#!/bin/bash
HERE=`pwd`
set -e
for i in ${HERE}/../lib_client \
         ${HERE}/crcanvas_gtk \
         ${HERE}/src/bank \
         ${HERE}/src/interface \
         ${HERE}/src/subsets \
         ${HERE}/src/bdplot ;
do 
  echo
  echo DOING:
  echo ${i}
  echo
  echo
  cd ${i}
  ./cmd
done

echo
echo DOING:
echo ${HERE}
echo
echo
cd ${HERE}

make clean
make


