#!/bin/bash
set -e
HERE=`pwd`
TARGZ=${HERE}/../../../targz_store
TARGET=${HERE}/.
#----------------------------------------------------------
cd ${TARGET}
rm -rf ${TARGET}/spice-protocol
tar xvf ${TARGZ}/spice-protocol_*.tar.gz
cd ${HERE}/spice-protocol
meson --default-library=static --prefix=${TARGET} --datadir=${TARGET} \
      --libdir=${TARGET} --includedir=${TARGET} build
cd build
ninja
ninja install
#----------------------------------------------------------
cd ${TARGET}
rm -rf ${TARGET}/spice
tar xvf ${TARGZ}/spice_*.tar.gz
cd ${TARGET}/spice/server/
sed -i s"/library('spice-server'/library('cloonix-spice-server'/" meson.build
cd ${TARGET}/spice
sed -i s"/UNKNOWN/0.14.0/" build-aux/git-version-gen
sed -i 13s"/true/false/" meson_options.txt
sed -i 41s"/true/false/" meson_options.txt
sed -i 52s"/true/false/" meson_options.txt
sed -i s"/^run_command/#run_command/" meson.build
export PKG_CONFIG_PATH=${TARGET}/pkgconfig
meson --default-library=static --prefix=${TARGET} --datadir=${TARGET} \
      --libdir=${TARGET} --includedir=${TARGET} build
cd build
ninja
ninja install
#----------------------------------------------------------
cd ${TARGET}
rm -rf ${TARGET}/usbredir
tar xvf ${TARGZ}/usbredir_*.tar.gz
cd ${HERE}/usbredir/usbredirhost
sed -i s"/libusbredirhost/libcloonix-usbredirhost/" meson.build
sed -i s"/library('usbredirhost'/library('cloonix-usbredirhost'/" meson.build
cd ${HERE}/usbredir/usbredirparser
sed -i s"/libusbredirparser/libcloonix-usbredirparser/" meson.build
sed -i s"/library('usbredirparser'/library('cloonix-usbredirparser'/" meson.build
cd ${HERE}/usbredir
sed -i s"/subdir('tests')/#subdir('tests')/" meson.build
meson  --default-library=static --prefix=${TARGET} --datadir=${TARGET} \
       --libdir=${TARGET} --includedir=${TARGET} build
cd build
ninja
ninja install
#----------------------------------------------------------
