#!/bin/bash
#----------------------------------------------------------------------#
DEBIAN_REPO="http://deb.debian.org/debian"

#----------------------------------------------------------------------#
ROOTFS=/root/hirsute.img
#----------------------------------------------------------------------#
fct_check_uid()
{
  if [ $UID != 0 ]; then
    echo you must be root
    exit -1
  fi
}
#----------------------------------------------------------------------#
fct_check_losetup()
{
  modprobe loop
  if [[ "$(losetup -a |grep loop10)" != "" ]]; then
    echo
    echo
    echo losetup -a |grep loop10 should give nothing, it gives:
    losetup -a grep loop10
    echo
    exit -1
  fi
}
#----------------------------------------------------------------------#

#########################################################################
fct_check_uid
set +e
if [ -e $ROOTFS ]; then
  echo $ROOTFS already exists
  exit 1
fi
fct_check_losetup
set -e
#-----------------------------------------------------------------------#
dd if=/dev/zero of=${ROOTFS} bs=500M count=10
mkfs.ext4 ${ROOTFS}
losetup -fP ${ROOTFS}
mkdir -p /tmp/wkmntloops
DEVLOOP=$(losetup -l | grep ${ROOTFS} | awk '{print $1}')
echo $DEVLOOP
mount -o loop $DEVLOOP /tmp/wkmntloops
INCLUDES="openssh-client,vim,bash-completion,net-tools,tcpdump"
COMPONENT="kernel,multiverse,universe,main"

debootstrap --no-check-certificate \
	    --no-check-gpg \
            --arch amd64 \
            --include=${INCLUDES} \
            --components=${COMPONENT} \
            hirsute \
            /tmp/wkmntloops ${REPO_STRETCH}


DEFVIM=/tmp/wkmntloops/usr/share/vim/vim82/defaults.vim
sed -i s"/filetype plugin/\"filetype plugin/" $DEFVIM
sed -i s"/set mouse/\"set mouse/" $DEFVIM

umount /tmp/wkmntloops
losetup -d $DEVLOOP
rmdir /tmp/wkmntloops
#-----------------------------------------------------------------------#
mv ${ROOTFS} /home/perrier/cloonix_data/bulk
#-----------------------------------------------------------------------#

