#!/bin/bash
#-----------------------------------------------------------------------#
HERE=`pwd`
OPENWRT=https://downloads.openwrt.org/releases/21.02.3/targets/x86/64
OPENWRT_IMG=openwrt-21.02.3-x86-64-generic-ext4-rootfs.img

wget https://downloads.openwrt.org/releases/21.02.3/targets/x86/64/openwrt-21.02.3-x86-64-generic-ext4-rootfs.img.gz


for i in qemu-img gunzip wget; do
  path_bin=$(which $i)
  if [ -z $path_bin ]; then
    echo $i  DOES NOT EXIST
    exit -1
  fi
done

if [ $UID != 0 ]; then
  echo you must be root
  exit -1
fi
modprobe loop
if [[ "$(losetup -a )" != "" ]]; then
  echo
  echo
  echo losetup -a should give nothing, it gives:
  losetup -a
  echo
  exit -1
fi
#---------------------------------------------------------------------------#
mkdir -p /tmp/wkmntloops
wget --no-check-certificate ${OPENWRT}/${OPENWRT_IMG}.gz
gunzip ${OPENWRT_IMG}.gz
mv ${OPENWRT_IMG} openwrt.img
losetup /dev/loop0 openwrt.img
mount /dev/loop0 /tmp/wkmntloops
#--------------------------------------------------------------------#
  cat > /tmp/wkmntloops/chroot_cmds  << "EOF"
#!/bin/ash
passwd << "INEOF"
root
root
INEOF
EOF

chmod +x /tmp/wkmntloops/chroot_cmds
chroot /tmp/wkmntloops /chroot_cmds
rm -f /tmp/wkmntloops/chroot_cmds
#---------------------------------------------------------------------#
umount /tmp/wkmntloops
losetup -d /dev/loop0
rmdir /tmp/wkmntloops
#-----------------------------------------------------------------------#
mv openwrt.img /home/perrier/cloonix_data/bulk
#-----------------------------------------------------------------------#





