#!/bin/bash
HERE=`pwd`
TARGZ=../../../targz_store

cd ${TARGZ}
VWIFI=$(ls vwifi_*)
VWIFI=${VWIFI%%.*}
cd ${HERE}

tar xvf ${TARGZ}/${VWIFI}.tar.gz
diff -Naur vwifi vwifi_tainted > ${HERE}/tmp_vwifi.patch


