#!/bin/bash
set -e
NSH="/usr/libexec/cloonix/client/cloonix-hide-dirs"
if [ 1 -gt ${#} ]; then
  echo  cloonix_name needed as parameter.
  exit
fi
cloonix_name=$1
shift 1
${NSH} "dsh" ${cloonix_name}

