#!/bin/bash
set -e
if [ 2 -gt ${#} ]; then
  echo  cloonix_name and vm_name needed as parameter.
  exit 1
fi
NSH="/usr/libexec/cloonix/client/cloonix-hide-dirs"
cloonix_name=$1
vm_name=$2
shift 2
${NSH} "scp" ${cloonix_name} ${vm_name} "$@"


