#!/bin/bash
set -e
if [ 3 -gt ${#} ]; then
  echo  cloonix_name source dest needed as parameter.
  exit 1
fi
NSH="/usr/libexec/cloonix/common/cloonix-hide-dirs"

if [ 3 -eq ${#} ]; then
${NSH} "scp" ${1} ${2} ${3}
else
${NSH} "scp" ${1} ${2} ${3} ${4}
fi


