#!/bin/bash
set -e
if [ 2 -gt ${#} ]; then
  echo  cloonix_name and vm_name needed as parameter.
  exit 1
fi
NSH="/usr/libexec/cloonix/cloonfs/cloonix-hide-dirs"
cloonix_name=$1
vm_name=$2
if [ 2 -eq ${#} ]; then
${NSH} "ssh" ${cloonix_name} ${vm_name}
else
shift 2
${NSH} "ssh" ${cloonix_name} ${vm_name} "$*"
fi


