#!/usr/libexec/cloonix/cloonfs/bin/bash
set -e
NSH="/usr/libexec/cloonix/cloonfs/bin/cloonix-hide-dirs"
CLOONIX_CFG="/usr/libexec/cloonix/cloonfs/etc/cloonix.cfg"


if [ 2 -gt ${#} ]; then
  echo error input params
  echo  "cloonix_osh <nemo> <vm_name> [cmd]"
  exit 1
fi

cloonix_name=$1
vm_name=$2

LINE_CONFIG=$(cat $CLOONIX_CFG)
LINE_CONFIG=$(echo $LINE_CONFIG)
cloonix_info="${LINE_CONFIG##*CLOONIX_NET: $cloonix_name \{}"
cloonix_info="${cloonix_info%%\}*}"

ip=$(echo $cloonix_info |awk '{print $2}')
port=$(echo $cloonix_info |awk '{print $4}')
passwd=$(echo $cloonix_info |awk '{print $6}')

set +e
get_ip=$(cloonix_cli ${cloonix_name} cnf nat nat_${vm_name} whatip=${vm_name})
resp=${get_ip%%=*}
ip_vm=${get_ip##*=}
if [ "${resp}" != "OK OK" ]; then
  echo ${get_ip}
  exit
fi

if [ 2 -eq ${#} ]; then
${NSH} "osh" ${cloonix_name} ${vm_name} ${ip_vm}
else
shift 2
${NSH} "osh" ${cloonix_name} ${vm_name} ${ip_vm} "$*"
fi

