#!/bin/bash
set -e
if [ 3 -gt ${#} ]; then
  echo  cloonix_name vm_name eth_num needed as parameter.
  exit 1
fi

if [ -x "/cloonix/cloonfs/bin/cloonix-hide-dirs" ]; then
  NSH="/cloonix/cloonfs/bin/cloonix-hide-dirs"
else
  NSH="/usr/libexec/cloonix/cloonfs/bin/cloonix-hide-dirs"
fi

cloonix_name=$1
vm_name=$2
eth_num=$3
${NSH} "wsk" ${cloonix_name} ${vm_name} ${eth_num}


