#!/bin/bash
set -e
if [ 2 -ne ${#} ]; then
  echo  cloonix_name and vm_name needed as parameter.
  exit 1
fi
NSH="/usr/libexec/cloonix/cloonfs/cloonix-hide-dirs"
cloonix_name=$1
vm_name=$2
${NSH} "shk" ${cloonix_name} ${vm_name}


