#!/bin/bash
set -e
NSH="/usr/libexec/cloonix/client/cloonix-hide-dirs"
CLOONIX_CONFIG="/usr/libexec/cloonix/common/etc/cloonix.cfg"

#
# The following private id_rsa corresponds to the id_rsa.pub that
# is used in file step1_make_preconf_iso.sh for the cisco making.
#
rm -f /tmp/cloonix_private_id_rsa
cat > /tmp/cloonix_private_id_rsa << EOF
-----BEGIN RSA PRIVATE KEY-----
MIIEowIBAAKCAQEAxkepoiuYZD/HnpXL4raEarJi7EsMFkr5NoC/cv9SF8CPweIF
JM66qe0CUd9Jw97Ov9ulTLPnoUQYFbjb/abOa7etijRx3vsvahgQSjYpOBXCngkd
zooAvWymLYsBsZQo0QNtXdagP0lmti5eEX+/uCv/+IWGFx7tBT8UF8s58DruDRpm
dwzGgh/fr2FwOklxjQO71gkIzd/fpQXevsj93CsUH3UzTrvTn8BrfrKABAAeH2Qd
1yxTHRPcf9syEzMMA8YtwCPPO8vqobMt1tH6Yrl/c7DkxqCftWjPVx0mMJ/SHBOQ
P4NMVr+fE6R0Y1WuWVwojs86uLAtOFBl5i+VmwIDAQABAoIBAAlCzZyCdsKv6+3v
Ry+WoMavAEnTE4RzCgLOrqJ7ZGUxnEVM/jqC4VsQc9xJFpPsczGo26aifH4exRU2
pifJw7hqQtPCsVLd3pARAanFr9UrxwREnrzH21L9oSFdbb3Skrl4dII+hQuPrRlz
PveIRPcgLvt3mRS5YA6vrIuT9WfP85qt7QD4ibcDtb5+y93m0ayJty8YcgNCfqrF
VdW40deeC4xzfBR6Q6edF4lho9O8Zl/9OTI3n/aS6xBl3qdN9y2hcIU9VTJQPErk
jJMPb2ugZCeiXiFCPcZQGwn7oVeQsIbkBpkA7aYjATgIfsr7FVjZu8xkEhxr5aEQ
9i/eiKECgYEA/zfrqdCvaYxi2bOa3u1nvRSsUbwsH6OFYye5WQhClqig+MQLN8Nu
QZop4NswfwFnsIundcDgWzlT/EnuIA6qcsEW8Y4jRTi1uJqJDyDS3dHFXQHnu6c8
oEoHJ5r32r93kbWRaJm+sbBrTOA2bH9bJX5NvfYCHMl0fbiY3UceRqsCgYEAxuMa
29qBmjdwL11Udk/rMOLGABIITqL+PtRxsDGT54qG6jkfK6Lb0ZfMo7BfXM65Xr3W
e875ErgaZZQaJOd2E1CEEWb0NWe+lMmfwJKz4q/p3bI5FL9ZX6Jr/wpJUDFXv051
pxn5PPm9gFzvgkoFYSK5DoG6wmYoh4aGgPD3rNECgYEAhEHMZEH6xO21RC/o7+GD
Qt71tZ2YGAU7WHj7egHnz/8u+/tL/OfPuTtUvGuaJBbsTvbwHvuGyH9a4IDHX+F5
vuIFK8SGzpZmxXV/1VEjNURBzMLx/bLang3+yy1ph/h01BONePFDev17fWkriuos
p69eRjS4P4a+UXBZ90GllOUCgYBVpWrljj0Nah43Z1t974B6ds2JLjrBklMmP1oN
4+urY+4hYyPXKLS8l0AapVMLpkIRWHLKsiB0PS+w2ow/pCUmwB9/VvSHIvvhGspe
pU4tqk9tltgZ5STZmBolpApaLEV7LpBfu0GnTmyaoGrLkpCqecdzRc5k9JUzd2zo
jdw6YQKBgEB5T9gNNRpjjD2D8yJmyVDsCcHKUWO4kPejGhIQJ1hFLBsFv3DFmga8
Ku+HluGo0TDABJUv1JBpVDeHBNprX3mHgud4fxKvoeG4eBfrjW5QsqIL34mrzT2b
Tf6PmCDYsKOA79p2IYNG0aRiVMyTjb0JaDi/QJY65WR6Q5uoyCae
-----END RSA PRIVATE KEY-----
EOF
chmod 400 /tmp/cloonix_private_id_rsa

cloonix_name=$1

if [ 3 -gt ${#} ]; then
  echo error input params
  echo  "cloonix_osh <nemo> <vm_name:files> files"
  echo  "cloonix_osh <nemo> files <vm_name:files>"
  exit 1
fi

if (( ${#} == 4 )); then
  if [ "$2" != "-r" ]; then
    echo error input params
    exit 1
  fi
  recurs="y"
  src_side=$3
  dst_side=$4
else
  recurs="n"
  src_side=$2
  dst_side=$3
fi

case $src_side in

  *[:]* )
    file_src=${src_side##*:}
    vm_name=${src_side%%:*}
    case $dst_side in
      *[:]* )
        echo Bad input
        exit 1
      ;;
      *)
      file_source="dist"
      file_dst=$dst_side
      ;;
    esac
  ;;

  *)
  file_src=${src_side}
  case $dst_side in
    *[:]* )
      file_dst=${dst_side##*:}
      vm_name=${dst_side%%:*}
      file_source="loc"
    ;;
    *)
        echo Bad input
        exit 1
    ;;
  esac
  ;;
esac

set +e
get_ip=$(cloonix_cli ${cloonix_name} cnf nat nat_${vm_name} whatip=${vm_name})
resp=${get_ip%%=*}
ip_vm=${get_ip##*=}
if [ "${resp}" != "OK OK" ]; then
  echo ${get_ip}
  exit
fi

${NSH} "ocp" ${cloonix_name} ${vm_name} ${ip_vm} ${file_src} ${file_dst} ${recurs} ${file_source}


