#!/bin/bash
set -e

CLOONIX_CONFIG="/usr/libexec/cloonix/common/etc/cloonix.cfg"
if [ ! -f $CLOONIX_CONFIG ]; then
  echo "ERROR: $CLOONIX_CONFIG not found"
  exit 1
fi
OVS_BIN="/usr/libexec/cloonix/server/cloonix-ovs-vsctl"
if [ ! -x $OVS_BIN ]; then
  echo "ERROR: $OVS_BIN not found"
  exit 1
fi
LIST=$(cat $CLOONIX_CONFIG |grep CLOONIX_NET: | awk '{print $2}')
if (( ${#} < 2 )); then
  echo
  echo "cloonix_ovs <net> --help"
  echo "cloonix_ovs <net> show"
  echo
  echo net:
  echo $LIST
  echo
  exit 1
fi
cloonix_name=$1
shift 1

export FONTCONFIG_FILE="/usr/libexec/cloonix/common/etc/fonts/fonts.conf"
export XDG_CONFIG_HOME="/usr/libexec/cloonix/common/share"
export XDG_DATA_HOME="/usr/libexec/cloonix/common/share"
export XDG_RUNTIME_DIR="/var/lib/cloonix/${cloonix_name}"
export QT_PLUGIN_PATH="/usr/libexec/cloonix/common/lib/qt6/plugins"
export QT_X11_NO_MITSHM="1"
export QT_XCB_NO_MITSHM="1"
export GTK_IM_MODULE_FILE="/usr/libexec/cloonix/common/lib/gtk-3.0/3.0.0/immodules.cache"
export GDK_PIXBUF_MODULE_FILE="/usr/libexec/cloonix/common/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache"
export GST_PLUGIN_SYSTEM_PATH="/usr/libexec/cloonix/common/lib/gstreamer-1.0"
export NO_AT_BRIDGE="1"
export OVS_RUNDIR="/var/lib/cloonix/${cloonix_name}"
export OVS_DBDIR=$OVS_RUNDIR

sudo ${OVS_BIN} --db=unix:${OVS_DBDIR}/ovsdb_server.sock "$@"
