#!/bin/bash
set -e

CLOONIX_CONFIG="/usr/libexec/cloonix/common/etc/cloonix.cfg"
if [ ! -f $CLOONIX_CONFIG ]; then
  echo "ERROR: $CLOONIX_CONFIG not found"
  exit 1
fi
OVS_BIN="/usr/libexec/cloonix/server/cloonix-ovs-vsctl"
if [ ! -x $OVS_BIN ]; then
  echo "ERROR: $OVS_BIN not found"
  exit 1
fi
LIST=$(cat $CLOONIX_CONFIG |grep CLOONIX_NET: | awk '{print $2}')
if (( ${#} < 2 )); then
  echo
  echo "cloonix_ovs <net> --help"
  echo "cloonix_ovs <net> show"
  echo
  echo net:
  echo $LIST
  echo
  exit 1
fi
cloonix_name=$1

source /usr/libexec/cloonix/common/etc/cloonix_exports

shift 1

sudo ${OVS_BIN} --db=unix:${OVS_DBDIR}/ovsdb_server.sock "$@"
