#!/bin/bash
set -e
if [ 2 -ne ${#} ]; then
  echo  cloonix_name and vm_name needed as parameter.
  exit 1
fi

if [ -x "/cloonix/cloonfs/bin/cloonix-hide-dirs" ]; then
  NSH="/cloonix/cloonfs/bin/cloonix-hide-dirs"
else
  NSH="/usr/libexec/cloonix/cloonfs/bin/cloonix-hide-dirs"
fi

cloonix_name=$1
vm_name=$2
${NSH} "shc" ${cloonix_name} ${vm_name}


