#!/bin/bash
set -e
if [ 2 -gt ${#} ]; then
  echo  cloonix_name and vm_name needed as parameter.
  exit 1
fi

if [ -x "/cloonix/cloonfs/bin/cloonix-hide-dirs" ]; then
  NSH="/cloonix/cloonfs/bin/cloonix-hide-dirs"
else
  NSH="/usr/libexec/cloonix/cloonfs/bin/cloonix-hide-dirs"
fi

cloonix_name=$1
vm_name=$2
if [ 2 -eq ${#} ]; then
${NSH} "ssh" ${cloonix_name} ${vm_name}
else
shift 2
${NSH} "ssh" ${cloonix_name} ${vm_name} "$*"
fi


