#!/usr/libexec/cloonix/cloonfs/bash
set -e
NSH="/usr/libexec/cloonix/cloonfs/cloonix-hide-dirs"
if [ 2 -gt ${#} ]; then
  echo  cloonix_name and cmd needed as parameter.
  ${NSH} "cli"
  exit
fi
cloonix_name=$1
shift 1
${NSH} "cli" ${cloonix_name} "$@"

