#!/bin/bash
set -e

CLOONIX_CONFIG="/usr/libexec/cloonix/common/etc/cloonix.cfg"
if [ ! -f $CLOONIX_CONFIG ]; then
  echo "ERROR: $CLOONIX_CONFIG not found"
  exit 1
fi
WIRE="/usr/libexec/cloonix/server/cloonix-wireshark"

OPTIONS="-o capture.no_interface_load:TRUE \
         -o gui.ask_unsaved:FALSE"

source /usr/libexec/cloonix/common/etc/cloonix_exports

${WIRE} ${OPTIONS}

