#!/bin/bash
set -e
if [ 1 -gt ${#} ]; then
  echo  cloonix_name and cmd needed as parameter.
  exit 1
fi

#  if [ $(egrep -c cloonix-init /proc/1/cmdline) -gt 0 ]; then 
#    export DISPLAY=:713
#    export XAUTHORITY=/tmp/cloonix_proxy/Xauthority
#  fi

if [ -z $DISPLAY ] ; then
  echo DISPLAY NOT SET gui will not work
  exit 1
fi

NSH="/usr/libexec/cloonix/common/cloonix-hide-dirs"
cloonix_name=$1
${NSH} "gui" ${cloonix_name}

