#!/bin/bash
set -e
NSH="/usr/libexec/cloonix/cloonfs/bin/cloonix-hide-dirs"
CLOONIX_CFG="/usr/libexec/cloonix/cloonfs/etc/cloonix.cfg"

cloonix_name=$1

if [ 3 -gt ${#} ]; then
  echo error input params
  echo  "cloonix_osh <nemo> <vm_name:files> files"
  echo  "cloonix_osh <nemo> files <vm_name:files>"
  exit 1
fi

if (( ${#} == 4 )); then
  if [ "$2" != "-r" ]; then
    echo error input params
    exit 1
  fi
  recurs="y"
  src_side=$3
  dst_side=$4
else
  recurs="n"
  src_side=$2
  dst_side=$3
fi

case $src_side in

  *[:]* )
    file_src=${src_side##*:}
    vm_name=${src_side%%:*}
    case $dst_side in
      *[:]* )
        echo Bad input
        exit 1
      ;;
      *)
      file_source="dist"
      file_dst=$dst_side
      ;;
    esac
  ;;

  *)
  file_src=${src_side}
  case $dst_side in
    *[:]* )
      file_dst=${dst_side##*:}
      vm_name=${dst_side%%:*}
      file_source="loc"
    ;;
    *)
        echo Bad input
        exit 1
    ;;
  esac
  ;;
esac

set +e
get_ip=$(cloonix_cli ${cloonix_name} cnf nat nat_${vm_name} whatip=${vm_name})
resp=${get_ip%%=*}
ip_vm=${get_ip##*=}
if [ "${resp}" != "OK OK" ]; then
  echo ${get_ip}
  exit
fi

${NSH} "ocp" ${cloonix_name} ${vm_name} ${ip_vm} ${file_src} ${file_dst} ${recurs} ${file_source}


