#!/bin/bash
set -e
CLOONIX_CONFIG="/usr/libexec/cloonix/common/etc/cloonix.cfg"
if [ ! -f $CLOONIX_CONFIG ]; then
  echo "ERROR: $CLOONIX_CONFIG not found"
  exit 1
fi
CTRL="/usr/libexec/cloonix/client/cloonix-ctrl"
if [ ! -x $CTRL ]; then
  echo "ERROR: $CTRL not found"
  exit 1
fi
cloonix_name=$1

source /usr/libexec/cloonix/common/etc/cloonix_exports

${CTRL} $CLOONIX_CONFIG "$@"

