#!/bin/bash
set -e
if [ 2 -gt ${#} ]; then
  echo  cloonix_name and vm_name needed as parameter.
  exit 1
fi

if [ -x "/cloonix/cloonfs/bin/cloonix-hide-dirs" ]; then
  NSH="/cloonix/cloonfs/bin/cloonix-hide-dirs"
else
  NSH="/usr/libexec/cloonix/cloonfs/bin/cloonix-hide-dirs"
fi

cloonix_name=$1
vm_name=$2
ID=$(cloonix_cli $cloonix_name dmp |grep "^$vm_name vm_id:" | awk '{print $3}')
if [ -z $ID ]; then
  echo BAD PARAM, either $cloonix_name or $vm_name
  exit 1
fi
${NSH} "ice" ${cloonix_name} ${vm_name} ${ID}

