#!/bin/bash
set -e
if [ 1 -gt ${#} ]; then
  echo  cloonix_name needed as parameter.
  exit
fi

if [ -x "/cloonix/cloonfs/bin/cloonix-hide-dirs" ]; then
  NSH="/cloonix/cloonfs/bin/cloonix-hide-dirs"
else
  NSH="/usr/libexec/cloonix/cloonfs/bin/cloonix-hide-dirs"
fi

cloonix_name=$1
${NSH} "dsh" ${cloonix_name}

