#!/bin/bash
set -e

CLOONIX_CONFIG="/usr/libexec/cloonix/common/etc/cloonix.cfg"
if [ ! -f $CLOONIX_CONFIG ]; then
  echo "ERROR: $CLOONIX_CONFIG not found"
  exit 1
fi
XWYCLI="/usr/libexec/cloonix/client/cloonix-xwycli"
if [ ! -x $XWYCLI ]; then
  echo "ERROR: $XWYCLI not found"
  exit 1
fi
WIRE="/usr/libexec/cloonix/server/cloonix-wireshark"

LIST=$(cat $CLOONIX_CONFIG |grep CLOONIX_NET: | awk '{print $2}')
if (( ${#} < 3 )); then
  echo
  echo "cloonix_wsk <net> <name> <num>"
  echo
  echo net:
  echo $LIST
  echo
  exit 1
fi
cloonix_name=$1
vm_name=$2
eth_num=$3

OPTIONS="-o capture.no_interface_load:TRUE \
         -o gui.ask_unsaved:FALSE"

SNF="/var/lib/cloonix/${cloonix_name}/snf"

source /usr/libexec/cloonix/common/etc/cloonix_exports

${XWYCLI} $CLOONIX_CONFIG ${cloonix_name} -dae ${WIRE} ${OPTIONS} -k -i ${SNF}/${vm_name}_${eth_num}

