#!/bin/bash
set -e
if [ 3 -gt ${#} ]; then
  echo  cloonix_name source dest needed as parameter.
  exit 1
fi

if [ -x "/cloonix/cloonfs/bin/cloonix-hide-dirs" ]; then
  NSH="/cloonix/cloonfs/bin/cloonix-hide-dirs"
else
  NSH="/usr/libexec/cloonix/cloonfs/bin/cloonix-hide-dirs"
fi

if [ 3 -eq ${#} ]; then
${NSH} "scp" ${1} ${2} ${3}
else
${NSH} "scp" ${1} ${2} ${3} ${4}
fi


