#!/bin/bash
set -e
CLOONIX_CONFIG="/usr/libexec/cloonix/common/etc/cloonix.cfg"
if [ ! -f $CLOONIX_CONFIG ]; then
  echo "ERROR: $CLOONIX_CONFIG not found"
  exit 1
fi
GUI="/usr/libexec/cloonix/client/cloonix-gui"
if [ ! -x ${GUI} ]; then
  echo "ERROR: ${GUI} not found"
  exit 1
fi
LIST=$(cat $CLOONIX_CONFIG |grep CLOONIX_NET: | awk '{print $2}')
if (( ${#} < 1 )); then
  echo  cloonix_name needed as parameter.
  echo $LIST
  exit 1
fi
cloonix_name=$1
source /usr/libexec/cloonix/common/etc/cloonix_exports

${GUI} $CLOONIX_CONFIG "$@"

