#!/bin/bash
HERE=`pwd`
TARGZ=${HERE}/../../../../targz_store

QEMU_NAME=qemu-3.1.0-rc1

rm -rf ${QEMU_NAME}

if [ ! -e tainted_qemu ]; then
  echo tainted_qemu directory must exist 
  exit 1
fi

tar xvf ${TARGZ}/${QEMU_NAME}.tar.xz
diff -Naur ${QEMU_NAME} tainted_qemu > tmp_cloonix_patch
rm -rf ${QEMU_NAME}
