#!/bin/bash
HERE=`pwd`
TARGZ=${HERE}/../../../../targz_store

QEMU_NAME=qemu_vip

rm -rf $QEMU_NAME

if [ -e tainted_qemu ]; then
  echo remove tainted_qemu directory and start again
  exit 1
fi

tar xvf ${TARGZ}/${QEMU_NAME}.tar.gz

mv $QEMU_NAME tainted_qemu

cd tainted_qemu

patch -f -p1 < ../cloonix_patch

