#!/bin/bash
set -e
HERE=`pwd`
TARGZ=${HERE}/../../../targz_store
TARGET=${HERE}/../spice_lib_client

if [ ! -e ${TARGET}/pkgconfig ]; then
  cd ${TARGET}
  ./cmd
fi

cd ${HERE}/spice_client
./patched_create

export PKG_CONFIG_PATH=${TARGET}/pkgconfig
export DESTDIR=${TARGET}
export PATH=${TARGET}/bin:$PATH
cd ${HERE}/spice_client/tainted_spice
sed -i s/UNKNOWN/0.39/ ./build-aux/git-version-gen

meson build
cd build
ninja -v install

cp -vf ${TARGET}/usr/local/bin/spicy ${HERE}/cloonix-spicy
cp -vf ${TARGET}/usr/local/libexec/spice-client-glib-usb-acl-helper ${HERE}/cloonix-spice-client-glib-usb-acl-helper
if [ -d  ${TARGET}/usr/local/lib/x86_64-linux-gnu ]; then
  cp -vf ${TARGET}/usr/local/lib/x86_64-linux-gnu/libcloonix-spice* ${TARGET}
else
  if [ -d  ${TARGET}/usr/local/lib64 ]; then
    cp -vf ${TARGET}/usr/local/lib64/libcloonix-spice* ${TARGET}
  else
    echo ERROR MISSING:
    echo ${TARGET}/lib/x86_64-linux-gnu
    echo ${TARGET}/lib64
    exit 1
  fi
fi
cd ${HERE}/spice_client
./allclean


