#!/bin/bash

export SRC_TREE_ROOT=`pwd`
if [ ! -e ${SRC_TREE_ROOT}/cloonix/cloonix_config ]; then
  echo NOT FOUND:
  echo ${SRC_TREE_ROOT}/cloonix/cloonix_config
  exit 1
fi

#----------------------------------------------------------
BUNDLE="${HOME}/cloonix_bundle"
rm -rf ${BUNDLE}
#----------------------------------------------------------
rm -rf ${SRC_TREE_ROOT}/xdoc/build/
#----------------------------------------------------------
CLOONSRC=${SRC_TREE_ROOT}/cloonix/cloonsrc
#----------------------------------------------------------
  for i in lib_rpc_clownix \
           lib_rpc_doors \
           lib_rpc_layout \
           lib_utils; do
    cd ${CLOONSRC}/${i}
    ./allclean
  done
#----------------------------------------------------------
  for i in proxy_sig \
           proxy_traf_tcp \
           proxy_traf_unix; do
    cd ${CLOONSRC}/tester_lib/${i}
    make clean
  done
#----------------------------------------------------------
  for i in  lib_client \
            ctrl \
            xwycli \
            cairo_canvas/crcanvas_gtk \
            cairo_canvas/src/bank \
            cairo_canvas/src/interface \
            cairo_canvas/src/subsets \
            cairo_canvas/src/bdplot \
            cairo_canvas ; do
    cd ${CLOONSRC}/${i}
    make clean
  done
#----------------------------------------------------------
  for i in hide_dirs \
           openssh \
           rxvt \
           spice \
           spice_lib_client \
           cloonix_dropbear ; do
    cd ${CLOONSRC}/${i}
    ./allclean
  done
#----------------------------------------------------------
  for i in  doorways \
            proxymous \
            suid_power \
            uml_cloonix_switch \
            create_insider_agents_iso/cloonix_agent ; do
    cd ${CLOONSRC}/${i}
    make clean
  done 
  rm -f ${CLOONSRC}/dtach/cloonix-dtach
  rm -f ${CLOONSRC}/cloonix-proxymous
#----------------------------------------------------------
  for i in vwifi \
           erase_workdir \
           apk_tools \
           iproute2 \
           ovs \
           proxymous \
           nginx \
           ovs_drv \
           ovs_snf \
           ovs_nat_main \
           ovs_c2c \
           ovs_a2b \
           qemu \
           xwy \
           wm2 \
           crun \
           frr \
           xorg \
           wireshark \
           spice_lib_server ; do
    cd ${CLOONSRC}/${i}
    ./allclean
  done
  rm -f ${CLOONSRC}/insider_agents/insider_agent_x86_64.iso
  rm -rf ${CLOONSRC}/insider_agents/cdrom
#----------------------------------------------------------
