#!/bin/bash
set -e
HERE=`pwd`
TMPBUILD=${HERE}/tmpbuild
CLOONIX_COMMON=${TMPBUILD}/cloonix/common
CLOONIX_SERVER=${TMPBUILD}/cloonix/server
CLOONIX_CLIENT=${TMPBUILD}/cloonix/client
#----------------------------------------------------------
echo TARGET:
echo $TMPBUILD
#----------------------------------------------------------
rm -rf ${TMPBUILD}
mkdir -p ${TMPBUILD}/targz_store
cp -f ${HERE}/targz_store/* ${TMPBUILD}/targz_store
cp -r ${HERE}/cloonix ${TMPBUILD}
#----------------------------------------------------------
for i in cloonix_dta cloonix_osh cloonix_xwy \
         cloonix_cli cloonix_gui cloonix_net cloonix_scp \
         cloonix_ice cloonix_ocp cloonix_ssh cloonix_ovs; do 
  mv ${TMPBUILD}/cloonix/${i} ${TMPBUILD}
done
#----------------------------------------------------------
  echo
  echo BUILDING COMMON
  echo
  sleep 1
#----------------------------------------------------------
  for i in meson_ninja \
           agent_dropbear \
           xwy \
           lib_rpc_clownix \
           lib_utils \
           lib_rpc_doors \
           lib_rpc_layout ; do

    cd ${CLOONIX_COMMON}/${i}
    echo
    echo DOING:
    echo ${CLOONIX_COMMON}/${i}
    echo
    echo
    sleep 2
    ./cmd
  done
#----------------------------------------------------------
  echo
  echo BUILDING SERVER
  echo
  sleep 1
#----------------------------------------------------------
  for i in  ovs \
            doorways \
            suid_power \
            uml_cloonix_switch \
            qemu \
            ovs_drv \
            ovs_snf \
            ovs_nat \
            ovs_c2c \
            dtach; do

    echo
    echo DOING:
    echo ${CLOONIX_SERVER}/${i}
    echo
    echo
    sleep 2
    cd ${CLOONIX_SERVER}/${i}
    ./cmd
  done

#----------------------------------------------------------
  echo
  echo BUILDING CLIENT
  echo
  sleep 1
#----------------------------------------------------------
  for i in  lib_client \
            ctrl \
            xwycli \
            cairo_canvas/crcanvas_gtk \
            cairo_canvas/src/bank \
            cairo_canvas/src/interface \
            cairo_canvas/src/subsets \
            cairo_canvas/src/bdplot \
            cairo_canvas \
            spice \
            openssh; do

    echo
    echo DOING:
    echo ${CLOONIX_CLIENT}/${i}
    echo
    echo
    sleep 2
    cd ${CLOONIX_CLIENT}/${i}
    ./cmd
  done
#----------------------------------------------------------

