#!/bin/bash
HERE=`pwd`
#----------------------------------------------------------
if [ $# != 1 ]; then
  echo Give cloonix to install as param
  exit
fi
#----------------------------------------------------------
CLOONIX=$1
if [ ! -e $CLOONIX ]; then
  echo NOT FOUND:
  echo $CLOONIX
  exit
fi
#----------------------------------------------------------
for i in cloonix_dta cloonix_mon cloonix_osh cloonix_xwy \
         cloonix_cli cloonix_gui cloonix_net cloonix_scp \
         cloonix_zor cloonix_ice cloonix_ocp \
         cloonix_ssh cloonix_ovs; do 
  rm -f /usr/local/bin/${i}
done
rm -rf /usr/local/bin/cloonix
mkdir -p /usr/local/bin
cd /usr/local/bin
tar zxvf ${HERE}/${CLOONIX}
chown -R root:root /usr/local/bin/cloonix*
SERV_BIN_PATH=/usr/local/bin/cloonix/server
MUTAP=${SERV_BIN_PATH}/muswitch/mutap/cloonix_mutap
MUOVS=${SERV_BIN_PATH}/muswitch/muovs/cloonix_muovs
SUID_POWER=${SERV_BIN_PATH}/suid_power/cloonix_suid_power
SNF_DPDK=${SERV_BIN_PATH}/dpdk/bin/cloonix_snf_dpdk
NAT_DPDK=${SERV_BIN_PATH}/dpdk/bin/cloonix_nat_dpdk
D2D_DPDK=${SERV_BIN_PATH}/dpdk/bin/cloonix_d2d_dpdk
USBHELP=/usr/local/bin/cloonix/common/spice/spice_lib
USBHELP+=/libexec/spice-client-glib-usb-acl-helper
chmod u+s ${MUTAP}
chmod u+s ${MUOVS}
chmod u+s ${SUID_POWER}
chmod u+s ${SNF_DPDK}
chmod u+s ${NAT_DPDK}
chmod u+s ${D2D_DPDK}
chmod u+s ${USBHELP}
#----------------------------------------------------------
rm -f ${HERE}/${CLOONIX}
#----------------------------------------------------------
