#!/bin/bash
#--------------------------------------------------------------------------
if [ $# == 1 ]; then
  action=$1 
  case "$1" in
    "run")
      printf "\n\tPackages to run cloonix will be installed.\n\n"
      depends_build=0
    ;;
    "build")
      printf "\n\tPackages to build cloonix will be installed.\n\n"
      depends_build=1
    ;;
    *)
     echo ERROR: bad input param \"run\" \"build\"
     exit
  esac
else
  echo
  echo ERROR: missing input param \"run\" or \"build\"
  echo if you want to compile cloonix choose build.
  echo
  exit
fi
#--------------------------------------------------------------------------
if [ ! -e /etc/os-release ]; then 
  printf "\n\tERROR: Not able to determine your distribution."
  printf "\n\tYou must install the packages by hand.\n\n"
  exit
fi
#--------------------------------------------------------------------------
name=$(cat /etc/os-release |grep PRETTY_NAME)
name=${name#*\"}
name=${name%% *}
#--------------------------------------------------------------------------
if [ -z $name ]; then
  printf "\n\tERROR: Not able to determine your distribution from os-release."
  printf "\n\tYou must install the packages by hand.\n\n"
  exit
fi
#--------------------------------------------------------------------------
fct_build_get_arch_packages()
{
  sed -i s"%#\[multilib\]%#\[multilib\]\nInclude = /etc/pacman.d/mirrorlist%" /etc/pacman.conf
  pacman --noconfirm --force -Syu \
             tar cdrkit rxvt-unicode base-devel \
             readline libevent gtk3 python2 python2-pyparsing \
             python2-six intltool opus polkit acl mesa libusb \
             gst-plugins-base ttf-dejavu orc python bison flex \
             wireshark

}
#--------------------------------------------------------------------------
fct_run_get_arch_packages()
{
  pacman --noconfirm --force -Syu \
             tar cdrkit rxvt-unicode readline libevent gtk3 \
             opus polkit acl mesa libusb gst-plugins-base \
             ttf-dejavu orc wireshark
}
#--------------------------------------------------------------------------
fct_build_get_debian_packages()
{
  apt-get -y install tar genisoimage rxvt-unicode build-essential \
                     intltool libncurses5-dev \
                     libjpeg-dev libusb-1.0-0-dev libsasl2-dev \
                     libopus-dev openssl libssl-dev libgtk-3-dev libcap-dev \
                     libevent-dev libreadline-dev python-pyparsing python-six \
                     libgstreamer-plugins-base1.0-dev libepoxy-dev libdrm-dev \
                     libgbm-dev libpolkit-gobject-1-dev libacl1-dev \
		     sudo zlib1g-dev liborc-0.4-dev libegl1-mesa-dev \
                     bison flex libjson-glib-dev wireshark
# For DPDK
   apt-get -y install build-essential coreutils linux-headers-amd64 \
                      libnuma-dev autoconf libtool pkg-config python3 \
                      python3-six libglib2.0-dev libpixman-1-dev \
                      libpcap-dev libmnl-dev libibverbs-dev 
}
#--------------------------------------------------------------------------
fct_run_get_debian_packages()
{
  apt-get -y install tar genisoimage rxvt-unicode libusb-1.0 libopus0 \
                     libgtk-3-0 libepoxy0 libsasl2-2 \
                     libgstreamer-plugins-base1.0 liborc-0.4-0 libgbm1 \
                     wireshark
}
#--------------------------------------------------------------------------
fct_build_get_centos_packages()
{
  yum -y install \
         tar genisoimage xterm make gcc gcc-c++ m4 bc \
         glibc-devel.x86_64 libstdc++-devel.x86_64 \
         intltool ncurses-devel libjpeg-turbo-devel libusb-devel \
         libgusb-devel cyrus-sasl-devel opus-devel openssl openssl-devel \
         gtk3-devel libcap-devel libevent-devel readline-devel \
         pyparsing python-six gstreamer1-plugins-base-devel \
         libepoxy-devel polkit-devel libacl-devel \
         dejavu-serif-fonts mesa-libgbm-devel orc-devel \
         mesa-libEGL-devel bison flex wireshark
# libpcap-devel
}
#--------------------------------------------------------------------------
fct_run_get_centos_packages()
{
  yum -y install \
         tar genisoimage gtk3 xterm libevent libusb opus \
         cyrus-sasl dejavu-serif-fonts libepoxy polkit libacl \
         gstreamer1-plugins-base libjpeg-turbo orc mesa-libgbm \
         wireshark
}
#--------------------------------------------------------------------------
fct_build_get_fedora_packages()
{
  dnf -y install \
         tar genisoimage rxvt-unicode make gcc gcc-c++ m4 bc \
         glibc-devel.x86_64 libstdc++-devel.x86_64 \
         libtool intltool ncurses-devel libjpeg-turbo-devel \
         libusb-devel cyrus-sasl-devel opus-devel openssl openssl-devel \
         gtk3-devel libcap-devel libevent-devel readline-devel \
         python pyparsing python-six gstreamer1-plugins-base-devel \
         libepoxy-devel libdrm-devel polkit-devel \
	 libacl-devel dejavu-serif-fonts mesa-libgbm-devel orc-devel \
         mesa-libEGL-devel bison flex wireshark
# libpcap-devel
}
#--------------------------------------------------------------------------
fct_run_get_fedora_packages()
{
  dnf -y install \
         tar genisoimage gtk3 rxvt-unicode libevent libusb opus \
         cyrus-sasl dejavu-serif-fonts libepoxy polkit libacl \
         gstreamer1-plugins-base libjpeg-turbo orc mesa-libgbm \
         wireshark
}
#--------------------------------------------------------------------------
fct_build_get_opensuse_packages()
{
  zypper --non-interactive install \
         tar genisoimage rxvt-unicode make gcc gcc-c++ m4 bc \
         libtool intltool ncurses-devel libjpeg62-devel \
         libusb-devel cyrus-sasl-devel libopus-devel openssl openssl-devel \
         gtk3-devel libcap-devel libevent-devel readline-devel \
         python python-pyparsing python-six dejavu-fonts patch \
         gstreamer-plugins-base-devel libepoxy-devel polkit-devel \
         libacl-devel glibc-locale libgbm-devel orc-devel \
         Mesa-libEGL-devel bison flex wireshark
# libpcap-devel
}
#--------------------------------------------------------------------------
fct_run_get_opensuse_packages()
{
  zypper --non-interactive install \
         tar genisoimage gtk3 rxvt-unicode libevent libusb \
         libopus0 cyrus-sasl dejavu-fonts libepoxy0 polkit libacl \
         gstreamer-plugins-base glibc-locale libgthread-2_0-0 \
         libjpeg62 libgbm1 liborc-0_4-0 wireshark
}
#--------------------------------------------------------------------------
if [ $UID != 0 ]; then
  printf "\n\tERROR: root privileges needed to install packages.\n\n"
  exit
fi
case "$name" in
  "Debian" | "Ubuntu" | "Kali")
    printf "\n\tInstall tool is apt-get.\n\n"
    apt-get --assume-yes update
    if [ $depends_build = 1 ]; then
      fct_build_get_debian_packages
    else
      fct_run_get_debian_packages
    fi
  ;;
  "CentOS")
    printf "\n\tInstall tool is yum.\n\n"
    yum update -y
    if [ $depends_build = 1 ]; then
      fct_build_get_centos_packages
    else
      fct_run_get_centos_packages
    fi
  ;;
  "Fedora")
    printf "\n\tInstall tool is dnf.\n\n"
    dnf update -y
    if [ $depends_build = 1 ]; then
      fct_build_get_fedora_packages
    else
      fct_run_get_fedora_packages
    fi
  ;;
  "openSUSE")
    printf "\n\tInstall tool is zypper.\n\n"
    zypper update -y
    if [ $depends_build = 1 ]; then
      fct_build_get_opensuse_packages
    else
      fct_run_get_opensuse_packages
    fi
  ;;
  "Arch")
    printf "\n\tInstall tool is pacman.\n\n"
    pacman -Syu
    if [ $depends_build = 1 ]; then
      fct_build_get_arch_packages
    else
      fct_run_get_arch_packages
    fi
  ;;
  *)
  printf "\n\tERROR: Your distribution: $name is not supported"
  printf "\n\tYou must install the packages by hand.\n\n"
  exit
  ;;
esac
#--------------------------------------------------------------------------



