#!/bin/bash
HERE=`pwd`
TMPBUILD=${HERE}/tmpbuild
TMPBUILD_BIS=${HERE}/tmpbuild_bis
#----------------------------------------------------------
if [ ! -e ${TMPBUILD}/cloonix/cloonix_config ]; then
  echo NOT FOUND:
  echo ${TMPBUILD}/cloonix/cloonix_config
  exit
fi
#----------------------------------------------------------
if [ ! -e ./cloonix/cloonix_config ]; then
  echo NOT FOUND:
  echo cloonix_config
  exit
fi
CLOONIX_VERSION=$(cat ./cloonix/cloonix_config | grep CLOONIX_VERSION)
CLOONIX_VERSION=${CLOONIX_VERSION#*=}
#----------------------------------------------------------
mkdir -p ${TMPBUILD_BIS}
cp -rf ${TMPBUILD}/cloonix* ${TMPBUILD_BIS}
#----------------------------------------------------------
CLOONIX_COMMON=${TMPBUILD_BIS}/cloonix/common
CLOONIX_SERVER=${TMPBUILD_BIS}/cloonix/server
CLOONIX_CLIENT=${TMPBUILD_BIS}/cloonix/client
#----------------------------------------------------------
  for i in allclean cli cmd libmdl libcli srv; do
    rm -rf ${CLOONIX_COMMON}/xwy/${i}
  done
#----------------------------------------------------------
  for i in cloonix_agent cmd \
           allclean cloonix_dropbear \
           cmd_alien cmd_local; do
    rm -rf ${CLOONIX_COMMON}/agent_dropbear/${i}
  done
#----------------------------------------------------------
  rm -rf ${CLOONIX_COMMON}/glob_include
#----------------------------------------------------------
  for i in lib_io_clownix lib_rpc_doors \
           lib_rpc_layout lib_utils lib_rpc_clownix \
           meson_ninja ; do
    rm -rf ${CLOONIX_COMMON}/${i}
  done
#----------------------------------------------------------
  for i in  doorways \
            suid_power \
            uml_cloonix_switch ; do
    rm -f ${CLOONIX_SERVER}/${i}/cmd
    rm -f ${CLOONIX_SERVER}/${i}/Makefile
    rm -rf ${CLOONIX_SERVER}/${i}/obj
    rm -rf ${CLOONIX_SERVER}/${i}/src
    rm -rf ${CLOONIX_SERVER}/${i}/include
  done
#----------------------------------------------------------
  for i in build \
           usr \
           src ; do
    rm -rf ${CLOONIX_SERVER}/ovs_drv/${i}
    rm -rf ${CLOONIX_SERVER}/ovs_snf/${i}
    rm -rf ${CLOONIX_SERVER}/ovs_nat/${i}
    rm -rf ${CLOONIX_SERVER}/ovs_c2c/${i}
  done
  for i in allclean cmd meson.build; do
    rm -f ${CLOONIX_SERVER}/ovs_drv/${i}
    rm -f ${CLOONIX_SERVER}/ovs_snf/${i}
    rm -f ${CLOONIX_SERVER}/ovs_c2c/${i}
  done
  for i in cmd allclean qemu_bin \
           cloonix_patch mkpatch patched_create ; do
    rm -f ${CLOONIX_SERVER}/qemu/${i}
  done
  rm -rf ${CLOONIX_SERVER}/qemu/tainted_qemu
#----------------------------------------------------------
  rm -f ${CLOONIX_SERVER}/dtach/cmd
  rm -f ${CLOONIX_SERVER}/dtach/dtach_source.tar.gz
#----------------------------------------------------------
  SCHEMA=${CLOONIX_SERVER}/ovs/share/openvswitch/vswitch.ovsschema
  cp -f ${SCHEMA} ${CLOONIX_SERVER}/ovs
  for i in allclean cmd ovs ovs.patch \
           mkpatch patched_create ; do
    rm -rf ${CLOONIX_SERVER}/ovs/${i}
  done
#----------------------------------------------------------
  rm -rf ${CLOONIX_CLIENT}/lib_client
#----------------------------------------------------------
  for i in allclean cmd include share spice_client usr ; do
    rm -rf ${CLOONIX_CLIENT}/spice/${i}
  done
#----------------------------------------------------------
  for i in crcanvas_gtk Makefile obj src allclean cmd ; do 
    rm -rf ${CLOONIX_CLIENT}/cairo_canvas/${i}
  done
#----------------------------------------------------------
  for i in  ctrl xwycli ; do
    rm -f ${CLOONIX_CLIENT}/${i}/Makefile
    rm -rf ${CLOONIX_CLIENT}/${i}/obj
    rm -rf ${CLOONIX_CLIENT}/${i}/include
    rm -rf ${CLOONIX_CLIENT}/${i}/src
    rm -rf ${CLOONIX_CLIENT}/${i}/cmd
    rm -rf ${CLOONIX_CLIENT}/${i}/allclean
  done
#----------------------------------------------------------
  for i in tainted_openssh lib_doorways ; do
    rm -rf ${CLOONIX_CLIENT}/openssh/$i
  done
  for i in allclean cmd mkpatch openssh* patched_create ; do
    rm -f ${CLOONIX_CLIENT}/openssh/$i
  done
#----------------------------------------------------------
cd ${TMPBUILD_BIS}
tar zcvf ../cloonix-${CLOONIX_VERSION}.tar.gz .
rm -rf ${TMPBUILD_BIS}
#----------------------------------------------------------
