#!/bin/bash
#----------------------------------------------------------------------------#
set -e
WITH_FRR="__WITH_FRR__"
#----------------------------------------------------------------------------#
BUNDLE="${HOME}/cloonix_bundle"
if [ ! -e ${BUNDLE}/cloonix/cloonix_config ]; then
  echo NOT FOUND:
  echo ${BUNDLE}/cloonix/cloonix_config
  exit 1
fi
COMMON=${BUNDLE}/cloonix/common
CLIENT=${BUNDLE}/cloonix/client
SERVER=${BUNDLE}/cloonix/server
#----------------------------------------------------------------------------#
printf "\n\nBUILDING COMMON\n\n"
#----------------------------------------------------------------------------#
for i in "lib_io_clownix" \
         "lib_rpc_clownix" \
         "lib_utils" \
         "lib_rpc_doors" \
         "lib_rpc_layout" ; do

    cd ${COMMON}/${i}
    echo
    echo DOING:
    echo ${COMMON}/${i}
    echo
    echo
    ./cmd
done
#----------------------------------------------------------------------------#
printf "\n\nBUILDING CLIENT\n\n"
#----------------------------------------------------------------------------#
for i in  "hide_dirs" \
          "agent_dropbear" \
          "lib_client" \
          "ctrl" \
          "xwycli" \
          "rxvt" \
          "cairo_canvas" ; do
    echo
    echo DOING:
    echo ${CLIENT}/${i}
    echo
    echo
    cd ${CLIENT}/${i}
    ./cmd
done
#----------------------------------------------------------------------------#
printf "\n\nBUILDING SERVER\n\n"
#----------------------------------------------------------------------------#
  if [ "${WITH_FRR}" = "yes" ]; then
    echo DOING:
    echo ${SERVER}/frr
    echo
    echo
    cd ${SERVER}/frr
    ./cmd
  fi

  for i in  "apk_tools" \
            "xorg" \
            "wireshark" \
            "iproute2" \
            "crun" \
            "dtach" \
            "proxymous" \
            "xwy" \
            "wm2" \
            "ovs" \
            "nginx" \
            "websockify-js" \
            "doorways" \
            "suid_power" \
            "uml_cloonix_switch" \
            "ovs_drv" \
            "ovs_snf" \
            "ovs_nat_main" \
            "ovs_a2b" \
            "ovs_c2c" ; do
    echo
    echo DOING:
    echo ${SERVER}/${i}
    echo
    echo
    cd ${SERVER}/${i}
    ./cmd
  done
#----------------------------------------------------------------------------#
  for i in  "openssh" \
            "spice" \
            "spice_lib_client"; do
      echo
      echo DOING:
      echo ${CLIENT}/${i}
      echo
      echo
      cd ${CLIENT}/${i}
      ./cmd
  done

  for i in  "spice_lib_server" \
            "qemu"; do
    echo
    echo DOING:
    echo ${SERVER}/${i}
    echo
    echo
    cd ${SERVER}/${i}
    ./cmd
  done

#----------------------------------------------------------------------------#
  echo DOING:
  echo ${SERVER}/create_insider_agents_iso
  cd ${SERVER}/create_insider_agents_iso
  ./cmd_mk_iso
#----------------------------------------------------------------------------#
printf "\n\nBUILDING ALL OK\n\n"
#----------------------------------------------------------------------------#
