#!/bin/bash
#----------------------------------------------------------------------------#
set -e
#----------------------------------------------------------------------------#
BUNDLE="${HOME}/cloonix_bundle"
if [ ! -e ${BUNDLE}/cloonix/cloonix_config ]; then
  echo NOT FOUND:
  echo ${BUNDLE}/cloonix/cloonix_config
  exit 1
fi
CLOONSRC=${BUNDLE}/cloonix/cloonsrc
#----------------------------------------------------------------------------#
printf "\n\nBUILDING CLOONSRC\n\n"
#----------------------------------------------------------------------------#
for i in "lib_io_clownix" \
         "lib_rpc_clownix" \
         "lib_utils" \
         "lib_rpc_doors" \
         "lib_rpc_layout" ; do

    cd ${CLOONSRC}/${i}
    echo
    echo DOING:
    echo ${CLOONSRC}/${i}
    echo
    echo
    ./cmd
done
#----------------------------------------------------------------------------#
printf "\n\nBUILDING CLOONSRC\n\n"
#----------------------------------------------------------------------------#
for i in  "hide_dirs" \
          "agent_dropbear" \
          "lib_client" \
          "ctrl" \
          "xwycli" \
          "rxvt" \
          "cairo_canvas" ; do
    echo
    echo DOING:
    echo ${CLOONSRC}/${i}
    echo
    echo
    cd ${CLOONSRC}/${i}
    ./cmd
done
#----------------------------------------------------------------------------#
printf "\n\nBUILDING CLOONSRC\n\n"
#----------------------------------------------------------------------------#
  echo DOING:
  echo ${CLOONSRC}/frr
  echo
  echo
  cd ${CLOONSRC}/frr
  ./cmd

  for i in  "apk_tools" \
            "xorg" \
            "wireshark" \
            "iproute2" \
            "crun" \
            "dtach" \
            "proxymous" \
            "xwy" \
            "wm2" \
            "ovs" \
            "nginx" \
            "websockify-js" \
            "doorways" \
            "suid_power" \
            "uml_cloonix_switch" \
            "ovs_drv" \
            "ovs_snf" \
            "ovs_nat_main" \
            "ovs_a2b" \
            "ovs_c2c" ; do
    echo
    echo DOING:
    echo ${CLOONSRC}/${i}
    echo
    echo
    cd ${CLOONSRC}/${i}
    ./cmd
  done
#----------------------------------------------------------------------------#
  for i in  "openssh" \
            "spice" \
            "spice_lib_client"; do
      echo
      echo DOING:
      echo ${CLOONSRC}/${i}
      echo
      echo
      cd ${CLOONSRC}/${i}
      ./cmd
  done

  for i in  "spice_lib_server" \
            "qemu"; do
    echo
    echo DOING:
    echo ${CLOONSRC}/${i}
    echo
    echo
    cd ${CLOONSRC}/${i}
    ./cmd
  done

#----------------------------------------------------------------------------#
  echo DOING:
  echo ${CLOONSRC}/create_insider_agents_iso
  cd ${CLOONSRC}/create_insider_agents_iso
  ./cmd_mk_iso
#----------------------------------------------------------------------------#
printf "\n\nBUILDING ALL OK\n\n"
#----------------------------------------------------------------------------#
