#!/bin/bash
#----------------------------------------------------------
if [ $UID != 0 ]; then
  printf "\n\tERROR: root privileges needed.\n\n"
  exit 1
fi
#----------------------------------------------------------
for i in common.tar.gz \
         client.tar.gz \
         server.tar.gz ; do
  if [ ! -e ${i} ]; then
    echo NOT FOUND:
    echo ${i}
    exit
  fi
done
#----------------------------------------------------------
rm -rf /usr/libexec/cloonix
rm -f  /usr/bin/cloonix_*
#----------------------------------------------------------
rm -rf /tmp/common
rm -rf /tmp/client
rm -rf /tmp/server
#----------------------------------------------------------
tar --directory=/tmp -xf common.tar.gz
tar --directory=/tmp -xf client.tar.gz
tar --directory=/tmp -xf server.tar.gz
#----------------------------------------------------------
mkdir -p /usr/libexec/cloonix/common
cp -rf /tmp/common/* /usr/libexec/cloonix/common
chown -R root:root /usr/libexec/cloonix/common
chmod 755 /usr/libexec/cloonix/common/*
#----------------------------------------------------------
mkdir -p /usr/libexec/cloonix/client
cp -rf /tmp/client/* /usr/libexec/cloonix/client
rm -rf /usr/libexec/cloonix/client/usr_bin
rm -rf /usr/libexec/cloonix/client/polkit-1
chown -R root:root /usr/libexec/cloonix/client
chmod 755 /usr/libexec/cloonix/client/*
#----------------------------------------------------------
for i in  cloonix_cli \
          cloonix_gui \
          cloonix_ice \
          cloonix_ocp \
          cloonix_osh \
          cloonix_rsh \
          cloonix_ovs \
          cloonix_scp \
          cloonix_ssh \
          cloonix_lsh \
          cloonix_dsh \
          cloonix_wsk ; do
  cp -vf /tmp/client/usr_bin/${i} /usr/bin
  cp -vf /tmp/client/usr_bin/${i} /usr/libexec/cloonix/common
done
#----------------------------------------------------------
if [ -d /usr/share/polkit-1/actions ]; then
  dstusb="/usr/share/polkit-1/actions/org.spice-space.lowlevelusbaccess.policy"
  srcusb="/tmp/client/polkit-1/actions/org.spice-space.lowlevelusbaccess.policy"
  if [ ! -e ${dstusb} ]; then
    cp -f ${srcusb} ${dstusb}
  fi
fi
chmod u+s /usr/libexec/cloonix/client/cloonix-spice-client-glib-usb-acl-helper
#----------------------------------------------------------
mkdir -p /usr/libexec/cloonix/server
cp -rf /tmp/server/* /usr/libexec/cloonix/server
rm -rf /usr/libexec/cloonix/server/usr_bin
chown -R root:root /usr/libexec/cloonix/server
chmod 755 /usr/libexec/cloonix/server/*
#----------------------------------------------------------
cp -vf /tmp/server/usr_bin/cloonix_net /usr/bin
#----------------------------------------------------------
for i in dumpcap \
         cloonix-crun \
         cloonix-ovs-drv \
         cloonix-ovs-snf \
         cloonix-ovs-nat \
         cloonix-ovs-a2b \
         cloonix-ovs-c2c \
         cloonix-ovs-vsctl \
         cloonix-suid-power ; do
  chmod u+s /usr/libexec/cloonix/server/${i}
done
#----------------------------------------------------------
rm -rf /tmp/common
rm -rf /tmp/client
rm -rf /tmp/server
#----------------------------------------------------------
