#!/bin/bash
#----------------------------------------------------------
WITH_KVM="__WITH_KVM__"
#----------------------------------------------------------
if [ $UID != 0 ]; then
  printf "\n\tERROR: root privileges needed.\n\n"
  exit 1
fi
#----------------------------------------------------------
if [ ! -e cloonfs/etc/cloonix.cfg ]; then
  echo NOT FOUND:
  echo cloonfs/etc/cloonix.cfg
  exit
fi
#----------------------------------------------------------
rm -rf /usr/libexec/cloonix
rm -f  /usr/bin/cloonix_*
#----------------------------------------------------------
mkdir -p /usr/libexec/cloonix/cloonfs
cp -rf cloonfs/* /usr/libexec/cloonix/cloonfs
chown -R root:root /usr/libexec/cloonix/cloonfs
chmod 755 -R /usr/libexec/cloonix
#----------------------------------------------------------
for i in  "cloonix_net" \
          "cloonix_cli" \
          "cloonix_gui" \
          "cloonix_ocp" \
          "cloonix_osh" \
          "cloonix_shk" \
          "cloonix_shc" \
          "cloonix_ovs" \
          "cloonix_scp" \
          "cloonix_ssh" \
          "cloonix_dsh" \
          "cloonix_lsh" \
          "cloonix_ice" \
          "cloonix_wsk" ; do
  cp -vf /usr/libexec/cloonix/cloonfs/bin/${i} /usr/bin
  chmod 755 /usr/bin/${i}
done
#----------------------------------------------------------
if [ "${WITH_KVM}" = "yes" ]; then
#  TODO  if [ -d /usr/share/polkit-1/actions ]; then
#  TODO    dstusb="/usr/share/polkit-1/actions/org.spice-space.lowlevelusbaccess.policy"
#  TODO    srcusb="/usr/libexec/cloonix/cloonfs/bin/polkit-1/actions/org.spice-space.lowlevelusbaccess.policy"
#  TODO    if [ ! -e ${dstusb} ]; then
#  TODO      cp -f ${srcusb} ${dstusb}
#  TODO    fi
#  TODO  fi
  chmod u+s /usr/libexec/cloonix/cloonfs/bin/cloonix-spice-client-glib-usb-acl-helper
  mkdir -p /var/lib/cloonix/cache/fontconfig
  chmod 777 /var/lib/cloonix/cache
  chmod 777 /var/lib/cloonix/cache/fontconfig
fi
#----------------------------------------------------------
for i in "cloonix-xwy-srv" \
         "cloonix-ovs-drv" \
         "cloonix-ovs-snf" \
         "cloonix-ovs-nat-main" \
         "cloonix-ovs-a2b" \
         "cloonix-ovs-c2c" \
         "cloonix-ovs-vsctl" \
         "cloonix-suid-power" ; do
  chmod u+s /usr/libexec/cloonix/cloonfs/bin/${i}
done
#----------------------------------------------------------
mkdir -p /var/lib/cloonix/bulk
chmod 777 /var/lib/cloonix/bulk
#----------------------------------------------------------
