#!/bin/bash
#----------------------------------------------------------
if [ $UID != 0 ]; then
  printf "\n\tERROR: root privileges needed.\n\n"
  exit 1
fi
#----------------------------------------------------------
if [ ! -e cloonfs/etc/cloonix.cfg ]; then
  echo NOT FOUND:
  echo cloonfs/etc/cloonix.cfg
  exit
fi
#----------------------------------------------------------
rm -rf /usr/libexec/cloonix
rm -f  /usr/bin/cloonix_*
mkdir -p /usr/libexec/cloonix
#----------------------------------------------------------
for i in "cloonfs" "startup_bin" "insider_agents"; do
  cp -rf ${i} /usr/libexec/cloonix
done
#----------------------------------------------------------
chown -R root:root /usr/libexec/cloonix
#----------------------------------------------------------
for i in  "cloonix_net" \
          "cloonix_cli" \
          "cloonix_gui" \
          "cloonix_ocp" \
          "cloonix_osh" \
          "cloonix_shk" \
          "cloonix_shc" \
          "cloonix_ovs" \
          "cloonix_scp" \
          "cloonix_ssh" \
          "cloonix_dsh" \
          "cloonix_lsh" \
          "cloonix_ice" \
          "cloonix_wsk" ; do
  cp -vf /usr/libexec/cloonix/cloonfs/bin/${i} /usr/bin
  chmod 755 /usr/bin/${i}
done
#----------------------------------------------------------
chmod -R 755 /usr/libexec/cloonix/
mkdir -p /var/lib/cloonix/bulk
chmod -R 777 /var/lib/cloonix
#----------------------------------------------------------
for i in "cloonix-spice-client-glib-usb-acl-helper" \
         "cloonix-suid-erase-workdir" \
         "cloonix-ovs-nat-main" \
         "cloonix-ovs-vsctl" \
         "cloonix-ovs-snf" \
         "cloonix-ovs-drv" \
         "cloonix-ovs-a2b" \
         "cloonix-ovs-c2c" \
         "cloonix-xwy-srv" \
         "cloonix-suid-power" ; do
  chmod u+s /usr/libexec/cloonix/cloonfs/bin/${i}
done
#----------------------------------------------------------
