#!/bin/bash
PURE_CRUN="no"
#----------------------------------------------------------------------#
if [ ${#} = 1 ]; then
  if [ "$1" = "i386" ]; then
    ARCH="i386"
  else
    if [ "$1" = "amd64" ]; then
      ARCH="amd64"
    else
      echo ERROR $0 param must be i386 or amd64
      exit
    fi
  fi
else
  echo ERROR $0 param must be i386 or amd64
  exit
fi
#----------------------------------------------------------------------#
if [ ! -n "${CLOONIX_TREE_ROOT}" ]; then
  echo PLEASE DEFINE CLOONIX_TREE_ROOT
  exit 1
fi
if [ ! -e ${CLOONIX_TREE_ROOT}/cloonix/cloonix_config ]; then
  echo NOT FOUND:
  echo ${CLOONIX_TREE_ROOT}/cloonix/cloonix_config
  exit 1
fi
PATCHELF=/tmp/patchelf/src/patchelf
TMPBUILD=${CLOONIX_TREE_ROOT}/build_tools/tmpbuild_server
TARGZ_STORE=${CLOONIX_TREE_ROOT}/targz_store
SERVER="${CLOONIX_TREE_ROOT}/build_tools/server"
COMMON="${CLOONIX_TREE_ROOT}/build_tools/common"
mkdir -p ${SERVER}/proxy
cp -rf ${TMPBUILD}/cloonix/server/* ${SERVER}
rm -rf ${SERVER}/iso_agent_dropbear
rm -rf ${SERVER}/create_insider_agents_iso
#----------------------------------------------------------
mkdir -p ${SERVER}/usr_bin
cp -f ${CLOONIX_TREE_ROOT}/cloonix/cloonix_net ${SERVER}/usr_bin
#----------------------------------------------------------
cp ${SERVER}/xwy/cloonix-xwy-srv ${SERVER}
rm -rf ${SERVER}/xwy
#----------------------------------------------------------
cp ${SERVER}/wm2/cloonix-novnc-wm2 ${SERVER}
rm -rf ${SERVER}/wm2
#----------------------------------------------------------
cp -f ${SERVER}/suid_power/cloonix-suid-power ${SERVER}
cp -f ${SERVER}/doorways/cloonix-doorways ${SERVER}
cp -f ${SERVER}/suid_power/cloonix-suid-power ${SERVER}
cp -f ${SERVER}/uml_cloonix_switch/cloonix-main-server ${SERVER}
for i in  doorways \
          suid_power \
          uml_cloonix_switch ; do
  rm -rf ${SERVER}/${i}
done
#----------------------------------------------------------
mkdir -p ${SERVER}/ovsschema
cp -f ${SERVER}/ovs/cloonix-vswitch.ovsschema ${SERVER}/ovsschema
for i in cloonix-ovsdb-server \
         cloonix-ovs-vswitchd \
         cloonix-ovsdb-tool \
         cloonix-ovs-appctl \
         cloonix-ovs-vsctl ; do
  cp -f ${SERVER}/ovs/bin/${i} ${SERVER}
done
rm -rf ${SERVER}/ovs
#----------------------------------------------------------
cp -f ${SERVER}/nginx/bin/cloonix-novnc-nginx ${SERVER}
rm -rf ${SERVER}/nginx
#----------------------------------------------------------
cp -f ${SERVER}/websockify-js/bin/cloonix-novnc-websockify-js ${SERVER}
rm -rf ${SERVER}/websockify-js
#----------------------------------------------------------
cp -f ${SERVER}/ovs_c2c/cloonix-ovs-c2c ${SERVER}
rm -rf ${SERVER}/ovs_c2c
#----------------------------------------------------------
cp -f ${SERVER}/ovs_a2b/cloonix-ovs-a2b ${SERVER}
rm -rf ${SERVER}/ovs_a2b
#----------------------------------------------------------
cp -f ${SERVER}/ovs_drv/cloonix-ovs-drv ${SERVER}
rm -rf ${SERVER}/ovs_drv
#----------------------------------------------------------
cp -f ${SERVER}/ovs_nat/cloonix-ovs-nat ${SERVER}
rm -rf ${SERVER}/ovs_nat
#----------------------------------------------------------
cp -f ${SERVER}/ovs_snf/cloonix-ovs-snf ${SERVER}
rm -rf ${SERVER}/ovs_snf
#----------------------------------------------------------
if [ "${PURE_CRUN}" = "no" ]; then
  rm -rf ${SERVER}/spice_lib_server
  mv ${SERVER}/qemu/cloonix-qemu-system ${SERVER}
  mv ${SERVER}/qemu/cloonix-qemu-img ${SERVER}
  for i in cmd allclean qemu_bin tainted_qemu \
           cloonix_patch mkpatch patched_create ; do
    rm -rf ${SERVER}/qemu/${i}
  done
fi
#----------------------------------------------------------
cp -f ${SERVER}/dtach/cloonix-dtach ${SERVER}
rm -rf ${SERVER}/dtach
#----------------------------------------------------------
cp -f ${SERVER}/script_pty/cloonix-scriptpty ${SERVER}
rm -rf ${SERVER}/script_pty
#----------------------------------------------------------
cp -f ${SERVER}/proxy_crun/cloonix-proxy-crun-access ${SERVER}/proxy
rm -rf ${SERVER}/proxy_crun
#----------------------------------------------------------
cp -f ${SERVER}/crun/crun_tainted/crun ${SERVER}/cloonix-crun
rm -rf ${SERVER}/crun
#----------------------------------------------------------
cp -f ${SERVER}/tmux/tmux/tmux ${SERVER}/cloonix-tmux
rm -rf ${SERVER}/tmux
#----------------------------------------------------------
if [ "${ARCH}" = "i386" ]; then
  echo NOT MAINTAINED!!!!!!!!!!!!!
  exit -1
else
  cp -f ${TARGZ_STORE}/xorg/built_objects_amd64/Xvfb ${SERVER}/cloonix-novnc-Xvfb
  cp -f ${TARGZ_STORE}/iproute2/built_objects_amd64/ip ${SERVER}
  cp -f ${TARGZ_STORE}/shark/built_objects_amd64/wireshark ${SERVER}/cloonix-wireshark
  cp -f ${TARGZ_STORE}/shark/built_objects_amd64/dumpcap ${SERVER}/cloonix-dumpcap
fi
#----------------------------------------------------------
cp -f /usr/bin/xauth     ${SERVER}/xauth
cp -f /usr/bin/xkbcomp   ${SERVER}/xkbcomp
cp -f /bin/bash          ${SERVER}/cloonix-bash
cp -f /bin/mount         ${SERVER}/cloonix-mount
cp -f /bin/umount        ${SERVER}/cloonix-umount 
cp -f /bin/mknod         ${SERVER}/cloonix-mknod 
cp -f /bin/chmod         ${SERVER}/cloonix-chmod
cp -f /bin/grep          ${SERVER}/cloonix-grep

for i in "ps" "awk" "osirrox" "fuse-zip"
do
  cp -f /usr/bin/${i}  ${SERVER}/cloonix-${i}
done

for i in "x11vnc" "xsetroot"
do
  cp -f /usr/bin/${i}  ${SERVER}/cloonix-novnc-${i}
done

#----------------------------------------------------------
openssl req -x509 -nodes -newkey rsa:3072 -keyout novnc.pem -subj "/CN=cloonix.net" -out ${SERVER}/novnc.pem -days 3650
#----------------------------------------------------------
if [ "${ARCH}" = "i386" ]; then
  LDLINUX="/usr/libexec/cloonix/common/lib32/ld-linux.so.2"
  RPATH_LIB="/usr/libexec/cloonix/common/lib:/usr/libexec/cloonix/common/lib/i386-linux-gnu"
else
  LDLINUX="/usr/libexec/cloonix/common/lib64/ld-linux-x86-64.so.2"
  RPATH_LIB="/usr/libexec/cloonix/common/lib:/usr/libexec/cloonix/common/lib/x86_64-linux-gnu"
fi
for i in `find ${SERVER} -maxdepth 1 -type f` ; do
  ${PATCHELF} --force-rpath  --set-rpath ${RPATH_LIB} ${i} 2>/dev/null
  ${PATCHELF} --set-interpreter ${LDLINUX} ${i} 2>/dev/null
done
#----------------------------------------------------------
cd ${CLOONIX_TREE_ROOT}/build_tools
gcc -o copy_libs fill_common.c
./copy_libs ${COMMON} client
./copy_libs ${SERVER} server
rm ./copy_libs
rm -rf ${TMPBUILD}
#----------------------------------------------------------
echo DONE pack_server
#----------------------------------------------------------
