#!/bin/bash
#----------------------------------------------------------------------#
if [ ${#} = 1 ]; then
  if [ "$1" = "i386" ]; then
    ARCH="i386"
  else
    if [ "$1" = "amd64" ]; then
      ARCH="amd64"
    else
      echo ERROR $0 param must be i386 or amd64
      exit
    fi
  fi
else
  echo ERROR $0 param must be i386, or amd64
  exit
fi
#----------------------------------------------------------------------#
if [ ! -n "${CLOONIX_TREE_ROOT}" ]; then
  echo PLEASE DEFINE CLOONIX_TREE_ROOT
  exit 1
fi
if [ ! -e ${CLOONIX_TREE_ROOT}/cloonix/cloonix_config ]; then
  echo NOT FOUND:
  echo ${CLOONIX_TREE_ROOT}/cloonix/cloonix_config
  exit 1
fi
TARGZ_STORE=${CLOONIX_TREE_ROOT}/targz_store
COMMON="${CLOONIX_TREE_ROOT}/build_tools/common"
pretty_name=$(cat /etc/os-release |grep PRETTY_NAME)
pretty_name=${pretty_name#*\"}
pretty_name=${pretty_name%% *}
case "$pretty_name" in
  "Debian")
  ;;
  *)
  printf "\n\tERROR: Your distribution: $pretty_name is not supported"
  exit
  ;;
esac

if [ "${ARCH}" = "i386" ]; then
  mkdir -p ${COMMON}/lib32
  mkdir -p ${COMMON}/lib/i386-linux-gnu
else
  mkdir -p ${COMMON}/lib64
  mkdir -p ${COMMON}/lib/x86_64-linux-gnu
fi

mkdir -p ${COMMON}/lib/locale
mkdir -p ${COMMON}/etc
mkdir -p ${COMMON}/share
mkdir -p ${COMMON}/share/dconf
mkdir -p ${COMMON}/share/locale
mkdir -p ${COMMON}/share/i18n/charmaps
mkdir -p ${COMMON}/share/i18n/locales
mkdir -p ${COMMON}/share/glib-2.0/schemas
mkdir -p ${COMMON}/share/X11/locale
mkdir -p ${COMMON}/lib/python3/dist-packages
mkdir -p ${COMMON}/lib/python3.11

#  cp /usr/lib/python3/dist-packages/distutils-precedence.pth ${COMMON}/lib/python3/dist-packages
for i in "websockify" \
         "websockify-0.10.0.egg-info" \
         "_distutils_hack" \
         "__pycache__" ; do
  cp -r /usr/lib/python3/dist-packages/${i} ${COMMON}/lib/python3/dist-packages
done


for i in "lib2to3" \
         "lib-dynload" \
         "encodings" \
         "re" \
         "collections" \
         "importlib" \
         "urllib" \
         "xml" \
         "email" \
         "logging" \
         "http" \
         "html" \
         "multiprocessing" ; do
  cp -r /usr/lib/python3.11/${i} ${COMMON}/lib/python3.11
done


for i in "enum.py" \
         "types.py" \
         "operator.py" \
         "functools.py" \
         "keyword.py" \
         "reprlib.py" \
         "copyreg.py" \
         "zipfile.py" \
         "warnings.py" \
         "contextlib.py" \
         "threading.py" \
         "_weakrefset.py" \
         "shutil.py" \
         "fnmatch.py" \
         "struct.py" \
         "pathlib.py" \
         "ipaddress.py" \
         "pkgutil.py" \
         "weakref.py" \
         "typing.py" \
         "platform.py" \
         "plistlib.py" \
         "datetime.py" \
         "string.py" \
         "base64.py" \
         "quopri.py" \
         "random.py" \
         "bisect.py" \
         "socket.py" \
         "selectors.py" \
         "calendar.py" \
         "locale.py" \
         "tempfile.py" \
         "textwrap.py" \
         "inspect.py" \
         "ast.py" \
         "dis.py" \
         "opcode.py" \
         "linecache.py" \
         "tokenize.py" \
         "token.py" \
         "subprocess.py" \
         "signal.py" \
         "csv.py" \
         "ssl.py" \
         "hashlib.py" \
         "optparse.py" \
         "traceback.py" \
         "socketserver.py" \
         "copy.py" \
         "mimetypes.py" \
         "pickle.py" \
         "_compat_pickle.py" \
         "stringprep.py" \
         "codecs.py" ; do
  cp /usr/lib/python3.11/${i} ${COMMON}/lib/python3.11
done
#----------------------------------------------------------
FROM_HERE=`pwd`
tar --directory=/tmp -xf ${TARGZ_STORE}/patchelf_*.tar.gz
cd /tmp/patchelf
make
cd $FROM_HERE
#----------------------------------------------------------
cp -Lrf /etc/fonts ${COMMON}/etc
rm -f ${COMMON}/etc/fonts/fonts.conf
cat > ${COMMON}/etc/fonts/fonts.conf << EOF
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
    <dir>/usr/libexec/cloonix/common/share</dir>
    <cachedir>/var/lib/cloonix/cache/fontconfig</cachedir>
    <cachedir prefix="xdg">fontconfig</cachedir>
</fontconfig>
EOF
cat > ${COMMON}/etc/locale.gen << EOF
en_US.UTF-8 UTF-8
EOF
cat > ${COMMON}/etc/locale.conf << EOF
LANG=C
EOF
cat > ${COMMON}/etc/hosts << EOF
127.0.0.1   localhost
EOF
cat > ${COMMON}/etc/group << EOF
audio:x:29:pulse
EOF
#----------------------------------------------------------
cp -f ${TARGZ_STORE}/dconf/user ${COMMON}/share/dconf
#----------------------------------------------------------
cp -Lrf /usr/lib/locale/* ${COMMON}/lib/locale
#----------------------------------------------------------
cd $FROM_HERE
for i in "icons" "mime" "themes" "fonts" "gtk-3.0" \
         "gstreamer-1.0" "alsa" "novnc" ; do
   cp -Lrf /usr/share/${i} ${COMMON}/share
done
for i in "en_GB" "en" "locale.alias" ; do
  cp -Lrf /usr/share/locale/${i} ${COMMON}/share/locale
done

#cp -Lrf /usr/share/X11 ${COMMON}/share
#cp -Lrf /etc/X11 ${COMMON}/etc


cp -Lrf /usr/share/X11/locale/en_US.UTF-8 ${COMMON}/share/X11/locale
cp -Lrf /usr/share/X11/locale/C ${COMMON}/share/X11/locale
cp -Lrf /usr/share/X11/locale/locale.dir ${COMMON}/share/X11/locale
cp -Lrf /usr/share/X11/xkb ${COMMON}/share/X11
cp -f /usr/share/X11/rgb.txt ${COMMON}/share/X11


cp -f /usr/share/i18n/charmaps/UTF-8.gz ${COMMON}/share/i18n/charmaps
for i in en_US en_GB i18n i18n_ctype iso14651_t1 translit_* ; do
  cp -f /usr/share/i18n/locales/${i} ${COMMON}/share/i18n/locales
done
cp -Lrf /usr/share/i18n/locales/iso14651_t1_common  ${COMMON}/share/i18n/locales
cp -f /usr/share/glib-2.0/schemas/gschemas.compiled ${COMMON}/share/glib-2.0/schemas
cd ${COMMON}/share/i18n/charmaps
gunzip UTF-8.gz
cd $FROM_HERE
#----------------------------------------------------------
if [ "${ARCH}" = "i386" ]; then
  tar --directory=${COMMON}/share -xf ${TARGZ_STORE}/shark/built_objects_i386/share_wireshark.tar.gz
else
  tar --directory=${COMMON}/share -xf ${TARGZ_STORE}/shark/built_objects_amd64/share_wireshark.tar.gz
fi
mv ${COMMON}/share/share_wireshark ${COMMON}/share/wireshark
#----------------------------------------------------------
if [ "${ARCH}" = "i386" ]; then
  cp -f /lib/ld-linux.so.2 ${COMMON}/lib32
else
  cp -f /lib64/ld-linux-x86-64.so.2 ${COMMON}/lib64
fi
cp -f ${CLOONIX_TREE_ROOT}/cloonix/cloonix_config ${COMMON}/etc/cloonix.cfg
#----------------------------------------------------------
if [ "${ARCH}" = "i386" ]; then
  SRCD="/usr/lib/i386-linux-gnu"
  DSTD="${COMMON}/lib/i386-linux-gnu"
else
  SRCD="/usr/lib/x86_64-linux-gnu"
  DSTD="${COMMON}/lib/x86_64-linux-gnu"
fi
for i in "gstreamer1.0" "gstreamer-1.0" \
         "gdk-pixbuf-2.0" "gtk-3.0" "gio" \
         "qt6" "pipewire-0.3" ; do
  cp -rf ${SRCD}/${i} ${DSTD}
done
mkdir -p ${DSTD}/gconv
cp -f ${SRCD}/gconv/gconv-modules.cache ${DSTD}/gconv
#----------------------------------------------------------
