#!/bin/bash
#----------------------------------------------------------------------#
if [ ${#} = 1 ]; then
  if [ "$1" = "i386" ]; then
    ARCH="i386"
    ARCHX="i386"
  else
    if [ "$1" = "amd64" ]; then
      ARCH="amd64"
      ARCHX="x86_64"
    else
      echo ERROR $0 param must be i386 or amd64
      exit
    fi
  fi
else
  echo ERROR $0 param must be i386 or amd64
  exit
fi
#----------------------------------------------------------------------#
if [ ! -n "${CLOONIX_TREE_ROOT}" ]; then
  echo PLEASE DEFINE CLOONIX_TREE_ROOT
  exit 1
fi
if [ ! -e ${CLOONIX_TREE_ROOT}/cloonix/cloonix_config ]; then
  echo NOT FOUND:
  echo ${CLOONIX_TREE_ROOT}/cloonix/cloonix_config
  exit 1
fi
PATCHELF=/tmp/patchelf/src/patchelf
VERSION=$(cat ${CLOONIX_TREE_ROOT}/cloonix/cloonix_config | grep CLOONIX_VERSION)
VERSION=${VERSION#*=}-${ARCH}
COMMON="${CLOONIX_TREE_ROOT}/build_tools/common"
#----------------------------------------------------------
if [ "${ARCH}" = "i386" ]; then
  LDLINUX="/usr/libexec/cloonix/common/lib32/ld-linux.so.2"
  RPATH_LIB="/usr/libexec/cloonix/common/lib:/usr/libexec/cloonix/common/lib/i386-linux-gnu"
else
  LDLINUX="/usr/libexec/cloonix/common/lib64/ld-linux-x86-64.so.2"
  RPATH_LIB="/usr/libexec/cloonix/common/lib:/usr/libexec/cloonix/common/lib/x86_64-linux-gnu"
fi
for i in `find ${COMMON} -maxdepth 1 -type f` ; do
  ${PATCHELF} --force-rpath --set-rpath ${RPATH_LIB} ${i} 2>/dev/null
  ${PATCHELF} --set-interpreter ${LDLINUX} ${i} 2>/dev/null
done
for i in `find ${COMMON}/lib -maxdepth 1 -type f` ; do
  ${PATCHELF} --force-rpath --set-rpath ${RPATH_LIB} ${i} 2>/dev/null
  ${PATCHELF} --set-interpreter ${LDLINUX} ${i} 2>/dev/null
done

for i in `find ${COMMON}/lib/${ARCHX}-linux-gnu -maxdepth 1 -type f` ; do
  ${PATCHELF} --force-rpath --set-rpath ${RPATH_LIB} ${i} 2>/dev/null
  ${PATCHELF} --set-interpreter ${LDLINUX} ${i} 2>/dev/null
done

for j in "qt6" "gdk-pixbuf-2.0" "gtk-3.0" "gio" "gconv" "gstreamer1.0" \
         "gstreamer1.0/gstreamer-1.0" "gstreamer-1.0" ; do
  for i in `find ${COMMON}/lib/${ARCHX}-linux-gnu/${j} -maxdepth 1 -type f` ; do
    ${PATCHELF} --force-rpath --set-rpath ${RPATH_LIB} ${i} 2>/dev/null
    ${PATCHELF} --set-interpreter ${LDLINUX} ${i} 2>/dev/null
  done
done

#----------------------------------------------------------
cd ${CLOONIX_TREE_ROOT}/build_tools
rm -f patchelf_bin
tar zcf common.tar.gz common
tar zcf client.tar.gz client
tar zcf server.tar.gz server
rm -rf common
rm -rf client
rm -rf server
mkdir -p cloonix-bundle-${VERSION}
cp -f install_cloonix    cloonix-bundle-${VERSION}
mv common.tar.gz cloonix-bundle-${VERSION}
mv client.tar.gz cloonix-bundle-${VERSION}
mv server.tar.gz cloonix-bundle-${VERSION}
cp -f ${CLOONIX_TREE_ROOT}/README cloonix-bundle-${VERSION}
cp -f ${CLOONIX_TREE_ROOT}/quickstart/ping_demo.sh cloonix-bundle-${VERSION}
#----------------------------------------------------------

