#!/bin/bash
#----------------------------------------------------------------------#
if [ ! -n "${CLOONIX_TREE_ROOT}" ]; then
  echo PLEASE DEFINE CLOONIX_TREE_ROOT
  exit 1
fi
if [ ! -e ${CLOONIX_TREE_ROOT}/cloonix/cloonix_config ]; then
  echo NOT FOUND:
  echo ${CLOONIX_TREE_ROOT}/cloonix/cloonix_config
  exit 1
fi
PATCHELF=/tmp/patchelf/src/patchelf
VERSION=$(cat ${CLOONIX_TREE_ROOT}/cloonix/cloonix_config | grep CLOONIX_VERSION)
VERSION=${VERSION#*=}
COMMON="${CLOONIX_TREE_ROOT}/build_tools/common"
#----------------------------------------------------------
LDLINUX="/usr/libexec/cloonix/common/lib64/ld-linux-x86-64.so.2"
RPATH_LIB="/usr/libexec/cloonix/common/lib:/usr/libexec/cloonix/common/lib/x86_64-linux-gnu"
for i in `find ${COMMON} -maxdepth 1 -type f` ; do
  ${PATCHELF} --force-rpath --set-rpath ${RPATH_LIB} ${i} 2>/dev/null
  ${PATCHELF} --set-interpreter ${LDLINUX} ${i} 2>/dev/null
done
for i in `find ${COMMON}/lib -maxdepth 1 -type f` ; do
  ${PATCHELF} --force-rpath --set-rpath ${RPATH_LIB} ${i} 2>/dev/null
  ${PATCHELF} --set-interpreter ${LDLINUX} ${i} 2>/dev/null
done

for i in `find ${COMMON}/lib/x86_64-linux-gnu -maxdepth 1 -type f` ; do
  ${PATCHELF} --force-rpath --set-rpath ${RPATH_LIB} ${i} 2>/dev/null
  ${PATCHELF} --set-interpreter ${LDLINUX} ${i} 2>/dev/null
done

for j in "gconv" "gstreamer-1.0" "gstreamer1.0" \
         "gstreamer1.0/gstreamer-1.0" "pipewire-0.3" \
         "qt6/plugins/platforms" ; do
  for i in `find ${COMMON}/lib/x86_64-linux-gnu/${j} -maxdepth 1 -type f` ; do
    ${PATCHELF} --force-rpath --set-rpath ${RPATH_LIB} ${i} 2>/dev/null
    ${PATCHELF} --set-interpreter ${LDLINUX} ${i} 2>/dev/null
  done
done
touch ${COMMON}/lib/x86_64-linux-gnu/libpthread.so.0
#----------------------------------------------------------
cd ${CLOONIX_TREE_ROOT}/build_tools
rm -f patchelf_bin
tar zcf common.tar.gz common
tar zcf server.tar.gz server
rm -rf common
rm -rf server
mkdir -p cloonix-bundle-${VERSION}
cp -f install_cloonix    cloonix-bundle-${VERSION}
mv common.tar.gz cloonix-bundle-${VERSION}
mv server.tar.gz cloonix-bundle-${VERSION}
cp -f ${CLOONIX_TREE_ROOT}/README cloonix-bundle-${VERSION}
#----------------------------------------------------------
echo DONE pack_common_after
#----------------------------------------------------------

