#!/bin/bash
#----------------------------------------------------------------------#
if [ ${#} = 1 ]; then
  if [ "$1" = "i386" ]; then
    ARCH="i386"
  else
    if [ "$1" = "amd64" ]; then
      ARCH="amd64"
    else
      echo ERROR $0 param must be i386 or amd64
      exit
    fi
  fi
else
  echo ERROR $0 param must be i386 or amd64
  exit
fi
#----------------------------------------------------------------------#
if [ ! -n "${CLOONIX_TREE_ROOT}" ]; then
  echo PLEASE DEFINE CLOONIX_TREE_ROOT
  exit 1
fi
if [ ! -e ${CLOONIX_TREE_ROOT}/cloonix/cloonix_config ]; then
  echo NOT FOUND:
  echo ${CLOONIX_TREE_ROOT}/cloonix/cloonix_config
  exit 1
fi
PATCHELF=/tmp/patchelf/src/patchelf
TMPBUILD=${CLOONIX_TREE_ROOT}/build_tools/tmpbuild_client
TARGZ_STORE=${CLOONIX_TREE_ROOT}/targz_store
CLIENT="${CLOONIX_TREE_ROOT}/build_tools/client"
COMMON="${CLOONIX_TREE_ROOT}/build_tools/common"
mkdir -p ${CLIENT}
cp -rf ${TMPBUILD}/cloonix/client/* ${CLIENT}
#----------------------------------------------------------
mkdir -p ${CLIENT}/usr_bin
for i in  cloonix_cli \
          cloonix_gui \
          cloonix_ice \
          cloonix_ocp \
          cloonix_osh \
          cloonix_rsh \
          cloonix_ovs \
          cloonix_scp \
          cloonix_ssh \
          cloonix_lsh \
          cloonix_dsh \
          cloonix_wsk ; do
  cp -f ${CLOONIX_TREE_ROOT}/cloonix/${i} ${CLIENT}/usr_bin
done
#----------------------------------------------------------
rm -rf ${CLIENT}/lib_client
rm -rf ${CLIENT}/spice_lib_client
#----------------------------------------------------------
cp -f  ${CLIENT}/hide_dirs/cloonix-hide-dirs ${CLIENT}
rm -rf ${CLIENT}/hide_dirs
#----------------------------------------------------------
cp -f  ${CLIENT}/agent_dropbear/cloonix-dropbear-scp ${CLIENT}
cp -f  ${CLIENT}/agent_dropbear/cloonix-dropbear-ssh ${CLIENT}
rm -rf ${CLIENT}/agent_dropbear
#----------------------------------------------------------
cp -f ${CLIENT}/spice/cloonix-spice-client-glib-usb-acl-helper ${CLIENT}
cp -rf ${CLIENT}/spice/polkit-1 ${CLIENT}
cp -f ${CLIENT}/spice/cloonix-spicy ${CLIENT}
rm -rf ${CLIENT}/spice
#----------------------------------------------------------
cp -f ${CLIENT}/cairo_canvas/cloonix-gui ${CLIENT}
rm -rf ${CLIENT}/cairo_canvas
#----------------------------------------------------------
cp -f ${CLIENT}/xwycli/cloonix-xwycli ${CLIENT}
rm -rf ${CLIENT}/xwycli
#----------------------------------------------------------
cp -f ${CLIENT}/rxvt/urxvt ${CLIENT}/cloonix-urxvt
rm -rf ${CLIENT}/rxvt
#----------------------------------------------------------
cp -f ${CLIENT}/ctrl/cloonix-ctrl ${CLIENT}
rm -rf ${CLIENT}/ctrl
#----------------------------------------------------------
cp -f ${CLIENT}/openssh/cloonix-u2i-scp ${CLIENT}
cp -f ${CLIENT}/openssh/cloonix-u2i-ssh ${CLIENT}
rm -rf ${CLIENT}/openssh
#----------------------------------------------------------
cp -f /usr/bin/tilix ${CLIENT}/cloonix-tilix
cp -f /bin/bash ${CLIENT}
#----------------------------------------------------------
for i in "awk" "cat" "chmod" "chown" "cp" "echo" "ps" \
         "env" "grep" "id" "kill" "ldd" "strace" \
         "locale" "localedef" "localectl" "xauth" ; do
  cp -f /usr/bin/${i} ${CLIENT}
done
#----------------------------------------------------------
for i in "ip" "ifconfig" "locale-gen" ; do
  cp -f /usr/sbin/${i} ${CLIENT}
done
#----------------------------------------------------------
cd ${CLIENT}
sed -i s"%/bin/sh%/usr/libexec/cloonix/client/bash%" locale-gen
sed -i s"%localedef%/usr/libexec/cloonix/client/localedef%" locale-gen
sed -i s'%LOCALEGEN=\(.*\)%LOCALEGEN=/usr/libexec/cloonix/common/etc/locale.gen%' locale-gen
#----------------------------------------------------------
if [ "${ARCH}" = "i386" ]; then
  LDLINUX="/usr/libexec/cloonix/common/lib32/ld-linux.so.2"
  RPATH_LIB="/usr/libexec/cloonix/common/lib:/usr/libexec/cloonix/common/lib/i386-linux-gnu"
else
  LDLINUX="/usr/libexec/cloonix/common/lib64/ld-linux-x86-64.so.2"
  RPATH_LIB="/usr/libexec/cloonix/common/lib:/usr/libexec/cloonix/common/lib/x86_64-linux-gnu"
fi
for i in `find ${CLIENT} -maxdepth 1 -type f` ; do
  ${PATCHELF} --force-rpath --set-rpath ${RPATH_LIB} ${i} 2>/dev/null
  ${PATCHELF} --set-interpreter ${LDLINUX} ${i} 2>/dev/null
done
#----------------------------------------------------------
cd ${CLOONIX_TREE_ROOT}/build_tools
gcc -o copy_libs fill_common.c
./copy_libs ${CLIENT} client
rm ./copy_libs
rm -rf ${TMPBUILD}
#----------------------------------------------------------
