#!/bin/bash
#----------------------------------------------------------------------------#
WITH_FRR="__WITH_FRR__"
#----------------------------------------------------------------------------#
set -e
FROM_HERE=`pwd`
BUNDLE="/root/cloonix_bundle"
ROOTFS="${BUNDLE}/cloonfs"
PATCHELF="${ROOTFS}/bin/patchelf"
#----------------------------------------------------------------------------#
if [ ! -e ${BUNDLE}/cloonix/cloonix_config ]; then
  echo NOT FOUND:
  echo ${BUNDLE}/cloonix/cloonix_config
  exit 1   
fi  
#----------------------------------------------------------------------------#
#----------------------------------------------------------------------------#
printf "\n\nPACKING ${pretty_name} ${ROOTFS}\n\n"
#----------------------------------------------------------------------------#
for i in  "cloonix_net" \
          "cloonix_cli" \
          "cloonix_gui" \
          "cloonix_ocp" \
          "cloonix_osh" \
          "cloonix_shk" \
          "cloonix_shc" \
          "cloonix_ovs" \
          "cloonix_scp" \
          "cloonix_ssh" \
          "cloonix_dsh" \
          "cloonix_lsh" \
          "cloonix_ice" \
          "cloonix_wsk" ; do
  cp -f ${BUNDLE}/cloonix/${i} ${ROOTFS}/bin
done
#----------------------------------------------------------------------------#
cp -f  ${BUNDLE}/cloonix/client/hide_dirs/cloonix-hide-dirs ${ROOTFS}/bin
cp -f  ${BUNDLE}/cloonix/client/agent_dropbear/cloonix-dropbear-scp ${ROOTFS}/bin
cp -f  ${BUNDLE}/cloonix/client/agent_dropbear/cloonix-dropbear-ssh ${ROOTFS}/bin
cp -f  ${BUNDLE}/cloonix/client/cairo_canvas/cloonix-gui ${ROOTFS}/bin
cp -f  ${BUNDLE}/cloonix/client/xwycli/cloonix-xwycli ${ROOTFS}/bin
cp -f  ${BUNDLE}/cloonix/client/rxvt/urxvt ${ROOTFS}/bin/cloonix-urxvt
cp -f  ${BUNDLE}/cloonix/client/ctrl/cloonix-ctrl ${ROOTFS}/bin
cp -f  ${BUNDLE}/cloonix/server/dtach/cloonix-dtach ${ROOTFS}/bin
cp -f  ${BUNDLE}/cloonix/server/apk_tools/cloonix-apk-static ${ROOTFS}/bin
cp -f  ${BUNDLE}/cloonix/server/ovs/cloonix-vswitch.ovsschema ${ROOTFS}/bin/ovsschema
cp -f -r ${BUNDLE}/cloonix/server/insider_agents ${BUNDLE}
if [ "${WITH_FRR}" = "yes" ]; then
  BUILD_FRR=${BUNDLE}/cloonix/server/frr/built_frr
  mv ${BUILD_FRR}/etc/frr ${ROOTFS}/etc
  mv ${BUILD_FRR}/bin/*  ${ROOTFS}/bin
  mv ${BUILD_FRR}/sbin/*  ${ROOTFS}/sbin
  mv ${BUILD_FRR}/lib/*  ${ROOTFS}/lib
  mv ${BUILD_FRR}/share/yang  ${ROOTFS}/share
  rm -rf ${BUILD_FRR}
fi
cp -f  ${BUNDLE}/cloonix/server/xwy/cloonix-xwy-srv ${ROOTFS}/bin
cp -f  ${BUNDLE}/cloonix/server/wm2/cloonix-novnc-wm2 ${ROOTFS}/bin
cp -f  ${BUNDLE}/cloonix/server/suid_power/cloonix-suid-power ${ROOTFS}/bin
cp -f  ${BUNDLE}/cloonix/server/doorways/cloonix-doorways ${ROOTFS}/bin
cp -f  ${BUNDLE}/cloonix/server/suid_power/cloonix-suid-power ${ROOTFS}/bin
cp -f  ${BUNDLE}/cloonix/server/uml_cloonix_switch/cloonix-main-server ${ROOTFS}/bin
for i in cloonix-ovsdb-server \
         cloonix-ovs-vswitchd \
         cloonix-ovsdb-tool \
         cloonix-ovs-appctl \
         cloonix-ovs-vsctl ; do
  cp -f ${BUNDLE}/cloonix/server/ovs/bin/${i} ${ROOTFS}/bin
done
cp -f  ${BUNDLE}/cloonix/server/nginx/bin/cloonix-novnc-nginx ${ROOTFS}/bin
cp -f  ${BUNDLE}/cloonix/server/websockify-js/bin/cloonix-novnc-websockify-js ${ROOTFS}/bin
cp -f  ${BUNDLE}/cloonix/server/ovs_c2c/cloonix-ovs-c2c ${ROOTFS}/bin
cp -f  ${BUNDLE}/cloonix/server/ovs_a2b/cloonix-ovs-a2b ${ROOTFS}/bin
cp -f  ${BUNDLE}/cloonix/server/ovs_drv/cloonix-ovs-drv ${ROOTFS}/bin
cp -f  ${BUNDLE}/cloonix/server/ovs_nat_main/cloonix-ovs-nat-main ${ROOTFS}/bin
cp -f  ${BUNDLE}/cloonix/server/ovs_snf/cloonix-ovs-snf ${ROOTFS}/bin
cp -f  ${BUNDLE}/cloonix/server/proxymous/cloonix-proxymous ${ROOTFS}/bin
cp -f  ${BUNDLE}/cloonix/server/iproute2/ip ${ROOTFS}/bin
cp -f  ${BUNDLE}/cloonix/server/crun/crun_tainted/crun ${ROOTFS}/bin/cloonix-crun
cp -f  ${BUNDLE}/cloonix/server/xorg/Xvfb ${ROOTFS}/bin/cloonix-novnc-Xvfb
cp -f  ${BUNDLE}/cloonix/server/xorg/Xephyr ${ROOTFS}/bin/cloonix-novnc-xephyr
cp -f  ${BUNDLE}/cloonix/server/wireshark/wireshark ${ROOTFS}/bin/cloonix-wireshark
cp -f  ${BUNDLE}/cloonix/server/wireshark/dumpcap ${ROOTFS}/bin/cloonix-dumpcap
#----------------------------------------------------------------------------#
cp -f ${BUNDLE}/cloonix/cloonix_config ${ROOTFS}/etc/cloonix.cfg
#----------------------------------------------------------------------------#
cp -rf ${BUNDLE}/cloonix/client/spice/polkit-1 ${ROOTFS}/bin
cp -f ${BUNDLE}/cloonix/client/spice/cloonix-spice-client-glib-usb-acl-helper ${ROOTFS}/bin
cp -f ${BUNDLE}/cloonix/client/spice/cloonix-spicy ${ROOTFS}/bin
cp -f ${BUNDLE}/cloonix/client/openssh/cloonix-u2i-scp ${ROOTFS}/bin
cp -f ${BUNDLE}/cloonix/client/openssh/cloonix-u2i-ssh ${ROOTFS}/bin
cp -rf ${BUNDLE}/cloonix/server/qemu ${ROOTFS}/bin
rm -rf ${ROOTFS}/bin/qemu/tainted_qemu
for i in "allclean" "cloonix-qemu-img" "cloonix-qemu-system" \
         "cloonix_patch" "cmd" "mkpatch" "patched_create" ; do
  rm -f ${ROOTFS}/bin/qemu/${i}
done
cp -f ${BUNDLE}/cloonix/server/qemu/cloonix-qemu-system ${ROOTFS}/bin
cp -f ${BUNDLE}/cloonix/server/qemu/cloonix-qemu-img ${ROOTFS}/bin
#----------------------------------------------------------------------------#
printf "\n\nGET ALL LIBRARIES ${ROOTFS}\n\n"
#----------------------------------------------------------------------------#
cd ${BUNDLE}
./copy_libs ${ROOTFS}
#----------------------------------------------------------------------------#
printf "\n\nPATCHELF ${ROOTFS}\n\n"
#----------------------------------------------------------------------------#
LDLINUX="/usr/libexec/cloonix/cloonfs/lib64/ld-linux-x86-64.so.2"
RPATH_LIB="/usr/libexec/cloonix/cloonfs/lib"
RPATH_LIB="${RPATH_LIB}:/usr/libexec/cloonix/cloonfs/lib/x86_64-linux-gnu"
set +e
for j in "bin" \
         "sbin" \
         "lib" \
         "lib/frr" \
         "lib/frr/modules" \
         "lib/systemd" \
         "lib/x86_64-linux-gnu" \
         "lib/x86_64-linux-gnu/rsyslog" \
         "lib/x86_64-linux-gnu/systemd" \
         "lib/x86_64-linux-gnu/qt6/plugins/platforms" \
         "lib/x86_64-linux-gnu/gconv" \
         "lib/x86_64-linux-gnu/gstreamer-1.0" \
         "lib/x86_64-linux-gnu/gstreamer1.0" \
         "lib/x86_64-linux-gnu/gstreamer1.0/gstreamer-1.0" \
         "lib/x86_64-linux-gnu/pipewire-0.3" ; do 

  if [ -e ${ROOTFS}/${j} ]; then
    for i in `find ${ROOTFS}/${j} -maxdepth 1 -type f` ; do
      ${PATCHELF} --force-rpath --set-rpath ${RPATH_LIB} ${i} 2>/dev/null
      ${PATCHELF} --set-interpreter ${LDLINUX} ${i} 2>/dev/null
    done
  fi
done
#----------------------------------------------------------------------------#
mkdir -p ${BUNDLE}/startup_bin
for i in "bash" "sleep" "mkdir" "xauth" "cat" \
         "ln" "mount" "echo" "rm" ; do
  cp -f ${ROOTFS}/bin/${i} ${BUNDLE}/startup_bin
done     
#----------------------------------------------------------------------------#
echo PACK DONE OK TO END
#----------------------------------------------------------------------------#

