#!/bin/bash
if [ ! -n "${CLOONIX_TREE_ROOT}" ]; then
  echo PLEASE DEFINE CLOONIX_TREE_ROOT
  exit 1
fi
if [ ! -e ${CLOONIX_TREE_ROOT}/cloonix/cloonix_config ]; then
  echo NOT FOUND:
  echo ${CLOONIX_TREE_ROOT}/cloonix/cloonix_config
  exit 1
fi
TARGZ_STORE=${CLOONIX_TREE_ROOT}/targz_store
COMMON="${CLOONIX_TREE_ROOT}/build_tools/common"
pretty_name=$(cat /etc/os-release |grep PRETTY_NAME)
pretty_name=${pretty_name#*\"}
pretty_name=${pretty_name%% *}
case "$pretty_name" in
  "Debian")
  ;;
  *)
  printf "\n\tERROR: Your distribution: $pretty_name is not supported"
  exit
  ;;
esac
mkdir -p ${COMMON}/lib64
mkdir -p ${COMMON}/lib
mkdir -p ${COMMON}/etc
mkdir -p ${COMMON}/share/locale
mkdir -p ${COMMON}/share/i18n/charmaps
mkdir -p ${COMMON}/share/i18n/locales
mkdir -p ${COMMON}/share/X11/locale
#----------------------------------------------------------
FROM_HERE=`pwd`
tar --directory=/tmp -xf ${TARGZ_STORE}/patchelf_*.tar.gz
cd /tmp/patchelf
make
cd $FROM_HERE
#----------------------------------------------------------
cp -Lrf /etc/fonts ${COMMON}/etc
rm -f ${COMMON}/etc/fonts/fonts.conf
cat > ${COMMON}/etc/fonts/fonts.conf << EOF
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
    <dir>/usr/libexec/cloonix/common/share</dir>
</fontconfig>
EOF
cat > ${COMMON}/etc/locale.gen << EOF
en_US.UTF-8 UTF-8
EOF
cat > ${COMMON}/etc/locale.conf << EOF
LANG=en_US.UTF-8
EOF
#----------------------------------------------------------
cp -f /usr/bin/xauth ${COMMON}/cloonix-xauth
cp -f /bin/busybox ${COMMON}
cp -f /usr/bin/locale ${COMMON}
cp -f /usr/bin/localedef ${COMMON}
cp -f /usr/bin/localectl ${COMMON}
cp -f /usr/sbin/locale-gen ${COMMON}
cp -f /usr/lib/locale/locale-archive ${COMMON}
cd ${COMMON}
for i in cat cp echo env grep id ifconfig ip \
         iproute kill ls mv ps rm sh su chmod \
         chown awk; do 
  ln -s busybox ${i}
done
cd $FROM_HERE
for i in icons mime themes fonts gtk-3.0 \
         gstreamer-1.0 ; do
   cp -Lrf /usr/share/${i} ${COMMON}/share
done
cp -Lrf /usr/share/locale/en ${COMMON}/share/locale
cp -Lrf /usr/share/X11/locale/en_US.UTF-8 ${COMMON}/share/X11/locale
cp -Lrf /usr/share/X11/locale/C ${COMMON}/share/X11/locale
cp -Lrf /usr/share/X11/locale/locale.dir ${COMMON}/share/X11/locale
#----------------------------------------------------------
tar --directory=${COMMON}/share -xf ${TARGZ_STORE}/shark/built_objects/share_wireshark.tar.gz
mv ${COMMON}/share/share_wireshark ${COMMON}/share/wireshark
#----------------------------------------------------------
cp -f /lib64/ld-linux-x86-64.so.2 ${COMMON}/lib64
cp -f ${CLOONIX_TREE_ROOT}/cloonix/cloonix_config ${COMMON}/etc/cloonix.cfg
cp -f ${CLOONIX_TREE_ROOT}/cloonix/cloonix_osh ${COMMON}
cp -f ${CLOONIX_TREE_ROOT}/cloonix/cloonix_cli ${COMMON}
cp -f ${CLOONIX_TREE_ROOT}/cloonix/crun_init_user.sh ${COMMON}/etc
cp -f ${CLOONIX_TREE_ROOT}/cloonix/podman_init_user.sh ${COMMON}/etc
#----------------------------------------------------------
for i in qt6 gdk-pixbuf-2.0 gtk-3.0 gstreamer-1.0 ; do
  cp -rf /usr/lib/x86_64-linux-gnu/${i} ${COMMON}/lib
done
cp /usr/lib/x86_64-linux-gnu/gstreamer1.0/gstreamer-1.0/gst-plugin-scanner ${COMMON}
#----------------------------------------------------------
