#!/bin/bash
HERE=`pwd`
DISTRO=bookworm
NET=nemo
NAME=dev
QCOW2=builder.qcow2
BULK="/var/lib/cloonix/bulk"
REPO="http://172.17.0.2/debian/bookworm"
#----------------------------------------------------------------------
cloonix_net ${NET}
#----------------------------------------------------------------------
echo cp -f ${BULK}/${DISTRO}.qcow2 ${BULK}/${QCOW2}
cp -f ${BULK}/${DISTRO}.qcow2 ${BULK}/${QCOW2}
#----------------------------------------------------------------------
sync
#----------------------------------------------------------------------
cloonix_gui ${NET}
cloonix_cli ${NET} add nat nat
#----------------------------------------------------------------------
PARAMS="ram=8000 cpu=4 eth=s"
cloonix_cli ${NET} add kvm ${NAME} ${PARAMS} ${QCOW2} --persistent
#----------------------------------------------------------------------
sleep 3
cloonix_cli ${NET} add lan ${NAME} 0 lan1
cloonix_cli ${NET} add lan nat 0 lan1
#----------------------------------------------------------------------
set +e
while ! cloonix_ssh ${NET} ${NAME} "echo" 2>/dev/null; do
  echo ${NAME} not ready, waiting 5 sec
  sleep 5
done
#----------------------------------------------------------------------
cloonix_ssh ${NET} ${NAME} "dhclient eth0"
#----------------------------------------------------------------------
cloonix_ssh ${NET} ${NAME} "cat > /etc/apt/sources.list << EOF
deb ${REPO} ${DISTRO} main contrib non-free
EOF"
#----------------------------------------------------------------------
cloonix_ssh ${NET} ${NAME} "apt-get --assume-yes update"

cloonix_ssh ${NET} ${NAME} "apt-get -y install tar build-essential \
                            pkg-config intltool libtool meson ninja-build \
                            libssl-dev libusb-1.0-0-dev patch libglib2.0-dev \
                            libpixman-1-dev python3-six sudo xauth \
                            python3-pyparsing libjpeg-dev libgstreamer1.0-dev \
                            libgstreamer-plugins-base1.0-dev liblz4-dev \
                            libpcap-dev libsasl2-dev libfuse3-dev \
                            fuse-overlayfs libnuma-dev libepoxy-dev xorriso \
                            libgtk-3-dev libjson-glib-dev libacl1-dev \
                            libpolkit-gobject-1-dev cmake patchelf \
                            libyajl-dev make git libsystemd-dev \
                            libprotobuf-c-dev libcap-dev libseccomp-dev \
                            libgcrypt20-dev go-md2man python3 python3-venv"

#----------------------------------------------------------------------
cloonix_ssh ${NET} ${NAME} "sync"
cloonix_ssh ${NET} ${NAME} "poweroff"
#----------------------------------------------------------------------


