#!/bin/bash
HERE=`pwd`
DPDK=../dpdk
CLOONIX_COMMON=../../common
NINJA=${HERE}/${CLOONIX_COMMON}/meson_ninja
IO_CLOWNIX=${CLOONIX_COMMON}/lib_io_clownix
GLOB_INCLUDE=${CLOONIX_COMMON}/glob_include
RPC_CLOWNIX=${CLOONIX_COMMON}/lib_rpc_clownix/
BLKD=${CLOONIX_COMMON}/lib_blkd
RPCT=${CLOONIX_COMMON}/lib_rpct



./allclean

if [ ! -f ${IO_CLOWNIX}/libio_clownix.a ]; then
  cd ${IO_CLOWNIX}
  make
fi
if [ ! -f ${RPC_CLOWNIX}/librpc_clownix.a ]; then
  cd ${RPC_CLOWNIX}
  ./cmd
fi
if [ ! -f ${BLKD}/libblkd.a ]; then
  cd ${BLKD}
  make
fi
if [ ! -f ${RPCT}/librpct.a ]; then
  cd ${RPCT}
  make
fi
if [ ! -f ${NINJA}/ninja/ninja ]; then
  cd ${NINJA}
  ./cmd
  cd ${HERE}
fi
if [ ! -f ${DPDK}/bin/dpdk-testpmd ]; then
  cd ${DPDK}
  ./cmd
  cd ${HERE}
fi

export PKG_CONFIG_PATH=${HERE}/${DPDK}/lib/pkgconfig
export PATH=${NINJA}/ninja:${NINJA}/meson:$PATH

cat > meson.build << EOF
project('cloonix_nat_dpdk', 'c')

incdir = include_directories('${DPDK}/include',
                             '${IO_CLOWNIX}/include',
                             '${RPC_CLOWNIX}/include',
                             '${GLOB_INCLUDE}')

cmplr = meson.get_compiler('c')
io_clownix = cmplr.find_library('libio_clownix', dirs : '${HERE}/${IO_CLOWNIX}')
blkd = cmplr.find_library('libblkd', dirs : '${HERE}/${BLKD}')
rpct = cmplr.find_library('librpct', dirs : '${HERE}/${RPCT}')
dpdk = dependency('libdpdk')
crypto = dependency('libcrypto')

cflags = '-fPIC'

sources = files('src/nat_dpdk.c',
                'src/vhost_client.c',
                'src/rxtx.c',
                'src/udp.c',
                'src/machine.c',
                'src/dhcp.c',
                'src/icmp.c',
                'src/udp.c',
                'src/tcp.c',
                'src/tcp_llid.c',
                'src/tcp_flagseq.c',
                'src/tcp_qstore.c',
                'src/txq_dpdk.c',
                'src/rxq_dpdk.c',
                'src/utils.c',
                'src/stub.c')

executable('cloonix_nat_dpdk', sources, include_directories : incdir,
            dependencies : [io_clownix,blkd,rpct,dpdk,crypto],
            c_args: cflags,
            install_rpath : '/usr/local/bin/cloonix/server/dpdk/lib',
            install : true)

EOF

meson.py build
cd build
ninja
DESTDIR=${HERE} ninja install
cd ${HERE}
cp -vf usr/local/bin/cloonix_nat_dpdk ${DPDK}/bin
