#!/bin/bash
HERE=`pwd`

cd ${HERE}/../../../../common/lib_blkd
make clean
make

cd ${HERE}/../../../../common/lib_rpct
make clean
make

cd ${HERE}/../../../../common/lib_io_clownix
make clean
make

cd ${HERE}/..
make clean
make

cd $HERE
make clean
make


