#!/bin/bash
HERE=`pwd`
./allclean
./patched_create
cd ${HERE}/crun_tainted
./autogen.sh
./configure --without-shared --disable-shared --enable-static --disable-caps --disable-dl --disable-seccomp --disable-systemd --disable-bpf --disable-lua-path-guessing --enable-embedded-yajl
make
