#!/bin/bash
HERE=`pwd`
./allclean
./patched_create
cd ${HERE}/crun_tainted
./autogen.sh
./configure --without-shared \
            --disable-shared \
            --enable-static \
            --disable-systemd \
            --disable-lua-path-guessing \
            --enable-embedded-yajl
make
strip ${HERE}/crun_tainted/crun
