#!/bin/bash
set -e
HERE=`pwd`
TARGZ=${HERE}/../../../targz_store
TARGET=${HERE}/.
#----------------------------------------------------------
cd ${TARGET}
rm -rf ${TARGET}/spice-protocol
tar xvf ${TARGZ}/spice-protocol_*.tar.gz
cd spice-protocol
rm -rf build
meson --prefix=${TARGET} --datadir=${TARGET} \
      --libdir=${TARGET} --includedir=${TARGET} build
cd build
ninja
ninja install
#----------------------------------------------------------
cd ${TARGET}
rm -rf ${TARGET}/usbredir
tar xvf ${TARGZ}/usbredir_*.tar.gz
cd usbredir
rm -rf build
sed -i s"/subdir('tests')/#subdir('tests')/" meson.build 
meson  --prefix=${TARGET} --datadir=${TARGET} \
       --libdir=${TARGET} --includedir=${TARGET} build
cd build
ninja
ninja install
#----------------------------------------------------------
cd ${TARGET}
rm -rf ${TARGET}/spice
tar xvf ${TARGZ}/spice_*.tar.gz
cd ${TARGET}/spice
sed -i s"/UNKNOWN/0.12.5/" build-aux/git-version-gen
sed -i 52s"/true/false/" meson_options.txt
sed -i s"/^run_command/#run_command/" meson.build
export PKG_CONFIG_PATH=${TARGET}/pkgconfig
meson --prefix=${TARGET} --datadir=${TARGET} \
      --libdir=${TARGET} --includedir=${TARGET} build
cd build
ninja
ninja install
#----------------------------------------------------------
cd ${HERE}
CMD="exec_prefix=/usr/local/bin/cloonix/common/spice_lib"
sed -i s"%exec_prefix=\(.*\)%${CMD}%" pkgconfig/libusbredirhost.pc
sed -i s"%exec_prefix=\(.*\)%${CMD}%" pkgconfig/libusbredirparser-0.5.pc
sed -i s"%Name:%${CMD}\nName:%" pkgconfig/spice-server.pc
sed -i s"%Name:%${CMD}\nName:%" pkgconfig/spice-protocol.pc
#----------------------------------------------------------

