#!/bin/bash
HERE=`pwd`
TARGZ=${HERE}/../../../targz_store
tar xvf ${TARGZ}/meson_*.tar.gz
tar xvf ${TARGZ}/ninja_*.tar.gz
cd ${HERE}/ninja
sed -i s"%/usr/bin/env python%/usr/bin/env python3%" configure.py
./configure.py --bootstrap
exit 0
