#!/bin/bash
HERE=`pwd`

cd ${HERE}/../../../common/lib_blkd
make clean
make 
cd ${HERE}/../../../common/lib_rpct
make clean
make 
cd ${HERE}/../lib_ioc
make clean
make 

if [ ! -d ../../../../tmpbuild/cloonix/server/dpdk/dpdk-19.02 ]; then
  if [ ! -d ../../dpdk/dpdk-19.02 ]; then
    cd ${HERE}/../../dpdk
    ./dpdk.sh
  fi
fi

cd ${HERE}
make clean
make 

