#!/bin/bash

# See quickstart/tools/arch_install.sh for the initial arch creation
# Download Arch-Linux-x86_64-basic-20230701.161647.qcow2
# pacman -S qemu-guest-agent
# poweroff

HERE=`pwd`
NET=nemo
DISTRO=arch
NAME=${DISTRO}
QCOW2=${DISTRO}.qcow2
INITIAL="Arch-Linux-x86_64-basic-20230701.161647.qcow2"
#----------------------------------------------------------------------
BULK="/var/lib/cloonix/bulk"
if [ ! -e ${BULK}/${INITIAL} ]; then
  echo
  echo ${BULK}/${INITIAL}
  echo
  exit 1
fi
#----------------------------------------------------------------------
is_started=$(cloonix_cli $NET pid |grep cloonix_server)
if [ "x$is_started" == "x" ]; then
  printf "\nServer Not started, launching:"
  printf "\ncloonix_net $NET:\n"
  cloonix_net $NET
  echo waiting 2 sec
  sleep 2
else
  cloonix_cli $NET rma
  echo waiting 10 sec
  sleep 10
fi
#----------------------------------------------------------------------
cp -f ${BULK}/${INITIAL} ${BULK}/${QCOW2}
sync
sleep 2
sync
#----------------------------------------------------------------------
cloonix_gui $NET
#----------------------------------------------------------------------
#----------------------------------------------------------------------
PARAMS="ram=8000 cpu=4 eth=s"
cloonix_cli $NET add kvm $NAME $PARAMS $QCOW2 --persistent --no_qemu_ga --natplug=0
#----------------------------------------------------------------------





