#!/bin/bash
set -e
DISTRO=opensuse155
DISTRONUM=15.5
ROOTFS=/var/lib/cloonix/bulk/${DISTRO}
OPENSUSE_MIRROR=http://download.opensuse.org

OPENSUSE=${OPENSUSE_MIRROR}/distribution/leap/${DISTRONUM}/repo/oss
OPENSUSE_UPDATES=${OPENSUSE_MIRROR}/update/leap/${DISTRONUM}/oss
#----------------------------------------------------------------------#
fct_check_uid()
{
  if [ $UID != 0 ]; then
    echo you must be root
    exit -1
  fi
}
#----------------------------------------------------------------------#
fct_check_losetup()
{
  modprobe loop
  if [[ "$(losetup -a )" != "" ]]; then
    echo
    echo
    echo losetup -a should give nothing, it gives:
    losetup -a
    echo
    exit -1
  fi
}
#----------------------------------------------------------------------#
fct_create_32G_mount_wkmntloops()
{
  truncate --size 32G ${ROOTFS}
  sgdisk --clear \
         --new 1::+1M --typecode=1:ef02 --change-name=1:'BIOS' \
         --new 2::-0 --typecode=2:8300 --change-name=2:'Linux' \
         ${ROOTFS}
  losetup /dev/loop0 ${ROOTFS}
  partprobe /dev/loop0
  mkfs.ext4 -F -L "cloonix" /dev/loop0p2
  mkdir -p /tmp/wkmntloops
  mount /dev/loop0p2 /tmp/wkmntloops
}
#----------------------------------------------------------------------#

#########################################################################
fct_check_uid
set +e
for i in qemu-img rpm blkid wget sgdisk partprobe zypper; do
  path_bin=$(which $i)
  if [ -z $path_bin ]; then
    echo $i  DOES NOT EXIST
    exit -1
  fi
done

if [ -e $ROOTFS ]; then
  echo $ROOTFS already exists
  exit 1
fi

fct_check_losetup
set -e
fct_create_32G_mount_wkmntloops $ROOTFS
#-----------------------------------------------------------------------#
set +e
for i in ${OPENSUSE} ${OPENSUSE_UPDATES};
do
  wget --no-check-certificate --delete-after ${i} 1>/dev/null 2>&1
  OK=$?
  if [ "$OK" != "0" ]; then
    echo ERROR wget ${i}
    exit 1
  fi
  echo
  echo REPO OK ${i}
  echo
done


zypper --root=/tmp/wkmntloops --non-interactive --no-gpg-checks --gpg-auto-import-keys addrepo ${OPENSUSE} ${DISTRONUM}-oss
zypper --root=/tmp/wkmntloops --non-interactive --no-gpg-checks --gpg-auto-import-keys addrepo ${OPENSUSE_UPDATES} ${DISTRONUM}-oss-updates
zypper --root=/tmp/wkmntloops --non-interactive --no-gpg-checks --gpg-auto-import-keys refresh
zypper --root=/tmp/wkmntloops --non-interactive --no-gpg-checks --gpg-auto-import-keys update --force-resolution
zypper --root=/tmp/wkmntloops --non-interactive --no-gpg-checks --gpg-auto-import-keys install systemd
zypper --root=/tmp/wkmntloops --non-interactive --no-gpg-checks --gpg-auto-import-keys install zypper

#-----------------------------------------------------------------------#
rm -f /tmp/wkmntloops/etc/resolv.conf
cp -f /etc/resolv.conf "/tmp/wkmntloops/etc"
#-----------------------------------------------------------------------#
for d in dev sys proc; do
  mkdir -p /tmp/wkmntloops/$d
  mount --bind /$d /tmp/wkmntloops/$d
done

chroot /tmp/wkmntloops/ zypper --non-interactive --no-gpg-checks --gpg-auto-import-keys refresh
chroot /tmp/wkmntloops/ zypper --non-interactive --no-gpg-checks --gpg-auto-import-keys update --force-resolution
chroot /tmp/wkmntloops/ zypper --non-interactive --no-gpg-checks --gpg-auto-import-keys dist-upgrade --allow-vendor-change

chroot /tmp/wkmntloops/ zypper --non-interactive --no-gpg-checks --gpg-auto-import-keys refresh
chroot /tmp/wkmntloops/ zypper --non-interactive --no-gpg-checks --gpg-auto-import-keys update --force-resolution
chroot /tmp/wkmntloops/ zypper --non-interactive --no-gpg-checks --gpg-auto-import-keys dist-upgrade --allow-vendor-change

#-----------------------------------------------------------------------#
list_pkt="kernel-default-extra "
list_pkt+="grub2-i386-pc dracut dracut-extra ignition-dracut-grub2 grub2 grubby "
list_pkt+="dhcp-client iproute2 openssh xauth sudo kbd vim net-tools "
list_pkt+="curl mdadm biosdevname tar qemu-guest-agent"
#-----------------------------------------------------------------------#
chroot /tmp/wkmntloops/ zypper --non-interactive --force-resolution install $list_pkt
chroot /tmp/wkmntloops/ zypper --non-interactive --force-resolution install -t pattern base
chroot /tmp/wkmntloops/ grub2-install --no-floppy --modules=part_gpt --target=i386-pc /dev/loop0
#-----------------------------------------------------------------------#
KERN="console=ttyS0 console=tty1 earlyprintk=serial net.ifnames=0 ipv6.disable=1"
printf "\nGRUB_CMDLINE_LINUX_DEFAULT=\"%s\"\n" "$KERN" \
        > /tmp/wkmntloops/etc/default/grub

version=$(ls /tmp/wkmntloops/lib/modules/ | grep default)
if [ ! -e /tmp/wkmntloops/boot/vmlinuz-${version} ]; then
  echo ERROR:
  ls /tmp/wkmntloops/lib/modules/
  ls /tmp/wkmntloops/boot/
  umount /tmp/wkmntloops/{dev,proc,sys}
  umount /tmp/wkmntloops
  losetup -d /dev/loop0
  exit 1
fi
echo $version
chroot /tmp/wkmntloops/ zstd -d /lib/modules/${version}/kernel/drivers/scsi/virtio_scsi.ko.zst
chroot /tmp/wkmntloops/ zstd -d /lib/modules/${version}/kernel/drivers/scsi/sd_mod.ko.zst 
list="sd_mod virtio_scsi"
chroot /tmp/wkmntloops/ dracut --add-drivers "${list}" --force /boot/initrd-${version} $version
chroot /tmp/wkmntloops/ grub2-mkconfig -o /boot/grub2/grub.cfg
uuid=$(blkid | grep cloonix)
uuid=${uuid#*UUID=\"}
uuid=${uuid%%\"*}
echo $uuid


#-----------------------------------------------------------------------#
cat > /tmp/wkmntloops/etc/fstab  << EOF
UUID=$uuid  /            ext4     defaults                      0 0 
proc        /proc        proc     nosuid,noexec,nodev           0 0
sysfs       /sys         sysfs    nosuid,noexec,nodev           0 0
devpts      /dev/pts     devpts   nosuid,noexec,gid=5,mode=620  0 0
tmpfs       /run         tmpfs    defaults                      0 0
devtmpfs    /dev         devtmpfs mode=0755,nosuid              0 0
EOF
#-----------------------------------------------------------------------#
cat > /tmp/wkmntloops/etc/sysconfig/network/ifcfg-eth0 << EOF
BOOTPROTO='dhcp'
BROADCAST=''
ETHTOOL_OPTIONS=''
IPADDR=''
MTU=''
NAME=''
NETMASK=''
NETWORK=''
REMOTE_IPADDR=''
STARTMODE='auto'
DHCLIENT_SET_DEFAULT_ROUTE='yes'
ZONE=public
PREFIXLEN='24'
EOF
#-----------------------------------------------------------------------#
chroot /tmp/wkmntloops/ passwd root <<EOF
root
root
EOF
#-----------------------------------------------------------------------#
sync /dev/loop0
sleep 2
umount /tmp/wkmntloops/{dev,proc,sys}
umount /tmp/wkmntloops
losetup -d /dev/loop0
#-----------------------------------------------------------------------#
qemu-img convert -O qcow2 $ROOTFS ${ROOTFS}.qcow2
rm -f $ROOTFS
#-----------------------------------------------------------------------#

