#!/bin/bash
#----------------------------------------------------------------------------
exec &> /tmp/cloonix_sbin_init_shared.log
echo "STARTING cloonixsbininitshared"
#-----------------------------------------------------------------
cat > /etc/rsyslog.conf << "EOF"
module(load="imuxsock") 
$FileOwner root
$FileGroup root
$FileCreateMode 0640
$DirCreateMode 0755
$Umask 0022
$WorkDirectory /var/spool/rsyslog
*.*;auth,authpriv.none          -/var/log/syslog
EOF
mkdir -p /var/spool/rsyslog
echo "/etc/rsyslog.conf done"
#----------------------------------------------------------------------
cat > /etc/locale.gen << "EOF"
en_US.UTF-8 UTF-8
EOF
#----------------------------------------------------------------------
cat > /etc/locale.conf << "EOF"
LANG=C
EOF
#----------------------------------------------------------------------
cat > /etc/hosts << "EOF"
127.0.0.1   localhost
EOF
#-----------------------------------------------------------------------
cat > /etc/passwd << "EOF"
root:x:0:0:root:/root:/bin/bash
nobody:x:65534:65534:nobody:/nonexistent:/usr/sbin/nologin
frr:x:0:0:Frr routing suite,,,:/nonexistent:/bin/nologin
EOF
#----------------------------------------------------------------------
cat > /etc/group << "EOF"
root:x:0:
nogroup:x:65534:
frrvty:x:0:frr
frr:x:0:
EOF
#----------------------------------------------------------------------
mkdir -p /etc/frr
#----------------------------------------------------------------------
cat > /etc/frr/support_bundle_commands.conf << "EOF"
PROC_NAME:zebra
CMD_LIST_START
PROC_NAME:ospf
CMD_LIST_START
EOF
#----------------------------------------------------------------------
cat > /etc/frr/vtysh.conf << "EOF"
service integrated-vtysh-config
EOF
#----------------------------------------------------------------------
cat > /etc/frr/daemons << "EOF"
ospfd=yes
vtysh_enable=yes
zebra_options="  -A 127.0.0.1 -s 90000000"
ospfd_options="  -A 127.0.0.1"
EOF
#----------------------------------------------------------------------
cat > /etc/frr/frr.conf << "EOF"
frr defaults traditional
log syslog debugging
router ospf
ospf router-id __NUM__.1.1.1
redistribute connected
redistribute static
EOF
#----------------------------------------------------------------------
mkdir -p /run/frr
mkdir -p /var/tmp/frr
mkdir -p /var/log/frr
mkdir -p /var/lib/frr
chmod 640 /etc/frr/*
#-----------------------------------------------------------------------
echo "LAUNCHING rsyslogd"
rsyslogd
logger rsyslogd LAUNCHED
echo "rsyslogd LAUNCHED"
#----------------------------------------------------------------------


