#!/bin/bash
set -e
HERE=`pwd`
DBASE=${HERE}/../..
NINJA=${DBASE}/common/meson_ninja
./allclean
if [ ! -f ${NINJA}/ninja/ninja ]; then
  echo Doing NINJA
  sleep 1
  cd ${NINJA}
  ./cmd
  cd ${HERE}
fi

if [ ! -f ${DBASE}/common/spice/spice_lib/pkgconfig/spice-protocol.pc ]; then
  echo Doing COMMON SPICE
  sleep 1
  cd ${DBASE}/common/spice
  ./cmd
  cd ${HERE}
fi

if [ ! -f ${DBASE}/common/spice/spice_lib/pkgconfig/spice-server.pc ]; then
  echo Doing SERVER SPICE
  sleep 1
  cd ${DBASE}/server/spice/
  ./cmd
  cd ${HERE}
fi


echo Doing LIBS
sleep 1

cd ${DBASE}/common/lib_rpct
make
cd ${HERE}


PKGCONFIG=${DBASE}/common/spice/spice_lib/pkgconfig
export PATH=${NINJA}/ninja:$PATH
export PKG_CONFIG_PATH=${PKGCONFIG}
export QEMU_CFLAGS="-fPIE -DPIE -I${DBASE}/common/spice/spice_lib/include \
                    -I${DBASE}/common/glob_include"
export QEMU_LDFLAGS="-pie -L${DBASE}/common/spice/spice_lib -lepoxy \
                     -Wl,-rpath,/usr/local/bin/cloonix/common/spice/spice_lib"

echo Doing untar and patch
sleep 1

./patched_create

cd ${HERE}/tainted_qemu/

 CONFIGURATION_OPTS="--prefix=/usr/local
                     --target-list=x86_64-softmmu
                     --python=/usr/bin/python3
                     --enable-fdt
                     --enable-kvm
                     --enable-spice
                     --enable-usb-redir
                     --enable-linux-user
                     --enable-coroutine-pool
                     --enable-opengl
                     --enable-gtk
                     --enable-numa
                     --enable-virglrenderer
                     --enable-vhost-net
                     --enable-vhost-kernel
                     --enable-vhost-user
                     --enable-pie
                     --enable-vhost-scsi
                     --enable-vhost-crypto
                     --enable-debug-info
                     --enable-debug
                     --enable-debug-mutex
                     --enable-linux-aio
                     --enable-curses
                     --disable-vte
                     --disable-lzo
                     --disable-snappy
                     --disable-bzip2
                     --disable-slirp
                     --disable-vhost-vsock
                     --disable-tcg
                     --disable-debug-tcg
                     --disable-virtfs
                     --disable-strip
                     --disable-modules
                     --disable-libiscsi
                     --disable-libusb
                     --disable-tcg-interpreter
                     --disable-bsd-user
                     --disable-docs
                     --disable-guest-agent
                     --disable-guest-agent-msi
                     --disable-sparse
                     --disable-gnutls
                     --disable-nettle
                     --disable-gcrypt
                     --disable-sdl
                     --disable-vnc
                     --disable-vnc-sasl
                     --disable-vnc-jpeg
                     --disable-vnc-png
                     --disable-cocoa
                     --disable-xen
                     --disable-xen-pci-passthrough
                     --disable-brlapi
                     --disable-curl
                     --disable-rdma
                     --disable-vde
                     --disable-netmap
                     --disable-cap-ng
                     --disable-attr
                     --disable-rbd
                     --disable-libnfs
                     --disable-smartcard
                     --disable-seccomp
                     --disable-glusterfs
                     --disable-tpm"


echo Doing CONFIGURE
sleep 1
./configure  $CONFIGURATION_OPTS

echo Doing QEMU
sleep 1
make clean
make -j 5

echo MOVING QEMU RESULT BIN
sleep 1

mv build/qemu-system-x86_64   ${HERE}
mv build/qemu-img             ${HERE}
cp pc-bios/bios-256k.bin      ${HERE}
cp pc-bios/kvmvapic.bin       ${HERE}
cp pc-bios/vgabios.bin        ${HERE}
cp pc-bios/vgabios-stdvga.bin ${HERE}
cp pc-bios/vgabios-qxl.bin    ${HERE}
cp pc-bios/vgabios-virtio.bin ${HERE}
cp pc-bios/efi-virtio.rom     ${HERE}
cp pc-bios/efi-e1000.rom      ${HERE}
cp pc-bios/efi-ne2k_pci.rom   ${HERE}
cp pc-bios/efi-rtl8139.rom    ${HERE}
cp pc-bios/efi-vmxnet3.rom    ${HERE}


