#!/bin/bash
set -e
HERE=`pwd`
#----------------------------------------------------------------------#
if [ ${#} = 1 ]; then
  if [ "$1" = "i386" ]; then
    ARCH="i386"
  else
    if [ "$1" = "amd64" ]; then
      ARCH="amd64"
    else
      echo ERROR $0 param must be i386, or amd64
      exit
    fi
  fi
else
  ARCH="amd64"
fi
#----------------------------------------------------------------------#

./allclean
./patched_create


if [ ! -d ${HERE}/../spice_lib_server/pkgconfig ]; then
  cd ${HERE}/../spice_lib_server
  ./cmd
  cd ${HERE}
fi

export PKG_CONFIG_PATH=${HERE}/../spice_lib_server/pkgconfig
export LDFLAGS="-L${HERE}/../spice_lib_server"

cd ${HERE}/tainted_qemu/

CONFIGURATION_OPTS="--prefix=/usr/local
                    --python=/usr/bin/python3
                    --enable-kvm
                    --enable-spice
                    --enable-spice-protocol
                    --enable-usb-redir
                    --enable-gtk
                    --enable-vhost-user
                    --enable-vhost-net
                    --enable-vhost-kernel
                    --enable-tools
                    --enable-pixman
                    --enable-linux-io-uring
                    --enable-linux-aio
                    --enable-gio
                    --without-default-features"

if [ "${ARCH}" = "i386" ]; then
  CONFIGURATION_OPTS="${CONFIGURATION_OPTS} --target-list=i386-softmmu"
else
  CONFIGURATION_OPTS="${CONFIGURATION_OPTS} --target-list=x86_64-softmmu"
fi


export CFLAGS="-mtune=generic -fno-stack-protector  -g"
export LDFLAGS="-L${HERE}/../spice_lib_server -lstdc++ "
echo Doing CONFIGURE
./configure  $CONFIGURATION_OPTS

echo Doing QEMU
make -j 6

echo MOVING QEMU RESULT BIN

if [ "${ARCH}" = "i386" ]; then
  mv build/qemu-system-i386   ${HERE}/cloonix-qemu-system
else
  mv build/qemu-system-x86_64   ${HERE}/cloonix-qemu-system
fi
mv build/qemu-img             ${HERE}/cloonix-qemu-img
cp pc-bios/bios-256k.bin      ${HERE}
cp pc-bios/efi-virtio.rom     ${HERE}
cp pc-bios/efi-e1000.rom      ${HERE}
cp pc-bios/kvmvapic.bin       ${HERE}
cp pc-bios/vgabios-virtio.bin ${HERE}
cp pc-bios/vgabios-qxl.bin    ${HERE}
cp pc-bios/vgabios-stdvga.bin ${HERE}

