#!/bin/bash
#----------------------------------------------------------------------#
MIRROR=https://mirrors.edge.kernel.org/centos/9-stream
#----------------------------------------------------------------------#
ROOTFS=/root/centos9.img
#----------------------------------------------------------------------#
fct_check_uid()
{
  if [ $UID != 0 ]; then
    echo you must be root
    exit -1
  fi
}
#----------------------------------------------------------------------#
fct_check_losetup()
{
  modprobe loop
  if [[ "$(losetup -a )" != "" ]]; then
    echo
    echo
    echo losetup -a should give nothing, it gives:
    losetup -a
    echo
    exit -1
  fi
}
#----------------------------------------------------------------------#

#########################################################################
fct_check_uid
set +e
if [ -e $ROOTFS ]; then
  echo $ROOTFS already exists
  exit 1
fi
fct_check_losetup
#-----------------------------------------------------------------------#
for i in ${MIRROR}/BaseOS/x86_64/os ${MIRROR}/AppStream/x86_64/os;
do
  wget --no-check-certificate --delete-after ${i} 1>/dev/null 2>&1
  OK=$?
  if [ "$OK" != "0" ]; then
    echo ERROR wget ${i}
    exit 1
  fi
  echo
  echo REPO OK ${i}
  echo
done

set -e
#-----------------------------------------------------------------------#
dd if=/dev/zero of=${ROOTFS} bs=500M count=10
mkfs.ext4 ${ROOTFS}
losetup -fP ${ROOTFS}
mkdir -p /tmp/wkmntloops
DEVLOOP=$(losetup -l | grep ${ROOTFS} | awk '{print $1}')
echo $DEVLOOP
mount -o loop $DEVLOOP /tmp/wkmntloops
#-----------------------------------------------------------------------#
mkdir -p /tmp/wkmntloops/etc/yum.repos.d

for i in AppStream \
         BaseOS \
         Devel \
         HighAvailability \
         PowerTools \
         centosplus \
         cr \
         extras ; do

cat > /tmp/wkmntloops/etc/yum.repos.d/CentOS-${i}.repo << EOF
[${i}]
name=CentOS-9 - ${i}
baseurl=${MIRROR}/${i}/x86_64/os
gpgcheck=0
EOF

done


dnf --releasever=9 --installroot=/tmp/wkmntloops -y install dnf
#-----------------------------------------------------------------------#
rm -f /tmp/wkmntloops/etc/resolv.conf
cp -f /etc/resolv.conf "/tmp/wkmntloops/etc"
#-----------------------------------------------------------------------#
list_pkt="dhclient sudo vim net-tools"
for d in dev sys proc; do mount --bind /$d /tmp/wkmntloops/$d; done
sleep 5
echo dnf --releasever=9 clean packages
chroot /tmp/wkmntloops/ dnf --releasever=9 clean packages
echo dnf --releasever=9 -y update
chroot /tmp/wkmntloops/ dnf --releasever=9 -y update
echo dnf --releasever=9 -y install
chroot /tmp/wkmntloops/ dnf --releasever=9 -y install $list_pkt
umount /tmp/wkmntloops/{dev,proc,sys}
#-----------------------------------------------------------------------#
umount /tmp/wkmntloops
losetup -d $DEVLOOP
rmdir /tmp/wkmntloops
#-----------------------------------------------------------------------#
mv ${ROOTFS} /home/perrier/cloonix_data/bulk
#-----------------------------------------------------------------------#


