#!/bin/bash
HERE=`pwd`
TARGZ=../../../targz_store

cd ${TARGZ}
NGINX=$(ls nginx_*)
NGINX=${NGINX%%.*}
cd ${HERE}

tar xvf ${TARGZ}/${NGINX}.tar.gz
diff -Naur nginx nginx_tainted > ${HERE}/tmp_nginx.patch


