#!/bin/bash
HERE=`pwd`
NET=nemo
DISTRO=tumbleweed
NAME=${DISTRO}
REPO=http://download.opensuse.org/tumbleweed/repo
UPDATE=http://download.opensuse.org/update/tumbleweed
CLOONIX_BULK=${HOME}/cloonix_data/bulk

cp -f ${CLOONIX_BULK}/opensuse155.qcow2 ${CLOONIX_BULK}/tumbleweed.qcow2

sync
sleep 2
sync

#######################################################################
is_started=$(cloonix_cli $NET pid |grep cloonix_server)
if [ "x$is_started" == "x" ]; then
  printf "\nServer Not started, launching:"
  printf "\ncloonix_net $NET:\n"
  cloonix_net $NET
  echo waiting 2 sec
  sleep 2
else
  cloonix_cli $NET rma
  echo waiting 10 sec
  sleep 10
fi
#######################################################################
cloonix_gui $NET
#----------------------------------------------------------------------
cloonix_cli ${NET} add nat nat
#----------------------------------------------------------------------
PARAMS="ram=8000 cpu=4 eth=s"
cloonix_cli $NET add kvm $NAME $PARAMS ${NAME}.qcow2 --persistent
#----------------------------------------------------------------------
sleep 3
cloonix_cli ${NET} add lan ${NAME} 0 lan1
cloonix_cli ${NET} add lan nat 0 lan1
#----------------------------------------------------------------------

#######################################################################
set +e
while ! cloonix_ssh $NET ${NAME} "echo" 2>/dev/null; do
  echo ${NAME} not ready, waiting 5 sec
  sleep 5
done
#----------------------------------------------------------------------
cloonix_ssh ${NET} ${NAME} "ip link set eth0 up"
cloonix_ssh ${NET} ${NAME} "systemctl restart wickedd-dhcp4.service"
cloonix_ssh ${NET} ${NAME} "systemctl restart wicked.service"
#----------------------------------------------------------------------
cloonix_ssh ${NET} ${NAME} "rm -f /etc/resolv.conf"
cloonix_ssh ${NET} ${NAME} "cat > /etc/resolv.conf << EOF
nameserver 172.17.0.3
EOF"
#----------------------------------------------------------------------
cloonix_ssh ${NET} ${NAME} "mkdir /etc/zypp/repos.d/old"
cloonix_ssh ${NET} ${NAME} "mv /etc/zypp/repos.d/*.repo /etc/zypp/repos.d/old"
cloonix_ssh ${NET} ${NAME} "zypper ar  -f -c ${REPO}/oss repo-oss"
cloonix_ssh ${NET} ${NAME} "zypper ar  -f -c ${REPO}/non-oss repo-non-oss"
cloonix_ssh ${NET} ${NAME} "zypper ar  -f -c ${UPDATE} repo-update"
cloonix_ssh ${NET} ${NAME} "zypper --gpg-auto-import-keys lr -u"
#----------------------------------------------------------------------
cloonix_ssh ${NET} ${NAME} "zypper cc -a"
cloonix_ssh ${NET} ${NAME} "zypper --non-interactive --no-gpg-checks refresh"
cloonix_ssh ${NET} ${NAME} "zypper --non-interactive --no-gpg-checks update"

echo NEXT STEP BY HAND IN SPICE CONSOLE!!!!!!!!!!!!!!!!!!!!!!
exit
cloonix_ssh ${NET} ${NAME} "zypper --non-interactive --no-gpg-checks dist-upgrade --allow-vendor-change"

sleep 2
cloonix_ssh ${NET} ${NAME} "sync"
#----------------------------------------------------------------------
cloonix_ssh $NET ${NAME} "poweroff"
echo $QCOW2 done
#----------------------------------------------------------------------

