#!/bin/bash
HERE=`pwd`
set -e

LIB_CLOWNIX=${HERE}/../lib_io_clownix

export CC=gcc
export AR=ar
export RANLIB=ranlib
export CFLAGS=""

cd $LIB_CLOWNIX
make

cd ${HERE}/../cloonix_dropbear
make clean
make

cp -f scp      ${HERE}/cloonix-dropbear-scp
cp -f dbclient ${HERE}/cloonix-dropbear-ssh


