#!/bin/bash
#----------------------------------------------------------------------#
DISTRO=bookworm
ROOTFS=/root/${DISTRO}.img
DEBIAN_REPO="http://deb.debian.org/debian"
#----------------------------------------------------------------------#
fct_check_uid()
{
  if [ $UID != 0 ]; then
    echo you must be root
    exit -1
  fi
}
#----------------------------------------------------------------------#
fct_check_losetup()
{
  modprobe loop
  if [[ "$(losetup -a )" != "" ]]; then
    echo
    echo
    echo losetup -a should give nothing, it gives:
    losetup -a
    echo
    exit -1
  fi
}
#----------------------------------------------------------------------#

#########################################################################
fct_check_uid
set +e
for i in debootstrap wget ; do
  path_bin=$(which $i)
  if [ -z $path_bin ]; then
    echo $i  DOES NOT EXIST
    exit -1
  fi
done
if [ -e $ROOTFS ]; then
  echo $ROOTFS already exists
  exit 1
fi
fct_check_losetup
set -e
#-----------------------------------------------------------------------#
list_pkt="openssh-client,bash-completion,sudo,kbd,vim,net-tools"
dd if=/dev/zero of=${ROOTFS} bs=500M count=10
mkfs.ext4 ${ROOTFS}
losetup -fP ${ROOTFS}
mkdir -p /tmp/wkmntloops
DEVLOOP=$(losetup -l | grep ${ROOTFS} | awk '{print $1}')
echo $DEVLOOP
mount -o loop $DEVLOOP /tmp/wkmntloops
list_pkt="openssh-client,bash-completion,sudo,kbd,vim,net-tools"
debootstrap --no-check-certificate \
	    --no-check-gpg \
            --arch amd64 \
            --include=$list_pkt \
            ${DISTRO} \
            /tmp/wkmntloops ${DEBIAN_REPO}
#-----------------------------------------------------------------------#
cat > /tmp/wkmntloops/etc/apt/sources.list << EOF
deb http://deb.debian.org/debian ${DISTRO} main contrib non-free
EOF
#-----------------------------------------------------------------------#
echo "source /etc/bash_completion" >> /tmp/wkmntloops/root/.bashrc
sync /dev/loop0
#-----------------------------------------------------------------------#
chroot /tmp/wkmntloops/ passwd root <<EOF
root
root
EOF
umount /tmp/wkmntloops/
losetup -d $DEVLOOP
#-----------------------------------------------------------------------#

