#!/bin/bash
set -e
ROOTFS=/root/centos9.img
MIRROR="https://mirror.stream.centos.org/9-stream"

#----------------------------------------------------------------------#
fct_check_uid()
{
  if [ $UID != 0 ]; then
    echo you must be root
    exit -1
  fi
}
#----------------------------------------------------------------------#
fct_check_losetup()
{
  modprobe loop
  if [[ "$(losetup -a )" != "" ]]; then
    echo
    echo
    echo losetup -a should give nothing, it gives:
    losetup -a
    echo
    exit -1
  fi
}
#----------------------------------------------------------------------#

#########################################################################
fct_check_uid
#----------------------------------------------------------------------#
set +e
for i in rpm dnf wget ; do
  path_bin=$(which $i)
  if [ -z $path_bin ]; then
    echo $i  DOES NOT EXIST
    exit -1
  fi
done

if [ -e $ROOTFS ]; then
  echo $ROOTFS already exists
  exit 1
fi

fct_check_losetup
set -e
#-----------------------------------------------------------------------#
dd if=/dev/zero of=${ROOTFS} bs=500M count=10
mkfs.ext4 ${ROOTFS}
losetup -fP ${ROOTFS}
mkdir -p /tmp/wkmntloops
DEVLOOP=$(losetup -l | grep ${ROOTFS} | awk '{print $1}')
echo $DEVLOOP
mount -o loop $DEVLOOP /tmp/wkmntloops
mkdir -p /tmp/wkmntloops/etc/yum.repos.d

for i in AppStream \
         BaseOS \
         CRB; do

cat > /tmp/wkmntloops/etc/yum.repos.d/CentOS-${i}.repo << EOF
[${i}]
name=CentOS-9 - ${i}
baseurl=${MIRROR}/${i}/x86_64/os
gpgcheck=0
EOF

done

dnf --releasever=9 --installroot=/tmp/wkmntloops -y install dnf
#-----------------------------------------------------------------------#
rm -f /tmp/wkmntloops/etc/resolv.conf
cp -f /etc/resolv.conf "/tmp/wkmntloops/etc"
#-----------------------------------------------------------------------#
list_pkt="passwd openssh-clients iputils sudo kbd vim net-tools"
for d in dev sys proc; do mount --bind /$d /tmp/wkmntloops/$d; done
sleep 5
echo dnf --releasever=9 clean packages
chroot /tmp/wkmntloops/ dnf --releasever=9 clean packages
echo dnf --releasever=9 -y update
chroot /tmp/wkmntloops/ dnf --releasever=9 -y update
echo dnf --releasever=9 -y install
chroot /tmp/wkmntloops/ dnf --releasever=9 -y install $list_pkt
#-----------------------------------------------------------------------#
chroot /tmp/wkmntloops/ passwd root <<EOF
root
root
EOF
#-----------------------------------------------------------------------#
umount /tmp/wkmntloops/{dev,proc,sys}
umount /tmp/wkmntloops/
losetup -d $DEVLOOP
#-----------------------------------------------------------------------#

