#!/bin/bash
HERE=`pwd`
cd ${HERE}/lib_doorways
make clean
cd ${HERE}/lib_doorways/tst
make clean
cd ${HERE}/lib_doorways/tst/serv
make clean
cd ${HERE}
rm -f cloonix-u2i-ssh
rm -f cloonix-u2i-scp
rm -rf tainted_openssh-portable
rm -rf openssh-portable
