#!/bin/bash
HERE=`pwd`
TARGZ=${HERE}/../../../targz_store
cd ${TARGZ}
OPENSSH=$(ls openssh-portable_*)
OPENSSH=${OPENSSH%%.*}
cd ${HERE}
if [ -e tainted_openssh-portable ]; then
  echo remove tainted_openssh-portable directory and start again
  exit 1
fi
tar xvf ${TARGZ}/${OPENSSH}.tar.gz
mv openssh-portable tainted_openssh-portable
cd tainted_openssh-portable
patch -f -p1 < ../openssh.patch

