#!/bin/bash
HERE=`pwd`
TARGZ=${HERE}/../../../../targz_store

rm -rf spice-gtk

if [ -e tainted_spice ]; then
  echo remove tainted_spice directory and start again
  exit 1
fi

cd ${TARGZ}
SPICEGTK=$(ls spice-gtk_*)
SPICEGTK=${SPICEGTK%%.*}
cd ${HERE}

tar xvf ${TARGZ}/${SPICEGTK}.tar.gz
mv spice-gtk tainted_spice

cd tainted_spice
patch -p1 < ../cloonix.patch


