#!/bin/bash
HERE=`pwd`
set -e

TARGZ_STORE=${HERE}/../../../targz_store
tar --directory=/tmp -xf ${TARGZ_STORE}/patchelf_*.tar.gz
cd /tmp/patchelf
make

TARGET="${HERE}/../insider_agents"
ISO_NAME="insider_agent_x86_64.iso"
XORRISO="/usr/bin/xorrisofs"
CDROM="${TARGET}/cdrom"

rm -f ${TARGET}/${ISO_NAME}
rm -rf ${CDROM}

mkdir -p ${CDROM}/lib
LIB_CLOWNIX=${HERE}/../../common/lib_io_clownix

export CC=gcc
export AR=ar
export RANLIB=ranlib
export CFLAGS=""

cd $LIB_CLOWNIX
export CFLAGS="-DNO_HMAC_CIPHER"
export LDFLAGS=
make clean
make

cd ${HERE}/../../common/cloonix_dropbear
export CFLAGS=
export LDFLAGS=
make clean
make dropbear

LIBC=$(ldd dropbear | grep libc.so |awk '{print $3}')
LIBD=$(ldd dropbear | grep ld-linux |awk '{print $1}')

if [ -z ${LIBC} ]; then
  LIBC=$(ldd dropbear | grep libc.musl-x86_64.so |awk '{print $3}')
  LIBD=""
fi
echo
echo $LIBC
echo

cd ${HERE}/../../common/cloonix_dropbear
LIB_DST=/cloonixmnt/cnf_fs/lib
export CFLAGS=
export LDFLAGS="-Wl,-rpath -Wl,${LIB_DST}"

if [ ! -z ${LIBD} ]; then
  LIBD_NAME=${LIBD##*/}
  echo $LIBD_NAME
  export LDFLAGS="${LDFLAGS} -Wl,--dynamic-linker -Wl,${LIB_DST}/${LIBD_NAME}"
fi

make clean
make dropbear
make scp

cp dropbear ${CDROM}/cloonix-dropbear-sshd
cp /usr/bin/scp ${CDROM}/cloonix-scp
for i in "touch" \
         "xauth" ; do
  cp /usr/bin/${i} ${CDROM}
done

RPATH_LIB="${LIB_DST}"
PATCHELF="/tmp/patchelf/src/patchelf"

if [ ! -z ${LIBD} ]; then
  LDLINUX="${LIB_DST}/ld-linux-x86-64.so.2"
  cp -vf ${LIBD} ${CDROM}/lib
fi
cp -vf ${LIBC} ${CDROM}/lib

for i in "libX11.so.6" \
         "libXau.so.6" \
         "libXext.so.6" \
         "libXmuu.so.1" \
         "libxcb.so.1" \
         "libXdmcp.so.6"; do
  cp /lib/x86_64-linux-gnu/${i} ${CDROM}/lib
  ${PATCHELF} --force-rpath --set-rpath ${RPATH_LIB} ${CDROM}/lib/${i} 2>/dev/null
  if [ ! -z ${LIBD} ]; then
    set +e
    ${PATCHELF} --set-interpreter ${LDLINUX} ${CDROM}/lib/${i} 2>/dev/null
    set -e
  fi
done

for i in "touch" \
         "xauth" \
         "cloonix-scp" ; do
  ${PATCHELF} --force-rpath --set-rpath ${RPATH_LIB} ${CDROM}/${i} 2>/dev/null
  if [ ! -z ${LIBD} ]; then
    ${PATCHELF} --set-interpreter ${LDLINUX} ${CDROM}/${i} 2>/dev/null
  fi
done

cd ${HERE}/cloonix_agent
make clean
make

cp cloonix-agent ${CDROM}
make clean

cd ${LIB_CLOWNIX}
make clean

cp ${HERE}/init_starter/* ${CDROM}
${XORRISO} -o ${TARGET}/${ISO_NAME} ${CDROM}
# rm -rf ${CDROM}
