#!/bin/bash
HERE=`pwd`
set -e

TARGZ_STORE=${HERE}/../../../targz_store
tar --directory=/tmp -xf ${TARGZ_STORE}/patchelf_*.tar.gz
cd /tmp/patchelf
make

TARGET="${HERE}/../insider_agents"
ISO_NAME="insider_agent_x86_64.iso"
XORRISO="/usr/bin/xorrisofs"
CDROM="${TARGET}/cdrom"

rm -f ${TARGET}/${ISO_NAME}
rm -rf ${CDROM}

mkdir -p ${CDROM}/lib
LIB_CLOWNIX=${HERE}/../../common/lib_io_clownix

export CC=gcc
export AR=ar
export RANLIB=ranlib
export CFLAGS=""

cd $LIB_CLOWNIX
export CFLAGS="-DNO_HMAC_CIPHER"
export LDFLAGS=
make clean
make

cd ${HERE}/../../common/cloonix_dropbear
export CFLAGS=
export LDFLAGS=
make clean
make dropbear

LIBC=$(ldd dropbear | grep libc.so |awk '{print $3}')
LIBD=$(ldd dropbear | grep ld-linux |awk '{print $1}')

if [ -z ${LIBC} ]; then
  LIBC=$(ldd dropbear | grep libc.musl-x86_64.so |awk '{print $3}')
  LIBD=""
fi
echo
echo $LIBC
echo

cd ${HERE}/../../common/cloonix_dropbear
LIB_DST=/mnt/cloonix_config_fs/lib
export CFLAGS=
export LDFLAGS="-Wl,-rpath -Wl,${LIB_DST}"

if [ ! -z ${LIBD} ]; then
  LIBD_NAME=${LIBD##*/}
  echo $LIBD_NAME
  export LDFLAGS="${LDFLAGS} -Wl,--dynamic-linker -Wl,${LIB_DST}/${LIBD_NAME}"
fi

make clean
make dropbear
make scp

cp dropbear ${CDROM}/cloonix-dropbear-sshd
cp /usr/bin/scp ${CDROM}/cloonix-scp

RPATH_LIB="${LIB_DST}"
PATCHELF="/tmp/patchelf/src/patchelf"
${PATCHELF} --force-rpath --set-rpath ${RPATH_LIB} ${CDROM}/cloonix-scp 2>/dev/null

if [ ! -z ${LIBD} ]; then
  LDLINUX="${LIB_DST}/ld-linux-x86-64.so.2"
  ${PATCHELF} --set-interpreter ${LDLINUX}  ${CDROM}/cloonix-scp 2>/dev/null
  cp -vf ${LIBD} ${CDROM}/lib
fi

cp -vf ${LIBC} ${CDROM}/lib

cd ${HERE}/cloonix_agent
make clean
make

cp cloonix-agent ${CDROM}
make clean

cd ${LIB_CLOWNIX}
make clean

cp ${HERE}/init_starter/* ${CDROM}
${XORRISO} -o ${TARGET}/${ISO_NAME} ${CDROM}
# rm -rf ${CDROM}
