#!/bin/bash
HERE=`pwd`
OVS=${HERE}
TARGZ=../../../targz_store
./allclean
mkdir -p ${OVS}/bin
tar xvf ${TARGZ}/ovs_*.tar.gz
cd ${HERE}/ovs
rm -rf .git
patch -p1 < ${HERE}/ovs.patch
./boot.sh

export CFLAGS=" -mtune=generic -fno-stack-protector -g -DALLOW_EXPERIMENTAL_API -pthread -lm -ldl -lnuma -lpcap -lrt -fPIC -lunwind"

./configure  --prefix=${HERE}
make -j 6
cd ${HERE}

for i in ovsdb-client ovsdb-server ovsdb-tool; do
  cp -vf ${HERE}/ovs/ovsdb/${i} ${OVS}/bin/cloonix-${i}
  strip ${OVS}/bin/cloonix-${i}
done

for i in ovs-appctl ovs-ofctl ovs-vsctl; do
  cp -vf ${HERE}/ovs/utilities/${i} ${OVS}/bin/cloonix-${i}
  strip ${OVS}/bin/cloonix-${i}
done

cp -vf ${HERE}/ovs/vswitchd/ovs-vswitchd ${OVS}/bin/cloonix-ovs-vswitchd
strip ${OVS}/bin/cloonix-ovs-vswitchd

mkdir -p ${OVS}/share/openvswitch
cp -vf ${HERE}/ovs/vswitchd/vswitch.ovsschema ${OVS}/cloonix-vswitch.ovsschema

