#!/bin/bash
HERE=`pwd`
TARGZ=../../../targz_store

cd ${TARGZ}
OVS=$(ls ovs_*)
OVS=${OVS%%.*}
cd ${HERE}

tar xvf ${TARGZ}/${OVS}.tar.gz
mv ovs ovs_tainted
cd ovs_tainted
patch -p1 < ${HERE}/ovs.patch


