#!/bin/bash
HERE=`pwd`
#----------------------------------------------------------------------#
if [ ${#} = 1 ]; then
  if [ "$1" = "i386" ]; then
    ARCH="i386"
    QCOW2="debian_builder_i386.qcow2"
    IP="ip_debian_i386.qcow2"
  else
    echo param must be i386, if no param, then is amd64
    exit
  fi
else
  ARCH="amd64"
  QCOW2="debian_builder_amd64.qcow2"
  IP="ip_debian_amd64.qcow2"
fi
#----------------------------------------------------------------------
BULK="/var/lib/cloonix/bulk"
if [ ! -e ${BULK}/${QCOW2} ]; then
  echo
  echo Missing:
  echo ${BULK}/${QCOW2}
  echo
  exit 1
fi
#----------------------------------------------------------------------
is_started=$(cloonix_cli nemo pid |grep cloonix_server)
if [ "x$is_started" == "x" ]; then
  printf "\nServer Not started, launching:"
  printf "\ncloonix_net nemo:\n"
  cloonix_net nemo
  echo waiting 2 sec
  sleep 2
else
  cloonix_cli nemo rma
  echo waiting 10 sec
  sleep 10
fi
#----------------------------------------------------------------------
cp -f ${BULK}/${QCOW2} ${BULK}/${IP}
sync
sleep 1
sync
#----------------------------------------------------------------------
cloonix_gui nemo
#----------------------------------------------------------------------
if [ ${ARCH} = "i386" ]; then
  cloonix_cli nemo add kvm ip ram=12000 cpu=8 eth=s ${IP} --persistent --i386 
else
  cloonix_cli nemo add kvm ip ram=8000 cpu=8 eth=s ${IP} --persistent 
fi
#----------------------------------------------------------------------
sleep 3
#----------------------------------------------------------------------
set +e
while ! cloonix_ssh nemo ip "echo" 2>/dev/null; do
  echo ip not ready, waiting 5 sec
  sleep 5
done
#----------------------------------------------------------------------
cloonix_scp nemo ${HERE}/iproute2-6.11.0.tar.gz ip:/root 
cloonix_scp nemo ${HERE}/iproute2-6.10.0.patch ip:/root 
cloonix_ssh nemo ip "tar xvf iproute2-6.11.0.tar.gz"
cloonix_ssh nemo ip "cd iproute2-6.11.0; patch -p1 < ../iproute2-6.10.0.patch"
cloonix_ssh nemo ip "cd iproute2-6.11.0; ./configure"
cloonix_ssh nemo ip "cd iproute2-6.11.0; make"
#----------------------------------------------------------------------
cloonix_ssh nemo ip "sync"
cloonix_ssh nemo ip "poweroff"
#----------------------------------------------------------------------





