#!/bin/bash
HERE=`pwd`

for i in dpdk_tainted ovs_tainted \
         dpdk ovs; do
  rm -rf ${HERE}/$i
done

for i in usr etc bin include lib sbin share var x86_64-linux-gnu; do
  rm -rf ${HERE}/$i
done




