#!/bin/bash
HERE=`pwd`

for i in dpdk_tainted openvswitch_tainted \
         dpdk-19.02 openvswitch-2.11.1; do
  rm -rf ${HERE}/$i
done

for i in etc bin include lib sbin share var; do
  rm -rf ${HERE}/$i
done




