#!/bin/bash
HERE=`pwd`
TARGZ=${HERE}/../../../targz_store
NINJA=${HERE}/../../common/meson_ninja
./allclean
if [ ! -f ${NINJA}/ninja/ninja ]; then
  cd ${NINJA}
  ./cmd
fi
cd ${HERE}
tar xvf ${TARGZ}/dpdk_*.tar.gz
cd ${HERE}/dpdk
echo patch -p1 < ${HERE}/dpdk.patch
patch -p1 < ${HERE}/dpdk.patch
sleep 2
export PATH=${NINJA}/ninja:$PATH
${NINJA}/meson/meson.py -Dexamples=l2fwd build
cd ${HERE}/dpdk/build
ninja
DESTDIR=${HERE} ninja install
cp -vrf ${HERE}/usr/local/bin     ${HERE}
cp -vrf ${HERE}/usr/local/include ${HERE}
mkdir -p ${HERE}/lib
if [ -d ${HERE}/usr/local/lib64 ]; then
  cp -vrf ${HERE}/usr/local/lib64/* ${HERE}/lib
else
  cp -vrf ${HERE}/usr/local/lib/x86_64-linux-gnu/* ${HERE}/lib
fi
cp -vrf ${HERE}/include ${HERE}/dpdk/build
cp -vrf ${HERE}/lib ${HERE}/dpdk/build
for i in etc sbin share usr var; do
  rm -rf ${HERE}/${i}
done
sed -i '1s/python/python3/' ${HERE}/bin/dpdk-devbind.py
for pc in ${HERE}/lib/pkgconfig/libdpdk.pc \
          ${HERE}/lib/pkgconfig/libdpdk-libs.pc ; do
  sed -i s"%libdir=\${prefix}/lib64%libdir=${HERE}/lib%" ${pc}
  sed -i s"%libdir=\${prefix}/lib/x86_64-linux-gnu%libdir=${HERE}/lib%" ${pc}
  sed -i s"%includedir=\${prefix}/include%includedir=${HERE}/include%" ${pc}
  sed -i s"%{libdir}%{libdir} -Wl,-rpath,/usr/local/bin/cloonix/server/dpdk/lib%" ${pc}
done
sed -i s"%-lrte_kvargs%-lrte_kvargs -Wl,--no-as-needed%" ${HERE}/lib/pkgconfig/libdpdk-libs.pc


