#!/bin/bash
HERE=`pwd`
TARGZSTORE=../../../targz_store
NAMEZ=dpdk-19.02.tar.xz
NAME=dpdk-19.02
tar xvf ${TARGZSTORE}/${NAMEZ}
exit
mv ${NAME} dpdk_tainted
cd dpdk_tainted
patch -p1 < ${HERE}/dpdk.patch


