#!/bin/bash
HERE=`pwd`
TARGZSTORE=../../../targz_store
NAMEZ=openvswitch-2.11.1.tar.gz
NAME=openvswitch-2.11.1
tar xvf ${TARGZSTORE}/${NAMEZ}
diff -Naur ${NAME} openvswitch_tainted > ${HERE}/tmp_openvswitch.patch


