#!/bin/bash
HERE=`pwd`
TARGZ=../../../targz_store

cd ${TARGZ}
DPDK=$(ls dpdk_*)
DPDK=${DPDK%%.*}
cd ${HERE}

tar xvf ${TARGZ}/${DPDK}.tar.gz
mv dpdk dpdk_tainted
cd dpdk_tainted
patch -p1 < ${HERE}/dpdk.patch


