#!/bin/bash
HERE=`pwd`
TARGZ=${HERE}/../../../../targz_store
if [ ! -e tainted_spice ]; then
  echo Must have tainted_spice
fi
tar xvf ${TARGZ}/spice-gtk.tar.gz
diff -Naur spice-gtk tainted_spice > tmp_cloonix.patch
