#!/bin/bash
HERE=`pwd`
NET=nemo
DISTRO=centos8
NAME=${DISTRO}
QCOW2=${DISTRO}.qcow2
CLOONIX_CENTOS8_REPO=https://mirrors.edge.kernel.org/centos/8
#######################################################################
CLOONIX_CONFIG=/usr/local/bin/cloonix/cloonix_config
CLOONIX_BULK=$(cat $CLOONIX_CONFIG |grep CLOONIX_BULK | awk -F = "{print \$2}")
BULK=$(eval echo $CLOONIX_BULK)
#######################################################################
is_started=$(cloonix_cli $NET pid |grep cloonix_server)
if [ "x$is_started" == "x" ]; then
  printf "\nServer Not started, launching:"
  printf "\ncloonix_net $NET:\n"
  cloonix_net $NET
  echo waiting 2 sec
  sleep 2
else
  cloonix_cli $NET rma
  echo waiting 10 sec
  sleep 10
fi
#----------------------------------------------------------------------
cp -f ${BULK}/${QCOW2} ${BULK}/full_${QCOW2}
sync
sleep 10
sync
#######################################################################
cloonix_gui $NET
#----------------------------------------------------------------------
PARAMS="ram=8000 cpu=4 eth=s"
cloonix_cli $NET add kvm $NAME $PARAMS full_$QCOW2 --persistent
#----------------------------------------------------------------------
cloonix_cli ${NET} add nat nat
#######################################################################
set +e
while ! cloonix_ssh $NET ${NAME} "echo" 2>/dev/null; do
  echo ${NAME} not ready, waiting 5 sec
  sleep 5
done
set -e
#----------------------------------------------------------------------
cloonix_cli ${NET} add lan ${NAME} 0 lan1
cloonix_cli ${NET} add lan nat 0 lan1
#----------------------------------------------------------------------
cloonix_ssh $NET ${NAME} "mkdir -p /root/cloonix_data/bulk"
#----------------------------------------------------------------------
cloonix_scp $NET ${HERE}/../../install_depends ${NAME}:/root
#----------------------------------------------------------------------
cloonix_scp $NET ${BULK}/bullseye.qcow2 ${NAME}:/root/cloonix_data/bulk
#----------------------------------------------------------------------
cloonix_ssh $NET ${NAME} "dhclient"
#----------------------------------------------------------------------
cloonix_ssh ${NET} ${NAME} "cat > /etc/yum.repos.d/CentOS-Base.repo << EOF
[base]
name=CentOS-8 - Base
baseurl=${CLOONIX_CENTOS8_REPO}/BaseOS/x86_64/os
gpgcheck=0
EOF"
cloonix_ssh ${NET} ${NAME} "cat > /etc/yum.repos.d/CentOS-AppStream.repo << EOF
[AppStream]
name=CentOS-8 - AppStream
baseurl=${CLOONIX_CENTOS8_REPO}/AppStream/x86_64/os
gpgcheck=0
EOF"
cloonix_ssh ${NET} ${NAME} "cat > /etc/yum.repos.d/CentOS-Extras.repo << EOF
[extras]
name=CentOS-8 - Extras
baseurl=${CLOONIX_CENTOS8_REPO}/extras/x86_64/os
gpgcheck=0
EOF"
cloonix_ssh ${NET} ${NAME} "cat > /etc/yum.repos.d/CentOS-PowerTools.repo << EOF
[PowerTools]
name=CentOS-8 - PowerTools
baseurl=${CLOONIX_CENTOS8_REPO}/PowerTools/x86_64/os
gpgcheck=0
EOF"
cloonix_ssh ${NET} ${NAME} "cat > /etc/yum.repos.d/CentOS-Cloud.repo << EOF
[Cloud]
name=CentOS-8 - Cloud
baseurl=${CLOONIX_CENTOS8_REPO}/cloud/x86_64/openstack-train
gpgcheck=0
EOF"
#----------------------------------------------------------------------
cloonix_ssh ${NET} ${NAME} "cat > /etc/resolv.conf << EOF
nameserver 172.17.0.3
EOF"
#----------------------------------------------------------------------
cloonix_ssh $NET ${NAME} "dnf update -y"
#----------------------------------------------------------------------
set +e
for ((i=0;i<3;i++)); do
  cloonix_ssh $NET ${NAME} "./install_depends"
  sleep 10
done
#----------------------------------------------------------------------
cloonix_ssh $NET ${NAME} "rm -f install_depends"
#----------------------------------------------------------------------
KERN="noquiet console=ttyS0 console=tty1 earlyprintk=serial "
KERN+="net.ifnames=0 "
KERN+="default_hugepagesz=1G hugepagesz=1G hugepages=2"
printf "\nGRUB_CMDLINE_LINUX_DEFAULT=\"%s\"\n" "$KERN" > /tmp/grub

cloonix_scp $NET /tmp/grub ${NAME}:/etc/default

cloonix_ssh $NET ${NAME} "grub2-mkconfig -o /boot/grub2/grub.cfg"

cloonix_ssh $NET ${NAME} "sync"
#----------------------------------------------------------------------
cloonix_ssh $NET ${NAME} "poweroff"
echo $QCOW2 done
#----------------------------------------------------------------------



