#!/bin/bash
HERE=`pwd`
NET=nemo
DISTRO=centos8
NAME=${DISTRO}
#######################################################################
is_started=$(cloonix_cli $NET pid |grep cloonix_server)
if [ "x$is_started" == "x" ]; then
  printf "\nServer Not started, launching:"
  printf "\ncloonix_net $NET:\n"
  cloonix_net $NET
  echo waiting 2 sec
  sleep 2
else
  cloonix_cli $NET rma
  echo waiting 10 sec
  sleep 10
fi
#######################################################################
cloonix_gui $NET
#----------------------------------------------------------------------
cloonix_cli $NET add kvm $NAME ram=8000 cpu=4 eth=d full_${NAME}.qcow2 --persistent
#----------------------------------------------------------------------
cloonix_cli ${NET} add nat nat
#######################################################################
set +e
while ! cloonix_ssh $NET ${NAME} "echo" 2>/dev/null; do
  echo ${NAME} not ready, waiting 5 sec
  sleep 5
done
set -e
#----------------------------------------------------------------------
cloonix_cli ${NET} add lan ${NAME} 0 lan1
cloonix_cli ${NET} add lan nat 0 lan1
#----------------------------------------------------------------------
cloonix_scp $NET ${HERE}/../../install_depends ${NAME}:/root
#----------------------------------------------------------------------
cloonix_ssh $NET ${NAME} "dhclient"
#----------------------------------------------------------------------
cloonix_ssh $NET ${NAME} "dnf update -y"
#----------------------------------------------------------------------
set +e
for ((i=0;i<2;i++)); do
  cloonix_ssh $NET ${NAME} "./install_depends"
  sleep 10
done
#----------------------------------------------------------------------
cloonix_ssh $NET ${NAME} "rm -f install_depends"
#----------------------------------------------------------------------
cloonix_ssh $NET ${NAME} "sync"
#----------------------------------------------------------------------
cloonix_ssh $NET ${NAME} "poweroff"
echo $QCOW2 done
#----------------------------------------------------------------------



