#!/bin/bash
HERE=`pwd`
NET=nemo
DISTRO=jammy
NAME=${DISTRO}
#######################################################################
is_started=$(cloonix_cli $NET pid |grep cloonix_server)
if [ "x$is_started" == "x" ]; then
  printf "\nServer Not started, launching:"
  printf "\ncloonix_net $NET:\n"
  cloonix_net $NET
  echo waiting 2 sec
  sleep 2
else
  cloonix_cli $NET rma
  echo waiting 10 sec
  sleep 10
fi
#######################################################################
cloonix_gui $NET
#----------------------------------------------------------------------
cloonix_cli ${NET} add nat nat
#----------------------------------------------------------------------
PARAMS="ram=8000 cpu=4 eth=s"
cloonix_cli $NET add kvm $NAME $PARAMS full_${NAME}.qcow2 --persistent
#----------------------------------------------------------------------
sleep 3
cloonix_cli ${NET} add lan ${NAME} 0 lan1
cloonix_cli ${NET} add lan nat 0 lan1
#----------------------------------------------------------------------

#######################################################################
set +e
while ! cloonix_ssh $NET ${NAME} "echo" 2>/dev/null; do
  echo ${NAME} not ready, waiting 5 sec
  sleep 5
done
set -e
#----------------------------------------------------------------------
cloonix_scp $NET ${HERE}/../../install_depends ${NAME}:/root
#----------------------------------------------------------------------
cloonix_ssh ${NET} ${NAME} "cat > /etc/resolv.conf << EOF
nameserver 172.17.0.3
EOF"
#----------------------------------------------------------------------
cloonix_ssh $NET ${NAME} "dhclient"
#----------------------------------------------------------------------
set +e
for ((i=0;i<2;i++)); do
  cloonix_ssh $NET ${NAME} "./install_depends"
  sleep 10
done
#----------------------------------------------------------------------
cloonix_ssh $NET ${NAME} "rm -f install_depends"
#----------------------------------------------------------------------
cloonix_ssh $NET ${NAME} "sync"
exit
#----------------------------------------------------------------------
cloonix_ssh $NET ${NAME} "poweroff"
echo $QCOW2 done
#----------------------------------------------------------------------





