#!/bin/bash
set -e
HERE=`pwd`
MESON_NINJA=${HERE}/../../common/meson_ninja
TARGZ=${HERE}/../../../targz_store
TARGET=${HERE}/spice_lib
rm -rf ${TARGET}
mkdir -p ${TARGET}

cd $TARGET
tar xvf ${TARGZ}/spice-protocol.tar.gz
cd spice-protocol
rm -rf build
export PATH=${MESON_NINJA}/ninja:$PATH
${MESON_NINJA}/meson/meson.py build
cd build
${MESON_NINJA}/meson/meson.py configure --prefix=${TARGET} \
                                        --datadir=${TARGET} \
                                        --libdir=${TARGET} \
                                        --includedir=${TARGET}
ninja
ninja install

cd ${TARGET}
tar xvf ${TARGZ}/usbredir.tar.gz
cd usbredir

./configure --prefix=${TARGET} --libdir=${TARGET} 

make clean
make
make install


cd ${TARGET}
tar xvf ${TARGZ}/libepoxy.tar.gz
tar xvf ${TARGZ}/virglrenderer.tar.gz
cd libepoxy
${MESON_NINJA}/meson/meson.py build
cd build
${MESON_NINJA}/meson/meson.py configure --prefix=${TARGET} \
                                        --datadir=${TARGET} \
                                        --libdir=${TARGET} \
                                        --includedir=${TARGET}
ninja
ninja install

export PKG_CONFIG_PATH=${TARGET}/pkgconfig

cd ${TARGET}

cd virglrenderer
patch -p1 < ${HERE}/virglrenderer.patch
${MESON_NINJA}/meson/meson.py build
cd build
${MESON_NINJA}/meson/meson.py configure --prefix=${TARGET} \
                                        --datadir=${TARGET} \
                                        --libdir=${TARGET} \
                                        --includedir=${TARGET}/include
ninja
ninja install

