#!/bin/bash
set -e
HERE=`pwd`
MESON_NINJA=${HERE}/../../common/meson_ninja
TARGZ=${HERE}/../../../targz_store
TARGET=${HERE}/spice_lib
rm -rf ${TARGET}
mkdir -p ${TARGET}

cd $TARGET
tar xvf ${TARGZ}/spice-protocol_*.tar.gz
cd spice-protocol
rm -rf build
export PATH=${MESON_NINJA}/ninja:$PATH
${MESON_NINJA}/meson/meson.py --prefix=${TARGET} \
                              --datadir=${TARGET} \
                              --libdir=${TARGET} \
                              --includedir=${TARGET} build
cd build

ninja
ninja install

cd ${TARGET}
tar xvf ${TARGZ}/usbredir_*.tar.gz
cd usbredir
rm -rf build
sed -i s"/subdir('tests')/#subdir('tests')/" meson.build 
export PATH=${MESON_NINJA}/ninja:$PATH
${MESON_NINJA}/meson/meson.py --prefix=${TARGET} \
                              --datadir=${TARGET} \
                              --libdir=${TARGET} \
                              --includedir=${TARGET} build
cd build

ninja
ninja install

