#!/bin/bash
HERE=`pwd`
TARGZ=${HERE}/../../../targz_store

cd ${TARGZ}
QEMU_NAME=$(ls qemu_*)
QEMU_NAME=${QEMU_NAME%%.*}
cd ${HERE}

rm -rf qemu_vip

if [ ! -e tainted_qemu ]; then
  echo tainted_qemu directory must exist 
  exit 1
fi

tar xvf ${TARGZ}/${QEMU_NAME}.tar.gz
diff -Naur qemu_vip tainted_qemu > tmp_cloonix_patch
rm -rf qemu_vip
