#!/bin/bash
HERE=`pwd`
TARGZ=${HERE}/../../../targz_store

cd ${TARGZ}
QEMU_NAME=$(ls qemu_*)
QEMU_NAME=${QEMU_NAME%%.*}
cd ${HERE}

rm -rf $QEMU_NAME

if [ -e tainted_qemu ]; then
  echo remove tainted_qemu directory and start again
  exit 1
fi

tar xvf ${TARGZ}/${QEMU_NAME}.tar.gz

mv qemu_vip tainted_qemu

cd tainted_qemu

patch -f -p1 < ../cloonix_patch

