#!/bin/bash
HERE=`pwd`
IO_CLOWNIX=../lib_io_clownix
RPC_CLOWNIX=../lib_rpc_clownix
LIB_UTILS=../lib_utils
RPC_LAYOUT=../lib_rpc_layout
cd ${IO_CLOWNIX}
./allclean
cd ${RPC_CLOWNIX}
./allclean
cd ${LIB_UTILS}
./allclean
cd ${RPC_LAYOUT}
./allclean

cd ${HERE}/../lib_client
make clean


for i in ${HERE}/crcanvas_gtk \
         ${HERE}/src/bank \
         ${HERE}/src/interface \
         ${HERE}/src/subsets \
         ${HERE}/src/bdplot ;
do 
  echo
  echo CLEAN:
  echo ${i}
  echo
  cd ${i}
  make clean
done
cd ${HERE}
make clean


