#!/bin/bash
HERE=`pwd`
./allclean

cd ${HERE}/../../common/lib_io_clownix
make
cd ${HERE}/lib_doorways
mkdir -p obj
make
cd ${HERE}
path_openssl=$(which openssl)
if [ -z $path_openssl ]; then
  echo openssl dev required
  exit 1
fi


./patched_create
cd tainted_openssh

./configure
make

mv ssh cloonix-u2i-ssh
mv scp cloonix-u2i-scp
mv cloonix-u2i-ssh $HERE
mv cloonix-u2i-scp $HERE

