#!/bin/bash
HERE=`pwd`
TARGZ=${HERE}/../../../targz_store
cd ${TARGZ}
OPENSSH=$(ls openssh-portable_*)
OPENSSH=${OPENSSH%%.*}
cd ${HERE}
if [ ! -e tainted_openssh-portable ]; then
  echo tainted_openssh-portable directory must exist 
  exit 1
fi
tar xvf ${TARGZ}/${OPENSSH}.tar.gz
diff -Naur openssh-portable tainted_openssh-portable > tmp_openssh_patch
rm -rf openssh-portable
