#!/bin/bash
HERE=`pwd`
TARGZ=${HERE}/../../../targz_store
OPENSSH=openssh-8.6p1
rm -rf $OPENSSH
if [ -e tainted_openssh ]; then
  echo remove tainted_openssh directory and start again
  exit 1
fi
tar xvf ${TARGZ}/${OPENSSH}.tar.gz
mv ${OPENSSH} tainted_openssh
cd tainted_openssh
patch -f -p1 < ../openssh.patch

