#!/bin/bash
HERE=`pwd`
TARGZ=${HERE}/../../../targz_store
version_openssl=$1
OPENSSH=openssh-7.6p1
rm -rf $OPENSSH
if [ -e tainted_openssh ]; then
  echo remove tainted_openssh directory and start again
  exit 1
fi
tar xvf ${TARGZ}/${OPENSSH}.tar.gz
mv ${OPENSSH} tainted_openssh
cd tainted_openssh
if [ "$version_openssl" = "1.1" ]; then
  patch -f -p1 < ../openssh-7.6p1-openssl-1.1.0-1.patch
fi
patch -f -p1 < ../openssh.patch

