#!/bin/bash
set -e
HERE=`pwd`
TARGZ=${HERE}/../../../targz_store
TARGET=${HERE}/.
#----------------------------------------------------------
cd ${TARGET}
rm -rf ${TARGET}/spice-protocol
tar xvf ${TARGZ}/spice-protocol_*.tar.gz
cd ${HERE}/spice-protocol
sed -i s"/spice-protocol/cloonix-spice-protocol/" spice-protocol.spec
meson --default-library=static --prefix=${TARGET} --datadir=${TARGET} \
      --libdir=${TARGET} --includedir=${TARGET} build
cd build
ninja
ninja install
#----------------------------------------------------------
cd ${TARGET}
rm -rf ${TARGET}/usbredir
tar xvf ${TARGZ}/usbredir_*.tar.gz
cd ${HERE}/usbredir/usbredirhost
sed -i s"/libusbredirparser/libcloonix-usbredirparser/" meson.build
sed -i s"/libusbredirhost/libcloonix-usbredirhost/" meson.build
sed -i s"/library('usbredirhost'/library('cloonix-usbredirhost'/" meson.build
cd ${HERE}/usbredir/usbredirparser
sed -i s"/libusbredirparser/libcloonix-usbredirparser/" meson.build
sed -i s"/library('usbredirparser'/library('cloonix-usbredirparser'/" meson.build
cd ${HERE}/usbredir
sed -i s"/subdir('tests')/#subdir('tests')/" meson.build 
meson  --default-library=static --prefix=${TARGET} --datadir=${TARGET} \
       --libdir=${TARGET} --includedir=${TARGET} build
cd build
ninja
ninja install
#----------------------------------------------------------


