#!/bin/bash
HERE=`pwd`
#----------------------------------------------------------------------#
if [ ${#} = 1 ]; then
  if [ "$1" = "i386" ]; then
    ARCH="i386"
    QCOW2="debian_builder_i386.qcow2"
    XORG="xorg_debian_i386.qcow2"
  else
    echo param must be i386, if no param, then is amd64
    exit
  fi
else
  ARCH="amd64"
  QCOW2="debian_builder_amd64.qcow2"
  XORG="xorg_debian_amd64.qcow2"
fi
#----------------------------------------------------------------------
BULK="/var/lib/cloonix/bulk"
if [ ! -e ${BULK}/${QCOW2} ]; then
  echo
  echo Missing:
  echo ${BULK}/${QCOW2}
  echo
  exit 1
fi
#----------------------------------------------------------------------
is_started=$(cloonix_cli nemo pid |grep cloonix_server)
if [ "x$is_started" == "x" ]; then
  printf "\nServer Not started, launching:"
  printf "\ncloonix_net nemo:\n"
  cloonix_net nemo
  echo waiting 2 sec
  sleep 2
else
  cloonix_cli nemo rma
  echo waiting 10 sec
  sleep 10
fi
#----------------------------------------------------------------------
cp -f ${BULK}/${QCOW2} ${BULK}/${XORG}
sync
sleep 1
sync
#----------------------------------------------------------------------
cloonix_gui nemo
#----------------------------------------------------------------------
if [ ${ARCH} = "i386" ]; then
  cloonix_cli nemo add kvm xorg ram=12000 cpu=8 eth=s ${XORG} --persistent --i386 
else
  cloonix_cli nemo add kvm xorg ram=8000 cpu=8 eth=s ${XORG} --persistent 
fi
#----------------------------------------------------------------------
sleep 3
#----------------------------------------------------------------------
set +e
while ! cloonix_ssh nemo xorg "echo" 2>/dev/null; do
  echo xorg not ready, waiting 5 sec
  sleep 5
done
#----------------------------------------------------------------------
cloonix_scp nemo ${HERE}/xserver-master.tar.gz xorg:/root 
cloonix_scp nemo ${HERE}/xserver-master.patch xorg:/root
cloonix_ssh nemo xorg "tar xvf xserver-master.tar.gz"
cloonix_ssh nemo xorg "cd xserver-master; patch -p1 < ../xserver-master.patch"
cloonix_ssh nemo xorg "cd xserver-master; meson setup build"
cloonix_ssh nemo xorg "cd xserver-master/build; ninja"
#----------------------------------------------------------------------
cloonix_ssh nemo xorg "sync"
cloonix_ssh nemo xorg "poweroff"
#----------------------------------------------------------------------





