#!/bin/bash
set -e
HERE=`pwd`
TARGZ=${HERE}/../../../targz_store
TARGET=${HERE}/../spice_lib_client

if [ ! -e ${TARGET}/pkgconfig ]; then
  cd ${TARGET}
  ./cmd
fi

cd ${HERE}/spice_client
./patched_create

export PKG_CONFIG_PATH=${TARGET}/pkgconfig
export DESTDIR=${TARGET}
export PATH=${TARGET}/bin:$PATH
cd ${HERE}/spice_client/tainted_spice
sed -i s/UNKNOWN/0.43/ ./build-aux/git-version-gen
sed -i s'/(spice_channel_set_capability)/spice_channel_set_capability/' src/channel-display.c


meson setup -Dcoroutine=gthread build
cd build
ninja -v install

cp -vf ${TARGET}/usr/local/bin/spicy ${HERE}/cloonix-spicy
strip ${HERE}/cloonix-spicy
cp -vf ${TARGET}/usr/local/libexec/spice-client-glib-usb-acl-helper ${HERE}/cloonix-spice-client-glib-usb-acl-helper
mkdir -p ${HERE}/polkit-1/actions
cp -vf ${HERE}/spice_client/tainted_spice/data/org.spice-space.lowlevelusbaccess.policy ${HERE}/polkit-1/actions
if [ -d  ${TARGET}/usr/local/lib/x86_64-linux-gnu ]; then
  cp -vf ${TARGET}/usr/local/lib/x86_64-linux-gnu/libcloonix-spice* ${TARGET}
else
  if [ -d  ${TARGET}/usr/local/lib ]; then
    cp -vf ${TARGET}/usr/local/lib/libcloonix-spice* ${TARGET}
  else
    echo ERROR MISSING:
    echo ${TARGET}/usr/local/lib
    exit 1
  fi
fi
cd ${HERE}/spice_client
./allclean


