#!/bin/bash
HERE=`pwd`
NET=mito
#----------------------------------------------------------------------#
ARCH="amd64"
QCOW2="debian_builder_amd64.qcow2"
WIRE="wire_qt_debian_amd64.qcow2"
#----------------------------------------------------------------------
rm -rf ${HERE}/built_objects_${ARCH}
mkdir -p ${HERE}/built_objects_${ARCH}
#----------------------------------------------------------------------
BULK="/var/lib/cloonix/bulk"
if [ ! -e ${BULK}/${QCOW2} ]; then
  echo
  echo Missing:
  echo ${BULK}/${QCOW2}
  echo
  exit 1
fi
#----------------------------------------------------------------------
is_started=$(cloonix_cli ${NET} pid |grep cloonix_server)
if [ "x$is_started" == "x" ]; then
  printf "\nServer Not started, launching:"
  printf "\ncloonix_net ${NET}:\n"
  cloonix_net ${NET}
  echo waiting 2 sec
  sleep 2
else
  cloonix_cli ${NET} rma
  echo waiting 10 sec
  sleep 10
fi
#----------------------------------------------------------------------
rm -f ${BULK}/${WIRE}
cp -f ${BULK}/${QCOW2} ${BULK}/${WIRE}
sync
sleep 1
sync
#----------------------------------------------------------------------
cloonix_gui ${NET}
#----------------------------------------------------------------------
cloonix_cli ${NET} add kvm wire ram=8000 cpu=8 eth=s ${WIRE} --persistent 
#----------------------------------------------------------------------
sleep 3
#----------------------------------------------------------------------
set +e
while ! cloonix_ssh ${NET} wire "echo" 2>/dev/null; do
  echo wire not ready, waiting 5 sec
  sleep 5
done
#----------------------------------------------------------------------
cloonix_ssh ${NET} wire "mkdir -p /var/lib/cloonix/bulk"
cloonix_scp ${NET} ${HERE}/../../quickstart/demos/ping_demo.sh wire:/root
cloonix_scp ${NET} /var/lib/cloonix/bulk/zipbasic.zip wire:/var/lib/cloonix/bulk
cloonix_scp ${NET} /home/perrier/cloonix-bundle-41-00-amd64.tar.gz wire:/root 
cloonix_ssh ${NET} wire "tar xvf cloonix-bundle-41-00-amd64.tar.gz"
cloonix_ssh ${NET} wire "cd cloonix-bundle-41-00-amd64; sudo ./install_cloonix"
cloonix_ssh ${NET} wire "cat > /root/test.sh << EOF
#!/bin/bash
/root/ping_demo.sh &
sleep 15
/root/wireshark -i /var/lib/cloonix/nemo/snf/cnt1_0 -t nemo_Cloon1_eth0
EOF"
cloonix_ssh ${NET} wire "chmod +x /root/test.sh"
cloonix_ssh ${NET} wire "rm -rf cloonix-bundle-41-00-amd64"
cloonix_ssh ${NET} wire "rm -f cloonix-bundle-41-00-amd64.tar.gz"
cloonix_ssh ${NET} wire "rm -f debconf_selection"
cloonix_ssh ${NET} wire "rm -f /usr/libexec/cloonix/server/cloonix-dumpcap"
cloonix_ssh ${NET} wire "rm -f /usr/libexec/cloonix/server/cloonix-wireshark"
cloonix_ssh ${NET} wire "echo \"fs.suid_dumpable=2\" >> /etc/sysctl.conf"
cloonix_ssh ${NET} wire "echo \"kernel.core_pattern=/root/kcore\" >> /etc/sysctl.conf"
cloonix_ssh ${NET} wire "echo \"root soft core unlimited\" >> /etc/security/limits.conf"
cloonix_ssh ${NET} wire "echo \"root hard core unlimited\" >> /etc/security/limits.conf"
cloonix_ssh ${NET} wire "echo \"DefaultLimitCORE=0:infinity\" >> /etc/systemd/system.conf"
cloonix_ssh ${NET} wire "echo \"ulimit -c unlimited\" >> /root/.bashrc"
cloonix_ssh ${NET} wire "echo \" sysctl -p\" >> /root/.bashrc"
#----------------------------------------------------------------------
cloonix_ssh ${NET} wire "sync"
sleep 2
cloonix_ssh ${NET} wire "sync"
cloonix_ssh ${NET} wire "poweroff"
cloonix_cli ${NET} kil
#----------------------------------------------------------------------


