#!/bin/bash
HERE=`pwd`
set -e

rm -rf ${HERE}/agent_bin
#rm -rf ${HERE}/agent_bin_alien

cd ${HERE}/../lib_io_clownix
make clean

cd ${HERE}/cloonix_dropbear
make clean

cd ${HERE}/cloonix_agent
make clean
