#!/bin/bash

# On debian, do: sudo apt-get install libc6-dev-i386
# dpkg --add-architecture i386
# deb [arch=amd64,i386] http://deb.debian.org/debian buster main contrib non-free
# sudo apt-get install libnl-3-200:i386


HERE=`pwd`
set -e
AGENT_BIN_ALIEN=${HERE}/agent_bin_alien/
rm -rf ${AGENT_BIN_ALIEN}
mkdir -p ${AGENT_BIN_ALIEN}
${HERE}/cmd_hwsim_i386
${HERE}/cmd_hwsim_x86_64
${HERE}/cmd_i386
${HERE}/cmd_x86_64
