#!/bin/bash
HERE=`pwd`
cd ../../../lib_io_clownix/
make clean
make
cd $HERE

cd ../../lib_utils
make clean
make

cd $HERE
cd ../../muswitch/lib_blkd
make clean
make

cd $HERE
cd ../../muswitch/lib_rpct
make clean
make

cd $HERE
cd ..
make clean
make
cd $HERE
make clean
make

