#!/bin/bash
HERE=`pwd`
TARGZ=../../../targz_store
BIN=${HERE}/bin
./allclean
mkdir -p ${BIN}
tar xvf ${TARGZ}/nginx_*.tar.gz
cd ${HERE}/nginx
sed -i s'/"nginx: "/"cloonix-novnc-nginx: "/' ./src/os/unix/ngx_setproctitle.c
./auto/configure --prefix=/var/lib/cloonix/cache/nginx
make
cp ${HERE}/nginx/objs/nginx ${BIN}/cloonix-novnc-nginx
