#!/bin/bash
set -e
HERE=`pwd`
TARGZ=${HERE}/../../../targz_store
CLOONIX_COMMON=${HERE}/../../../cloonix/common
MESON_NINJA=${CLOONIX_COMMON}/meson_ninja
TARGET=${CLOONIX_COMMON}/spice/spice_lib
if [ ! -d ${TARGET} ]; then
  echo
  echo NOT FOUND:
  echo ${TARGET}
  echo
  exit
fi
#----------------------------------------------------------
cd ${TARGET}
rm -rf ${TARGET}/spice
tar xvf ${TARGZ}/spice.tar.gz
cd ${TARGET}/spice
sed -i 52s/true/false/ meson_options.txt
export PKG_CONFIG_PATH=${TARGET}/pkgconfig
export PATH=${MESON_NINJA}/ninja:$PATH
${MESON_NINJA}/meson/meson.py build
cd build
${MESON_NINJA}/meson/meson.py configure --prefix=${TARGET} \
                                        --datadir=${TARGET} \
                                        --libdir=${TARGET} \
                                        --includedir=${TARGET} 

ninja
ninja install


