#!/bin/bash
set -e
HERE=`pwd`
TARGZ=${HERE}/../../../targz_store
COMMON=${HERE}/../../../cloonix/common
NINJA=${COMMON}/meson_ninja
TARGET=${COMMON}/spice/spice_lib
if [ ! -d ${TARGET} ]; then
  echo
  echo NOT FOUND:
  echo ${TARGET}
  echo
  exit
fi
if [ ! -f ${NINJA}/ninja/ninja ]; then
  echo Doing NINJA
  sleep 1
  cd ${NINJA}
  ./cmd
  cd ${HERE}
fi

if [ ! -f ${COMMON}/spice/spice_lib/pkgconfig/spice-protocol.pc ]; then
  echo Doing COMMON SPICE
  sleep 1
  cd ${COMMON}/spice
  ./cmd
  cd ${HERE}
fi


#----------------------------------------------------------
cd ${TARGET}
rm -rf ${TARGET}/spice
tar xvf ${TARGZ}/spice.tar.gz
cd ${TARGET}/spice
sed -i 52s/true/false/ meson_options.txt
sed -i s"/'-Wno-sign-compare',/'-Wno-sign-compare','-fPIC',/" meson.build
export PKG_CONFIG_PATH=${TARGET}/pkgconfig
export PATH=${NINJA}/ninja:$PATH
${NINJA}/meson/meson.py --prefix=${TARGET} \
                        --datadir=${TARGET} \
                        --libdir=${TARGET} \
                        --includedir=${TARGET} build 
cd build

ninja
ninja install



