#!/bin/bash
#----------------------------------------------------------------------#
if [ ${#} = 1 ]; then
  if [ "$1" = "i386" ]; then
    ARCH="i386"
  else
    echo param must be i386, if no param, then is amd64
    exit
  fi
else
  ARCH="amd64"
fi
#----------------------------------------------------------------------#

#----------------------------------------------------------------------#
DISTRO=bookworm
if [ "${ARCH}" = "i386" ]; then
  ROOTFS=/var/lib/cloonix/bulk/${DISTRO}_i386.zip
else
  ROOTFS=/var/lib/cloonix/bulk/${DISTRO}.zip
fi
REPO="http://deb.debian.org/debian"
TMPZIP=/tmp/wkmntzip
#----------------------------------------------------------------------#
if [ $UID != 0 ]; then
  echo you must be root
  exit -1
fi
#-----------------------------------------------------------------------#
if [[ $(mount | egrep ${TMPZIP}) ]]; then
  echo ERROR ${TMPZIP} is visible in mount
  exit -1
fi
#-----------------------------------------------------------------------#
rm -rf ${TMPZIP}
mkdir -p ${TMPZIP}
#-----------------------------------------------------------------------#
list_pkt="openssh-client,bash-completion,vim,net-tools,x11-apps,iperf3"
debootstrap --no-check-certificate \
            --no-check-gpg \
            --arch ${ARCH} \
            --include=$list_pkt \
            ${DISTRO} \
            ${TMPZIP} ${REPO}
#-----------------------------------------------------------------------#
cd ${TMPZIP}
zip -yr ${ROOTFS} .
#-----------------------------------------------------------------------#

