#!/bin/bash
releasever=40
basearch=x86_64
DISTRO=fedora${releasever}
ROOTFS=/var/lib/cloonix/bulk/${DISTRO}.zip
MIRROR=http://distrib-coffee.ipsl.jussieu.fr/pub/linux/fedora/linux
FEDORA_MAIN=${MIRROR}/releases/${releasever}/Everything/${basearch}/os
FEDORA_MAIN_UPDATES=${MIRROR}/updates/${releasever}/Everything/${basearch}
FEDORA_MODULAR_UPDATES=${MIRROR}/updates/${releasever}/Modular/${basearch}
TMPZIP=/tmp/wkmntzip
#----------------------------------------------------------------------#
if [ $UID != 0 ]; then
  echo you must be root
  exit -1
fi
#-----------------------------------------------------------------------#
if [[ $(mount | egrep ${TMPZIP}) ]]; then
  echo ERROR ${TMPZIP} is visible in mount
  exit -1
fi
#-----------------------------------------------------------------------#
rm -rf ${TMPZIP}
mkdir -p ${TMPZIP}
#-----------------------------------------------------------------------#
set +e
for i in ${FEDORA_MAIN} ${FEDORA_MAIN_UPDATES} \
         ${FEDORA_MODULAR_UPDATES};
do
  wget --no-check-certificate --delete-after ${i} 1>/dev/null 2>&1
  OK=$?
  if [ "$OK" != "0" ]; then
    echo ERROR wget ${i}
    exit 1
  fi
echo
echo REPO OK ${i}
echo
done
#-----------------------------------------------------------------------#
mkdir -p ${TMPZIP}/etc/yum.repos.d
cat > ${TMPZIP}/etc/yum.repos.d/fedora.repo << EOF
[fedora]
name=Fedora $releasever - $basearch
baseurl=${FEDORA_MAIN}
enabled=1
gpgcheck=0
EOF
cat > ${TMPZIP}/etc/yum.repos.d/fedora-updates.repo << EOF
[updates]
name=Fedora $releasever - $basearch - Updates
baseurl=${FEDORA_MAIN_UPDATES}
enabled=1
gpgcheck=0
EOF
cat > ${TMPZIP}/etc/yum.repos.d/fedora-updates-modular.repo << EOF
[fedora-modular-updates]
name=Fedora Modular $releasever - $basearch - Updates
baseurl=${FEDORA_MODULAR_UPDATES}
enabled=1
gpgcheck=0
EOF
dnf --releasever=${releasever} --nogpgcheck --installroot=${TMPZIP} -y install bash.$basearch
dnf --releasever=${releasever} --nogpgcheck --installroot=${TMPZIP} -y install libcurl-minimal.$basearch
dnf --releasever=${releasever} --nogpgcheck --installroot=${TMPZIP} -y install openssl.$basearch
dnf --releasever=${releasever} --nogpgcheck --installroot=${TMPZIP} -y install openssl-libs.$basearch
dnf --releasever=${releasever} --nogpgcheck --installroot=${TMPZIP} -y install rpm.$basearch
dnf --releasever=${releasever} --nogpgcheck --installroot=${TMPZIP} -y install dnf
#-----------------------------------------------------------------------#
rm -f ${TMPZIP}/etc/resolv.conf
cp -f /etc/resolv.conf ${TMPZIP}
#-----------------------------------------------------------------------#
list_pkt="openssh-client bash-completion vim net-tools"
for d in dev sys proc; do mount --bind /$d ${TMPZIP}/$d; done
echo dnf clean packages
chroot ${TMPZIP} dnf --releasever=${releasever} --nogpgcheck clean packages
echo dnf -y update
chroot ${TMPZIP} dnf --releasever=${releasever} --nogpgcheck -y update
echo dnf -y install
chroot ${TMPZIP} dnf --releasever=${releasever} --nogpgcheck -y install $list_pkt
umount ${TMPZIP}/{dev,proc,sys}
#-----------------------------------------------------------------------#
if [[ $(mount | egrep ${TMPZIP}) ]]; then
  echo ERROR ${TMPZIP} is visible in mount
  exit -1
fi
#-----------------------------------------------------------------------#
cd ${TMPZIP}
zip -yr ${ROOTFS} .
#-----------------------------------------------------------------------#

