#!/bin/bash
#----------------------------------------------------------------------#
DISTRO=trixie
ROOTFS=/var/lib/cloonix/bulk/${DISTRO}.zip
REPO="http://deb.debian.org/debian"
#REPO="http://127.0.0.1/debian/bookworm"
TMPZIP=/tmp/wkmntzip
#----------------------------------------------------------------------#
if [ $UID != 0 ]; then
  echo you must be root
  exit -1
fi
#-----------------------------------------------------------------------#
if [[ $(mount | egrep ${TMPZIP}) ]]; then
  echo ERROR ${TMPZIP} is visible in mount
  exit -1
fi
#-----------------------------------------------------------------------#
rm -rf ${TMPZIP}
mkdir -p ${TMPZIP}
#-----------------------------------------------------------------------#
list_pkt="openssh-client,bash-completion,vim,net-tools,x11-apps"
debootstrap --no-check-certificate \
            --no-check-gpg \
            --arch amd64 \
            --include=$list_pkt \
            ${DISTRO} \
            ${TMPZIP} ${REPO}
#-----------------------------------------------------------------------#
cd ${TMPZIP}
zip -yr ${ROOTFS} .
#-----------------------------------------------------------------------#

