#!/bin/bash
#----------------------------------------------------------------------#
DISTRO=centos9
ROOTFS=/var/lib/cloonix/bulk/${DISTRO}.zip
REPO="https://mirror.stream.centos.org/9-stream"
TMPZIP=/tmp/wkmntzip
#----------------------------------------------------------------------#
if [ $UID != 0 ]; then
  echo you must be root
  exit -1
fi
#-----------------------------------------------------------------------#
if [[ $(mount | egrep ${TMPZIP}) ]]; then
  echo ERROR ${TMPZIP} is visible in mount
  exit -1
fi
#-----------------------------------------------------------------------#
rm -rf ${TMPZIP}
mkdir -p ${TMPZIP}
#-----------------------------------------------------------------------#
mkdir -p ${TMPZIP}/etc/yum.repos.d
for i in AppStream \
         BaseOS \
         CRB; do
cat > ${TMPZIP}/etc/yum.repos.d/CentOS-${i}.repo << EOF
[${i}]
name=CentOS-9 - ${i}
baseurl=${REPO}/${i}/x86_64/os
gpgcheck=0
EOF
done
dnf --releasever=9 --installroot=${TMPZIP} -y install dnf
#-----------------------------------------------------------------------#
rm -f ${TMPZIP}/etc/resolv.conf
cp -f /etc/resolv.conf ${TMPZIP}/etc
#-----------------------------------------------------------------------#
list_pkt="openssh-client bash-completion vim net-tools monit"
for d in dev sys proc; do mount --bind /$d ${TMPZIP}/$d; done
echo dnf --releasever=9 clean packages
chroot ${TMPZIP} dnf --releasever=9 clean packages
echo dnf --releasever=9 -y update
chroot ${TMPZIP} dnf --releasever=9 -y update
echo dnf --releasever=9 -y install
chroot ${TMPZIP} dnf --releasever=9 -y install $list_pkt
umount ${TMPZIP}/{dev,proc,sys}
#-----------------------------------------------------------------------#
if [[ $(mount | egrep ${TMPZIP}) ]]; then
  echo ERROR ${TMPZIP} is visible in mount
  exit -1
fi
#-----------------------------------------------------------------------#
cd ${TMPZIP}
zip -yr ${ROOTFS} .
#-----------------------------------------------------------------------#
