#!/bin/bash
#----------------------------------------------------------------------#
DISTRO=jammy
ROOTFS=/var/lib/cloonix/bulk/${DISTRO}.zip
REPO="http://fr.archive.ubuntu.com/ubuntu"
TMPZIP=/tmp/wkmntzip
#----------------------------------------------------------------------#
if [ $UID != 0 ]; then
  echo you must be root
  exit -1
fi
#-----------------------------------------------------------------------#
if [[ $(mount | egrep ${TMPZIP}) ]]; then
  echo ERROR ${TMPZIP} is visible in mount
  exit -1
fi
#-----------------------------------------------------------------------#
rm -rf ${TMPZIP}
mkdir -p ${TMPZIP}
#-----------------------------------------------------------------------#
if [ ! -e /usr/share/debootstrap/scripts/${DISTRO} ]; then
  cd /usr/share/debootstrap/scripts
  ln -s gutsy ${DISTRO}
  cd $HERE
fi
#-----------------------------------------------------------------------#
list_pkt="openssh-client,bash-completion,vim,net-tools"
debootstrap --no-check-certificate --no-check-gpg --arch amd64 \
            --components=multiverse,universe,main \
            --include=$list_pkt \
            ${DISTRO} ${TMPZIP} ${REPO}
#-----------------------------------------------------------------------#
cat > ${TMPZIP}/etc/apt/sources.list << EOF
deb ${REPO} ${DISTRO} main universe
deb ${REPO} ${DISTRO}-security main universe 
deb ${REPO} ${DISTRO}-updates main universe 
EOF
#-----------------------------------------------------------------------#
cd ${TMPZIP}
zip -yr ${ROOTFS} .
#-----------------------------------------------------------------------#

