#!/bin/bash
set -e
HERE=`pwd`
#LIST="arch \
#      centos8 \
#      opensuse152 \

LIST="disco \
      eoan \
      buster \
      fedora30 \
      openwrt"
CLOONIX_BULK=${HOME}/cloonix_data/bulk
mkdir -p ${CLOONIX_BULK}
sudo echo "sudoer rights given"
for i in ${LIST}; do
  sudo rm -f ${CLOONIX_BULK}/${i}.qcow2
  sudo rm -f /root/${i}
  sudo rm -f /root/${i}.qcow2
done
for i in ${LIST}; do
  echo BEGIN ${i}  
  sudo ${HERE}/${i}.sh
  echo END ${i}  
  sudo mv -v /root/${i}.qcow2 ${CLOONIX_BULK}
  echo MOVED ${i}.qcow2  
done
