#!/bin/bash
rm -rf build
mkdir build
cp -f conf.py index.rst Makefile build
cp -rf doc png build
cd build 
sed -i s"/__LAST__/49-00/"g conf.py
sed -i s"/__LAST__/49-00/"g index.rst
sed -i s"/__LAST__/49-00/"g doc/configure.rst
sed -i s"/__LAST__/49-00/"g doc/building.rst
sed -i s"/__LAST_BASE__/49/"g doc/building.rst
sed -i s"/__LAST__/49-00/"g doc/installation.rst
sed -i s"/__LAST_BASE__/49/"g doc/installation.rst
make clean
make html
make singlehtml
