#!/bin/bash
rm -rf build
mkdir build
cp -f conf.py index.rst Makefile build
cp -rf doc png build
cd build 
sed -i s"/__LAST__/20-00/"g conf.py
sed -i s"/__LAST__/20-00/"g index.rst
sed -i s"/__LAST__/20-00/"g doc/instructions.rst
sed -i s"/__LAST__/20-00/"g doc/manual.rst
make clean
make html
make singlehtml
