#!/bin/bash
#----------------------------------------------------------------------------#
HERE=`pwd`
NET="nemo"
NAME="alpine"
ALPINE3="/var/lib/cloonix/bulk/alpine3"
ALPINE_BUILDER="/var/lib/cloonix/bulk/alpine_builder"
#----------------------------------------------------------------------------#
is_started=$(cloonix_cli $NET pid |grep cloonix_server)
if [ "x$is_started" == "x" ]; then
  printf "\nServer Not started, launching:"
  printf "\ncloonix_net $NET:\n"
  cloonix_net $NET
else
  echo cloonix $NET working! Please kill it with:
  echo cloonix_cli $NET kil
  exit 1
fi
#----------------------------------------------------------------------------#
if [ -e ${ALPINE_BUILDER} ]; then
  echo ${ALPINE_BUILDER} already exists, erasing
  unshare --user --fork --pid --mount --mount-proc \
          --map-users=100000,0,10000 --map-groups=100000,0,10000 \
          --setuid 0 --setgid 0 -- \
          /bin/bash -c "\
                       rm -rf ${ALPINE_BUILDER}"
fi
if [ -e ${ALPINE_BUILDER} ]; then
  echo ERROR ${ALPINE_BUILDER} exists and cannot be erased
  exit 1
fi
#----------------------------------------------------------------------#

#----------------------------------------------------------------------#
unshare --user --fork --pid --mount --mount-proc \
        --map-users=100000,0,10000 --map-groups=100000,0,10000 \
        --setuid 0 --setgid 0 -- \
        /bin/bash -c "\
                     cp -rf ${ALPINE3} ${ALPINE_BUILDER}"
#----------------------------------------------------------------------#
cloonix_gui ${NET}
cloonix_cli ${NET} add cvm ${NAME} eth=s alpine_builder --persistent
cloonix_cli ${NET} add nat nat
cloonix_cli ${NET} add lan ${NAME} 0 lan1
cloonix_cli ${NET} add lan nat 0 lan1
#----------------------------------------------------------------------------#
set +e
while ! cloonix_ssh ${NET} ${NAME} "echo" 2>/dev/null; do
  echo ${NAME} not ready, waiting 3 sec
  sleep 3
done
set -e
#----------------------------------------------------------------------------#
cloonix_ssh ${NET} ${NAME} "dhcpcd eth0"
#----------------------------------------------------------------------------#
LIST=""
LIST="${LIST} build-base bash vim pkgconfig linux-headers openssl-dev"
LIST="${LIST} ninja-build meson glib-dev gtk+3.0-dev libusb-dev cmake"
LIST="${LIST} py3-six json-glib-dev gstreamer-dev gst-plugins-base-dev"
LIST="${LIST} polkit-dev acl-dev acl-static opus-dev usbutils phodav-dev"
LIST="${LIST} libcap-dev libcap-ng-dev libva-dev perl libcap-setcap"
LIST="${LIST} libxkbfile-dev libxfont2-dev libxcvt-dev eudev-dev"
LIST="${LIST} qt6-qtbase-dev qt6-qttools-dev qt6-qt5compat-dev"
LIST="${LIST} libpcap-dev gperf argp-standalone libxt-dev libxmu-dev"
LIST="${LIST} libsm-dev libice-dev lz4-dev libaio-dev liburing-dev"
LIST="${LIST} openssh xorriso xfce4 xfce4-terminal xfce4-session"
LIST="${LIST} font-dejavu xeyes rsyslog dbus dbus-x11 strace"
LIST="${LIST} gpg-agent pm-utils"

#  while [ 1 ]; do
#    cloonix_ssh ${NET} ${NAME} "rm -f main"
#    cloonix_ssh ${NET} ${NAME} "wget http://172.17.0.2/alpine/main"
#  done

apkcmd="apk --allow-untrusted --no-cache --update add"

for i in ${LIST}; do
  echo DOING: ${i}
  cloonix_ssh ${NET} ${NAME} "${apkcmd} ${i}"
done

LIST="syslog dbus"
for i in ${LIST}; do
  echo DOING: "rc-update add ${i}"
  cloonix_ssh ${NET} ${NAME} "rc-update add ${i}"
done

#----------------------------------------------------------------------------#
cloonix_ssh ${NET} ${NAME} "sync"
cloonix_ssh ${NET} ${NAME} "poweroff"
cloonix_cli ${NET} kil
#----------------------------------------------------------------------------#



