#!/bin/bash
#----------------------------------------------------------------------#
HERE=`pwd`
NET="mito"
DISTRO="trixie"
QCOW2="${DISTRO}_builder.qcow2"
NAME="dev"
CLOONIX_TREE_ROOT=${HERE}/../..
#######################################################################
is_started=$(cloonix_cli $NET pid |grep cloonix_server)
if [ "x$is_started" == "x" ]; then
  printf "\nServer Not started, launching:"
  printf "\ncloonix_net $NET:\n"
  cloonix_net $NET
else
  cloonix_cli $NET rma
fi
#----------------------------------------------------------------------
rm -f cloonix-*
rm -rf /tmp/cloonix_build_tree
mkdir -p /tmp/cloonix_build_tree
cd ${CLOONIX_TREE_ROOT}
./allclean
tar zcvf /tmp/cloonix_build_tree/sources.tar.gz .
cd ${CLOONIX_TREE_ROOT}/build_tools
#----------------------------------------------------------------------
cloonix_gui ${NET}
#----------------------------------------------------------------------
PARAMS="ram=8000 cpu=4 eth=s"
cloonix_cli ${NET} add kvm ${NAME} ${PARAMS} ${QCOW2}

#----------------------------------------------------------------------
sleep 3
#----------------------------------------------------------------------
set +e
while ! cloonix_ssh ${NET} ${NAME} "echo" 2>/dev/null; do
  echo ${NAME} not ready, waiting 5 sec
  sleep 5
done
#----------------------------------------------------------------------
cloonix_ssh ${NET} ${NAME} "mkdir -p /root/sources"
cloonix_scp ${NET} /tmp/cloonix_build_tree/sources.tar.gz ${NAME}:/root/sources
cloonix_ssh ${NET} ${NAME} "mkdir -p /var/lib/cloonix/bulk"
cloonix_ssh ${NET} ${NAME} "cd /root/sources ; tar xvf sources.tar.gz ; rm sources.tar.gz"
cloonix_ssh ${NET} ${NAME} "cd /root/sources; ./doitall"
#----------------------------------------------------------------------
cloonix_scp ${NET} -r ${NAME}:/root/sources/build_tools/cloonix-bundle-* ${CLOONIX_TREE_ROOT}/build_tools
rm -rf /tmp/cloonix_build_tree
#----------------------------------------------------------------------


