#!/bin/bash
HERE=`pwd`
DISTRO=fedora38
NET=nemo
NAME=dev
QCOW2=fedora_builder.qcow2
BULK="/var/lib/cloonix/bulk"
#----------------------------------------------------------------------
cloonix_net ${NET}
#----------------------------------------------------------------------
echo cp -f ${BULK}/${DISTRO}.qcow2 ${BULK}/${QCOW2}
cp -f ${BULK}/${DISTRO}.qcow2 ${BULK}/${QCOW2}
#----------------------------------------------------------------------
sync
#----------------------------------------------------------------------
cloonix_gui ${NET}
cloonix_cli ${NET} add nat nat
#----------------------------------------------------------------------
PARAMS="ram=8000 cpu=4 eth=s"
cloonix_cli ${NET} add kvm ${NAME} ${PARAMS} ${QCOW2} --persistent
#----------------------------------------------------------------------
sleep 3
cloonix_cli ${NET} add lan ${NAME} 0 lan1
cloonix_cli ${NET} add lan nat 0 lan1
#----------------------------------------------------------------------
set +e
while ! cloonix_ssh ${NET} ${NAME} "echo" 2>/dev/null; do
  echo ${NAME} not ready, waiting 5 sec
  sleep 5
done
#----------------------------------------------------------------------
cloonix_ssh ${NET} ${NAME} "dhclient eth0"
#----------------------------------------------------------------------
cloonix_ssh ${NET} ${NAME} "dnf update -y"

cloonix_ssh ${NET} ${NAME} "dnf install -y make gcc gcc-c++ gdb \
                 libstdc++-devel intltool glibc-devel libtool tar \
                 pkg-config glib2-devel meson ninja-build patch \
                 tar openssl-devel glib2-devel pixman-devel strace \
                 python3-six python3-pyparsing libjpeg-turbo-devel \
                 polkit-devel lz4-devel libacl-devel cyrus-sasl-devel \
                 libunwind-devel numactl-devel gtk3-devel libepoxy-devel \
                 libpcap-devel json-glib-devel libcap-ng-devel fuse3-devel \
                 fuse-overlayfs bzip2 rxvt-unicode xorriso libusb1-devel \
                 yajl-devel git libcap-devel libseccomp-devel \
                 libptytty-devel"

cloonix_ssh ${NET} ${NAME} "dnf install -y meson gtk3-devel openssl-devel \
                            pulseaudio-libs-devel pulseaudio \
                            pixman-devel gobject-introspection-devel \
                            libjpeg-turbo-devel zlib-devel cyrus-sasl-devel \
                            gtk-doc gettext-devel vala python3 \
                            python3-pyparsing"

cloonix_ssh ${NET} ${NAME} "dnf install -y gstreamer1-devel \
                            gstreamer1-plugins-base-devel \
                            gstreamer1-plugins-good \
                            gstreamer1-plugins-bad-free"

cloonix_ssh ${NET} ${NAME} "dnf install -y c-ares-devel \
                            libpcap-devel \
                            pcre2-devel \
                            flex \
                            cmake \
                            python3 \
                            libgcrypt-devel \
                            speexdsp-devel \
                            qt6-qtbase-devel \
                            qt6-qttools-devel \
                            qt6-qt5compat-devel \
                            qt6-qtmultimedia-devel \
                            libxkbcommon-devel" 

#----------------------------------------------------------------------
cloonix_ssh ${NET} ${NAME} "sync"
cloonix_ssh ${NET} ${NAME} "poweroff"
#----------------------------------------------------------------------


