#!/bin/bash
HERE=`pwd`
DISTRO=bookworm
NET=nemo
NAME=dev
QCOW2=debian_builder.qcow2
BULK="/var/lib/cloonix/bulk"
REPO="http://172.17.0.2/debian/bookworm"
#######################################################################
is_started=$(cloonix_cli $NET pid |grep cloonix_server)
if [ "x$is_started" == "x" ]; then
  printf "\nServer Not started, launching:"
  printf "\ncloonix_net $NET:\n"
  cloonix_net $NET
else
  cloonix_cli $NET rma
fi
#----------------------------------------------------------------------
echo cp -f ${BULK}/${DISTRO}.qcow2 ${BULK}/${QCOW2}
cp -f ${BULK}/${DISTRO}.qcow2 ${BULK}/${QCOW2}
#----------------------------------------------------------------------
sync
#----------------------------------------------------------------------
cloonix_gui ${NET}
cloonix_cli ${NET} add nat nat
#----------------------------------------------------------------------
PARAMS="ram=8000 cpu=4 eth=s"
cloonix_cli ${NET} add kvm ${NAME} ${PARAMS} ${QCOW2} --persistent
#----------------------------------------------------------------------
sleep 3
cloonix_cli ${NET} add lan ${NAME} 0 lan1
cloonix_cli ${NET} add lan nat 0 lan1
#----------------------------------------------------------------------
set +e
while ! cloonix_ssh ${NET} ${NAME} "echo" 2>/dev/null; do
  echo ${NAME} not ready, waiting 5 sec
  sleep 5
done
#----------------------------------------------------------------------
cloonix_ssh ${NET} ${NAME} "dhclient eth0"
#----------------------------------------------------------------------
cloonix_ssh ${NET} ${NAME} "cat > /etc/apt/sources.list << EOF
deb ${REPO} ${DISTRO} main contrib non-free non-free-firmware
EOF"
#----------------------------------------------------------------------
cloonix_ssh ${NET} ${NAME} "apt-get --assume-yes update"

cloonix_ssh ${NET} ${NAME} "apt-get -y install \
                      tar build-essential g++ cmake \
                      pkg-config intltool libtool meson ninja-build \
                      libssl-dev libusb-1.0-0-dev patch libglib2.0-dev \
                      libpixman-1-dev python3 python3-six sudo xauth \
                      python3-pyparsing python3-venv libjpeg-dev \
                      pulseaudio libpulse-dev libgstreamer1.0-dev \
                      libgstreamer-plugins-base1.0-dev \
                      libgstreamer-plugins-bad1.0-dev \
                      gstreamer1.0-plugins-bad-apps \
                      gstreamer1.0-plugins-base-apps \
                      liblz4-dev libpcap-dev libsasl2-dev \
                      libnuma-dev libepoxy-dev xorriso \
                      libgtk-3-dev libjson-glib-dev libacl1-dev \
                      libpolkit-gobject-1-dev busybox-static \
                      libyajl-dev make git libsystemd-dev \
                      libprotobuf-c-dev libcap-dev libseccomp-dev \
                      libgcrypt20-dev go-md2man locales libffi-dev \
                      libfdt-dev libfuse-dev libarchive-dev libaio-dev \
                      liburing-dev fuse-zip libasound2-dev libc-ares-dev \
                      libpcre2-dev flex libgcrypt-dev libspeexdsp-dev \
                      qt6-base-dev qt6-multimedia-dev qt6-tools-dev \
                      qt6-tools-dev-tools qt6-l10n-tools \
                      libqt6core5compat6-dev freeglut3-dev libvulkan-dev \
                      libxkbcommon-dev libnl-3-dev libkrb5-dev libsmi2-dev \
                      libsbc-dev liblua5.2-dev libnl-cli-3-dev \
                      libparse-yapp-perl libsnappy-dev libzstd-dev \
                      libspandsp-dev libxml2-dev libminizip-dev \
                      perl xsltproc ccache doxygen bison \
                      ncurses-base strace tilix libsecret-1-0 \
                      gvfs-libs libibus-1.0-5"

#----------------------------------------------------------------------
cloonix_ssh ${NET} ${NAME} "sync"
cloonix_ssh ${NET} ${NAME} "poweroff"
#----------------------------------------------------------------------


